### ISSUE TITLE
Correctly read coroutine Flow

### ISSUE THREAD

**Issue by nenros** [micronaut-projects/micronaut-openapi#1013]
### Feature description

Hi! 
I'm trying to build api using coroutines and on endpoint where i respondd with flow I get `Flow_ServiceProviderResponse_` without any schema.
I guess it should be added here https://github.com/micronaut-projects/micronaut-openapi/blob/master/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java#L1268

P.S. Openapi don't work with KSP, any chance to fix it in the future?

**Comment by altro3** [comment]
@nenros Hi! Could you add example and add more information what now wrong and how need it work, because now I don't understand what is the problem?

**Comment by nenros** [comment]
i have such method 
```
    @Get(produces = [MediaType.APPLICATION_JSON])
    fun getAllServiceProviders() = serviceProviderService.getAllServiceProviders()
        .map { it.toResponse() }
 ```
`serviceProviderService.getAllServiceProviders()` gives https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/

and in schema it produces somthing like that

```
    get:
      operationId: getAllServiceProviders
      responses:
        "200":
          description: getAllServiceProviders 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flow_ServiceProviderResponse_'
```
Which looks like that:
```
components:
  schemas:
    Flow_ServiceProviderResponse_:
      type: object
```

When I change that asFlux for example(whatever, can be list):
```
      responses:
        "200":
          description: getAllServiceProviders 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceProviderResponse'
    
    ```
and component schema:
```
    ServiceProviderResponse:
      required:
      - description
      - id
      - name
      - slug
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        slug:
          type: string
          ```

**Comment by altro3** [comment]
ok, thanks! but it would be nice to have full emple app, because I will have to test the fix

**Comment by dstepanov** [comment]
@nenros Do you use Micronaut 4 Milestone with KSP?

**Comment by nenros** [comment]
@dstepanov yes, it isn't working, i had to change back to kapt because of 
```
kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
	at io.micronaut.kotlin.processing.KotlinOutputVisitor.visitGeneratedFile(KotlinOutputVisitor.kt:66)
	at io.micronaut.kotlin.processing.visitor.KotlinVisitorContext.visitGeneratedFile(KotlinVisitorContext.kt:158)
	at io.micronaut.inject.visitor.VisitorContext.getProjectDir(VisitorContext.java:172)
	at io.micronaut.openapi.visitor.OpenApiApplicationVisitor.resolve(OpenApiApplicationVisitor.java:632)
	at io.micronaut.openapi.visitor.OpenApiApplicationVisitor.readOpenApiConfigFile(OpenApiApplicationVisitor.java:665)
	at io.micronaut.openapi.visitor.OpenApiApplicationVisitor.endPointsConfiguration(OpenApiApplicationVisitor.java:652)
	at io.micronaut.openapi.visitor.OpenApiEndpointVisitor.visitClass(OpenApiEndpointVisitor.java:83)
```

It isn't related to topic of that issue. Probably i should prepare new bug for it.

**Comment by dstepanov** [comment]
Can you please create an issue in Core? Thanks for testing!
