### ISSUE TITLE
Ability to generate spec in json instead of yaml

### ISSUE THREAD

**Issue by vanga** [micronaut-projects/micronaut-openapi#102]
Hi,

I would like to know if there is any OOTB or an easy extension point to generate the OpenAPI spec in json format instead of Yaml. 

Thanks.

**Comment by ilopmar** [comment]
At this moment the only output is Yaml and it's done here https://github.com/micronaut-projects/micronaut-openapi/blob/ff28234c8c23c9f1a1c443865420c5527e6c33ef/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java#L259-L298

It shouldn't be too complicated to add support there to serialize to json based on some configuration property.

**Comment by vanga** [comment]
Thanks @ilopmar I will close this for now and take a dig at this code, to see if it's something that I can add easily

**Comment by murdos** [comment]
Hi! Can this issue be reopened? 
I think this feature is interesting to have too.

**Comment by hc-codersatlas** [comment]
Json will make it easier to be parsed by frontend services instead of yaml (using javascript). Likely faster to generate too.

**Comment by Hexer338** [comment]
+1  for this feature.

**Comment by vinmorel** [comment]
+1

**Comment by chrisrote-esper** [comment]
+1 swagger.json integrates better with many of the 3rd party tools we use
