### ISSUE TITLE
Migrate generator from openapi-generator

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-openapi#1037]
### Issue description

Currently, our OpenAPI generation strategy lives in the [OpenAPI Generator project](https://github.com/OpenAPITools/openapi-generator). This causes a number of issues:

- the generator is quite outdated. It generates code for Micronaut 3.4. The code is _not_ compatible with Micronaut 4.
- it cannot be easily tested with newer releases of Micronaut
- it reproduces logic which exists in Micronaut Launch (code generation), without the flexibility of Micronaut Launch
- It's "one shot" only, meaning that it is not possible to incrementally add new APIs
- it is not integrated with our build plugins
- the [guide](https://guides.micronaut.io/latest/micronaut-openapi-generator-server-gradle-java.html) is not consistent with the experience of other guides

Therefore, we should migrate the logic from the [OpenAPI Generator project](https://github.com/OpenAPITools/openapi-generator) to this project, as a submodule. It is perfectly acceptable to reuse the same code as in the original project, by having a dependency on OpenAPI generator. The difference is that *we* handle the releases of the Micronaut support, and we can create consistent experience.

This should let us:

- implement code generation directly in Micronaut Launch _or_
- add support for OpenAPI code generation in our build plugins

(build plugins support is currently our main focus).

**Comment by sdelamo** [comment]
@melix we merged https://github.com/micronaut-projects/micronaut-openapi/pull/1040 but it needs documentation. Docs are currently out of date: 

> If you wish to generate Micronaut projects from OpenAPI definition files, utilize the [OpenAPI Generator](https://openapi-generator.tech/)'s Micronaut support. Refer to the ["Micronaut server generation with OpenAPI" guide](https://guides.micronaut.io/latest/micronaut-openapi-generator-server) or the ["Micronaut Client generation with OpenAPI" guide](https://guides.micronaut.io/latest/micronaut-openapi-generator-client) for details.

**Comment by melix** [comment]
The merged PR only adds support for the generator in Micronaut OpenAPI. It is not effectively usable without build plugins, or invoking directly the API. I think we need to add support for this first, then we can update the docs and guides.

**Comment by altro3** [comment]
@melix as I understand, this issue already completed. Can I close it?

**Comment by melix** [comment]
I'm using it to track documentation too, I'm looking at the guides now.

**Comment by melix** [comment]
First guide PR: https://github.com/micronaut-projects/micronaut-guides/pull/1297
