### ISSUE TITLE
How to build Swagger/Rapidoc UI Views with build.gradle and Kotlin-only? 

### ISSUE THREAD

**Issue by lathspell** [micronaut-projects/micronaut-openapi#108]
The documenation on
https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#openApiViews
has an example how to specifiy "-Dmicronaut.openapi.view.spec" in build.gradle file for a Java project.

This seems to have no effet on a Kotlin-only project though. I tried the following but with no success:

```
dependencies {
    ...
    kapt "io.micronaut.configuration:micronaut-openapi"
    implementation "io.micronaut:micronaut-views"
    implementation "io.swagger.core.v3:swagger-annotations"
    ...
}
compileKotlin {
    // https://kotlinlang.org/docs/reference/using-gradle.html
	kotlinOptions {
        verbose = true
	    jvmTarget = '1.8'
	    // Will retain parameter names for Java reflection
	    javaParameters = true
        // Generate OpenAPI UIs
        // DOES NOT COMPILE: freeCompilerArgs += '-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop'
        freeCompilerArgs += '-Xjavac-arguments=-J-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop'
        freeCompilerArgs += '-Xjavac-arguments=-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop'
	}
}
```

How should I add those parameters? 

(BTW, compiler args seem somewhat ugly, can't this be configured just by adding a specific Gradle plugin or dependency?)

**Comment by croudet** [comment]
Have you try with https://kotlinlang.org/docs/reference/kapt.html#java-compiler-options

**Comment by lathspell** [comment]
I tried the following with no success. There is no error message either, the build runs fine but does not produce any HTML files or similar for the UI.

```
kapt {
    javacOptions {
        option('-J-Dmicronaut.openapi.views.spec', 'rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop')
        option('-Dmicronaut.openapi.views.spec', 'rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop')
        option('micronaut.openapi.views.spec', 'rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop')
        option('-Kapt-javac-option:micronaut.openapi.views.spec', 'rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop')
        option('-Kapt-verbose', 'true')
    }
}
```

I couldn't find any project on Github either that generates a Swagger API with Micronaut for a pure Kotlin app :-( If you are aware of any, please let me know.

**Comment by graemerocher** [comment]
The example at https://github.com/micronaut-projects/micronaut-examples/tree/master/hello-world-kotlin does so

My suspicion is that because Gradle uses a compiler daemon for compiling Kotlin code that you would need to pass the system properties to the compiler daemon. This is ugly I know, but I am unaware of a better way with Kotlin.

Something like:

```
./gradlew --no-daemon -Dkotlin.daemon.jvm.options="...system properties here..." clean assemble
```

This comes from my how I typically attach a debugger to the Kotlin compiler. See https://discuss.kotlinlang.org/t/debug-annotation-processor-kapt/11369/5

**Comment by lathspell** [comment]
Neither the hello-kotlin-java nor ~-kotlin example from micronaut-examples generates one of the OpenAPI UIs? Maybe the swagger.yml at runtime but they do not have HTML files in the build/target directories.

Using custom JVM options for Gradle is indeed way to ugly, I rather copy the Swagger-UI HTML files by hand into the resource folder :)

**Comment by rmberg** [comment]
JFYI @graemerocher's suggestion just above worked for me

**Comment by lathspell** [comment]
Thanks to @rmberg , your command line works for me as well now.

I tested with a newly created demo project not with the one at work though. In the demo project all three views were generated by default anyway so I did not even needed to set the properties. I verified that I can disable one specific view so it does get picked up by the compiler.

Could this be added to https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html ? Either how to define it in build.gradle for Kotlin projects or how to use the environment variable with a non-deamon Gradle as in your example.

**Comment by graemerocher** [comment]
Seems a great way to contribute to the project. PRs welcome!

**Comment by lathspell** [comment]
This should be done by the author of the openapi annotation processor package so that he can explain why we need environment variables and not just variables in the Gradle build file.

BTW, funny thing is that on my Mac at work, the very same git repository only generates the frontend when using your command line. On my Linux at home I was sure that the views for all three frontends were generated by default after adding the proper lines to the build.gradle file.

**Comment by graemerocher** [comment]
The author may have no experience in Kotlin and since this is a Kotlin specific thing who knows who is best placed to contribute this documentation. I doubt very much the author had Kotlin specifically in mind as Micronaut in general is not built just for Koltin.  I also don't know why the Kotlin Gradle integration makes it so difficult to customize compiler arguments (even to a attach a debugger) and even the author will not know the reason for that necessarily as it is something better explained by the Kotlin team.

**Comment by willbuck** [comment]
@lathspell has your concern been addressed? Is there anything further needed beyond the PR you graciously submitted?

**Comment by lathspell** [comment]
Needing to use JAVA_TOOL_OPTIONS to build documentation is ugly. As it's now at least documented you can close this issue. I would be happy to see if the plugin gets somewhen improved though :)

**Comment by willbuck** [comment]
@lathspell as I understand the issue, I think we're largely constrained by Gradle and Kotlin on this matter, unfortunately. If you encounter more elegant solutions out in the wild though, please share them!

**Comment by cristianrgreco** [comment]
Hi, the proposed solutions do not work for me. Micronaut version 1.3.0, Kotlin 1.3.61, Gradle 6.0.1. 

Following deps:

```
compile "io.swagger.core.v3:swagger-annotations"
kapt "io.micronaut.configuration:micronaut-openapi"
```

The YAML is correctly created under `/build/tmp/kapt3/classes/main/META-INF/swagger/XXX.yml` but I cannot get Micronaut to generate a UI.

This command does not work any UI: 
```
​JAVA_TOOL_OPTIONS=-Dmicronaut.openapi.views.spec=redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop ​./gradlew --no-daemon clean assemble
```

Neither does this one but I assume this one works only for Java anyway:
```
tasks.withType(JavaCompile) {
    options.fork = true
    options.forkOptions.jvmArgs << '-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop'
}
```

I've tried an equivalent for Kotlin also to no avail:
```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        freeCompilerArgs += '-Xjavac-arguments=-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop'
    }
}
```

I'm out of ideas, any help would be much appreciated!

**Comment by croudet** [comment]
Can you try:
- set in *gradle.properties*
```
org.gradle.jvmargs=-Dmicronaut.openapi.views.spec=redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui
.theme=flattop
```
- then
```
export JAVA_TOOL_OPTIONS=-Dmicronaut.openapi.views.spec=redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop
./gradlew clean compileKotlin --no-daemon
```

**Comment by cristianrgreco** [comment]
@croudet That worked, thank you! Is there a way we can move this code to the `build.gradle` file?

```
export JAVA_TOOL_OPTIONS=-Dmicronaut.openapi.views.spec=redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop
./gradlew clean compileKotlin --no-daemon
```

**Comment by croudet** [comment]
I am not sure it is possible, you can try what is suggested here:
https://github.com/micronaut-projects/micronaut-openapi/issues/108#issuecomment-564432223

**Comment by cristianrgreco** [comment]
Actually it seems gradle is also picking up the properties from the `gradle.properties` file so there's no need to export `JAVA_TOOL_OPTIONS`, just `./gradlew clean compileKotlin --no-daemon` is sufficient.

**Comment by miguelbaldi** [comment]
@graemerocher @croudet  I've baking a patch to make use of APT arguments and enable kotlin to configure openapi extension in the build script instead of using environment variable. I was planning to link to this issue. Should we reopen this issue or should we create another one?

**Comment by croudet** [comment]
@miguelbaldi I think everything have been taking care.
Currently `micronaut-openapi` is compatible with all version of  `micronaut-core`, so I made a PR
https://github.com/micronaut-projects/micronaut-core/pull/2779 to keep it like that.
And `@SupportedOptions` have been added to the project.

So it will work with system properties and annotation processor options.

**Comment by miguelbaldi** [comment]
> @miguelbaldi I think everything have been taking care.
> Currently `micronaut-openapi` is compatible with all version of `micronaut-core`, so I made a PR
> [micronaut-projects/micronaut-core#2779](https://github.com/micronaut-projects/micronaut-core/pull/2779) to keep it like that.
> And `@SupportedOptions` have been added to the project.
> 
> So it will work with system properties and annotation processor options.

Ok, but with kotlin does not work with APT options (only environment variable). My patch address that issue. At least with `openapi.properties` everything works fine with kotlin too!

Thanks @croudet !

**Comment by croudet** [comment]
I don't know kotlin, but https://kotlinlang.org/docs/reference/kapt.html#annotation-processor-arguments is this the way to pass annotation processor options?

**Comment by croudet** [comment]
I took a look at your branch, it requires micronaut-core v2. I don't know if it is the way we want it.

**Comment by miguelbaldi** [comment]
> I took a look at your branch, it requires micronaut-core v2. I don't know if it is the way we want it.

Exactly, it depends on commit https://github.com/micronaut-projects/micronaut-core/pull/2702

Current version is not taking APT arguments, only environment variable or openapi.properties (https://github.com/micronaut-projects/micronaut-openapi/blob/521b864645f711a60dabbcee208ddc8685436eec/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java#L313), if you look at my fork, you will be able to understand: https://github.com/miguelbaldi/micronaut-openapi/commit/59879a9606660584480b40287ed95a9fb9e0a3cb

With Kotlin APT plugin, the configuration would look like:
```
kapt {
    arguments {
        arg("micronaut.openapi.views.spec","rapidoc.enabled=true,swagger-ui.enabled=true,redoc.enabled=tru
    }   
}
```

But I made this patch before the `openapi.properties` support. Maybe now It's useless.
Anyway, thanks for your time

**Comment by croudet** [comment]
It will work with https://github.com/micronaut-projects/micronaut-core/pull/2779 that puts annotation processor options in system properties.

**Comment by adamkobor** [comment]
Sorry for nagging about this again, but it's not clear to me, what is the working solution for the problem described above. I've made it to work in one of our projects (Kotlin + Gradle), but now I can't do it to an other the same way, so I think that the first one was only a lucky mistake after trying several approaches randomly :D 
Micronaut version: 1.3.2, micronaut-openapi: 1.4.0

**Comment by croudet** [comment]
You can create a file `openapi.properties` at the root of your project.
