### ISSUE TITLE
SLF4J Issues still exist in latest milestone for 4

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-openapi#1085]
### Expected Behavior

No SLF4J issues

### Actual Behaviour

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```

### Version

Micronaut 4.0.0-M4

**Comment by altro3** [comment]
@graemerocher The reason for this is the incorrect merging of branches. Fixed here: https://github.com/micronaut-projects/micronaut-core/pull/9532
