### ISSUE TITLE
generated security declaration in yaml has wrong format

### ISSUE THREAD

**Issue by dlamoris** [micronaut-projects/micronaut-openapi#110]
Hi, I have a controller method annotated like this:
```
 @Operation(operationId = "doStuff", security = @SecurityRequirement(name = "BasicAuth", scopes={}))
```

and in the generated yaml, it has this
```
security:
  - name:
    - BasicAuth
```

but according to the openapi doc (https://swagger.io/docs/specification/authentication/basic-authentication/), it should be
```
security:
  - BasicAuth: []
```

**Comment by croudet** [comment]
I think a current work around is to use `SecuritryRequirement` outside `Operation`:
```
@SecurityRequirement(name = "BasicAuth", scopes={})
@Operation(operationId = "doStuff")
```

**Comment by dlamoris** [comment]
thanks, that works!
