### ISSUE TITLE
Cannot generate schema for response having a collection of enums (Groovy)

### ISSUE THREAD

**Issue by tcrespog** [micronaut-projects/micronaut-openapi#1135]
### Expected Behavior

The OpenAPI schema should be generated when a response class contains an attribute that is a collection of enum elements.

### Actual Behaviour

The schema generation fails with the following error when a response class contains an attribute that is a collection of enum elements (at least in Groovy).

```
> Task :compileGroovy FAILED
1 actionable task: 1 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> BUG! exception in phase 'semantic analysis' in source unit '/home/user/mn-openapi-enums/src/main/groovy/mn/openapi/enums/controller/DogController.groovy' Cannot invoke "io.swagger.v3.oas.models.media.Schema.setName(String)" because "schema" is null
```

### Steps To Reproduce

1. Download the sample app.
2. Look at the `Dog` class, which contains a `Set<Trait> traits` attribute, being `Trait` an `enum`.
3. Look at the `DogController` class, which contains a method returning a `Dog` instance.
4. Run the `compileGroovy` task.
5. The schema generation fails.

### Environment Information

- Operating System: Linux
- JDK version: Java 17

### Example Application

https://github.com/tcrespog/mn-openapi-enums

### Version

3.9.4

**Comment by altro3** [comment]
@tcrespog Hi! Hmm... it's a bug in micronaut-core. When classes anylizing micronaut-core return generic ofthis Set as ClassElement, but must be EnumElement.

I added a crutch to get around this bug. so in version 4.10.0 everything will work correctly

**Comment by altro3** [comment]
@tcrespog By the way, the bug is reproduced only in micronaut 3, in version 4 everything works correctly. so you can try using micronaut-openapi latest version 5.0.1
