### ISSUE TITLE
Document micronaut-openapi-annotations

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-openapi#1152]
### Issue description

We should not list the version and we should tell people to use io.micronaut.openapi:micronaut-open-api dependency instead of swagger-annotations: 

![CleanShot 2023-07-31 at 15 40 30](https://github.com/micronaut-projects/micronaut-openapi/assets/864788/c1435cd1-a925-4998-8d65-1a885b41bed8)

We should ensure our documentation documents these annotations: 

https://github.com/micronaut-projects/micronaut-openapi/tree/master/openapi-annotations/src/main/java/io/micronaut/openapi/annotation

**Comment by wetted** [comment]
@sdelamo  

The dependencies were fixed already on #1113 and #1145.
Those annotations are also documented via #1095

**Comment by sdelamo** [comment]
@wetted why the documentation is still wrong?

**Comment by altro3** [comment]
@sdelamo @wetted I think it was bug with build, because now all is ok. Chek https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/2f4669eb-9465-4c6a-89ce-94b065f6a1c8)

**Comment by altro3** [comment]
@sdelamo @wetted Something is wrong. Whee all other versions? Isee this now:

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/22a70bcc-1627-44b3-b4fd-cfdf86b5a90d)

Maybe it because we removed version?

**Comment by altro3** [comment]
now all correct
