### ISSUE TITLE
Specific @Header parameter ignored when generating OAS3 *.yml file

### ISSUE THREAD

**Issue by CZbosch** [micronaut-projects/micronaut-openapi#1159]
### Expected Behavior

Hello,
I have a case where I use @RequestBean annotation with @Header annotation on AUTHORIZATION header like:
```java
import io.micronaut.core.annotation.Introspected;
import io.micronaut.http.annotation.Header;
import static io.micronaut.http.HttpHeaders.AUTHORIZATION;

@Introspected
public class BaseRequestBean {
    @Header(value = AUTHORIZATION)
    String authorization;

    public String getAuthorization() {
        return authorization;
    }
}
```

**Expected behaviour**:
```yml
- name: Authorization
   in: header
   required: true
   schema:
     type: string
```

In the generated *.yml file I cannot see this header generated within any api call
Thanks for any hints.

### Actual Behaviour

Authorization is not included in the generated *.yml file.

### Environment Information

- Operating system: macOS Ventura 13.5
- JDK version: openjdk 17.0.5 LTS

### Version

3.8.8

**Comment by altro3** [comment]
Hi! This is not a bug. This is feature. You can check it with editor.swagger.io:

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/d3bbfa6b-de72-418d-9fff-aec09feeb732)

**Comment by CZbosch** [comment]
Thank you, closing the issue.
