### ISSUE TITLE
Server generator doesn't add JsonSubTypes annotation on inheritance causing incorrect JSON to be generated

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-openapi#1163]
### Expected Behavior

When using a discriminator to serialize and deserialize objects with inheritance, I expect the server generator to add the `@JsonSubTypes` annotation to the correct generated model class, so the defined enum value is used in the discriminating field. For instance:

```
{"type":"DETAILED","name":"Never-ending Story","availability":"available","author":"Michael Ende","ISBN":"SOME_ISBN"}
```

"type" is the discriminating field in this example.

### Actual Behaviour

The server generator does not add the `@JsonSubTypes` annotation, and therefore the sub-class name is used as discriminating value, making the generated JSON incorrect, since the defined enum value should be used:

```
{"type":"DetailedBookInfo","name":"Never-ending Story","availability":"available","author":"Michael Ende","ISBN":"SOME_ISBN"}
```

"type" is the discriminating field in this example.

This behaviour makes the deserialization incompatible with clients, that send the correct JSON, since they will send the value `DETAILED` in `type` and the Micronaut service will expect `DetailedBookInfo`.

### Steps To Reproduce

1. Clone https://github.com/runenielsen/missingjsonsubtypes
2. Run the `testSerdeForDetailedBookInfo` test in the `MissingjsonsubtypesTest` test class
3. I have made a hacky fix in lines 64 - 82 in build.gradle.kts, that inserts the needed `@JsonSubTypes` annotation in the generated `BookInfo.java` file, so you can see, how I think it should look. Comment the fix out and run the test again to see, that it now fails.

The `@JsonSubTypes` annotation is added correctly by other generators, for instance: https://openapi-generator.tech/docs/generators/java/. So this is not a bug in the OpenAPI Generator core.

The annotation is actually also already imported in the generated class, it is just not used:

```
import com.fasterxml.jackson.annotation.JsonSubTypes;
```

### Environment Information

OS: MacOS
JDK: Java 17

But it should occur in any environment.

### Example Application

https://github.com/runenielsen/missingjsonsubtypes

### Version

4.0.3

**Comment by altro3** [comment]
@runenielsen yes, it was a bug. Fixed here: https://github.com/micronaut-projects/micronaut-openapi/pull/1167

**Comment by runenielsen** [comment]
@altro3 : Awesome, thanks a lot.
