### ISSUE TITLE
Generators shouldn't add required discriminator property as a constructor parameter in generated models with inheritance

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-openapi#1168]
### Expected Behavior

Required discriminator properties in models with inheritance should not be part of the constructor parameters, since they are not required to be set (they are generated automatically based on the class on serialization).

Currently it is actually a problem, if they are set, since the property will then be added twice to the generated JSON on serialization due to a bug in Micronaut Serialization (reported here: https://github.com/micronaut-projects/micronaut-serialization/issues/550).

### Actual Behaviour

Required discriminator properties are added as constructor parameters for generated models with inheritance.

### Steps To Reproduce

1. Clone the project https://github.com/runenielsen/discriminatorgeneration
2. Build and inspect the generated classes to see, that the discriminator property `type` is added as a constructor parameter.
3. Run the test SerdeWithDiscriminatorTest and see the test case `testSerializationForDetailedBookInfoWithDiscriminatorSet` fail due to the discriminator property being added twice in the generated JSON, when it is set in the model. And see that the test case `testSerializationForDetailedBookInfoWithoutDiscriminatorSet` works correctly, when it is not set in the model. And lastly notice that the property is not set in the model on deserialization in the test case `testDeserializationForDetailedBookInfo`.

I'm aware that this issue is sort of in between a bug and a feature request, since it is mostly an annoyance to have a property in the constructor, that doesn't need to be set, and the main bug is actually in Micronaut Serialization. But I figured, I'd report it as a bug, since the fields in the Bug Report issue type fit better 🙂 

### Environment Information

OS: MacOS
JDK: 17

### Example Application

https://github.com/runenielsen/discriminatorgeneration

### Version

4.0.3

**Comment by altro3** [comment]
@runenielsen  Fixed it here too (two fixes in one PR): https://github.com/micronaut-projects/micronaut-openapi/pull/1167

**Comment by runenielsen** [comment]
@altro3 : Thanks 💪
