### ISSUE TITLE
console warning: "No content to map due to end-of-input" when @Body annotation supplied

### ISSUE THREAD

**Issue by j1m-renwick** [micronaut-projects/micronaut-openapi#1169]
### Expected Behavior

Swagger should generate without console warnings when processing an endpoint with a @Body annotation in the signature

### Actual Behaviour

**Warning is appearing in the logs**

```
WARNING: Can't convert  to object: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]

   eHttpResponse<?> breaks(@Body Map body) 
```

<img width="589" alt="image" src="https://github.com/micronaut-projects/micronaut-openapi/assets/52238993/8e45fe6d-bbbf-4aca-b817-0ced6e926d47">

**`requestBody` in the schema is being generated incorrectly as a string**
```
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: true
              default: ""
```

### Steps To Reproduce

- open and run `./gradlew clean assemble` on [openapi-body-bug.zip](https://github.com/micronaut-projects/micronaut-openapi/files/12363049/openapi-body-bug.zip)
- see the console warning occur for the `/breaks` endpoint and not the `/works` endpoint
- view the swagger.yml in the generated build file

### Environment Information

Operating System:  MacOS Ventura, Version 13.4
JDK Version:  Coretto 17

### Version

5.0.1

**Comment by j1m-renwick** [comment]
great, thank you!

**Comment by altro3** [comment]
@j1m-renwick This was not a bug, just a micronaut 4 feature :-). Fixed here: https://github.com/micronaut-projects/micronaut-openapi/pull/1170
