### ISSUE TITLE
Views aren't being generated

### ISSUE THREAD

**Issue by rabidgremlin** [micronaut-projects/micronaut-openapi#118]
I'm attempting to include the open API views into my project but having no luck.

As a last resort I have created a test app and am having the same issues. Steps to reproduce:

```
mn create-app my-openapi-app --features swagger-java
```

Add jvm parameters as documented to build.gradle
```
plugins {
    id "net.ltgt.apt-eclipse" version "0.21"
    id "com.github.johnrengelman.shadow" version "5.0.0"
    id "application"
}



version "0.1"
group "my.openapi.app"

repositories {
    mavenCentral()
    maven { url "https://jcenter.bintray.com" }
}

configurations {
    // for dependencies that are needed for development only
    developmentOnly 
}

dependencies {
    annotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
    annotationProcessor "io.micronaut:micronaut-inject-java"
    annotationProcessor "io.micronaut:micronaut-validation"
    annotationProcessor "io.micronaut.configuration:micronaut-openapi"
    implementation platform("io.micronaut:micronaut-bom:$micronautVersion")
    implementation "io.micronaut:micronaut-inject"
    implementation "io.micronaut:micronaut-validation"
    implementation "io.micronaut:micronaut-runtime"
    implementation "io.swagger.core.v3:swagger-annotations"
    implementation "io.micronaut:micronaut-http-client"
    implementation "io.micronaut:micronaut-http-server-netty"
    runtimeOnly "ch.qos.logback:logback-classic:1.2.3"
    testAnnotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
    testAnnotationProcessor "io.micronaut:micronaut-inject-java"
    testImplementation platform("io.micronaut:micronaut-bom:$micronautVersion")
    testImplementation "org.junit.jupiter:junit-jupiter-api"
    testImplementation "io.micronaut.test:micronaut-test-junit5"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
}

test.classpath += configurations.developmentOnly

mainClassName = "my.openapi.app.Application"

// use JUnit 5 platform
test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile){
    options.encoding = "UTF-8"
    options.compilerArgs.add('-parameters')
    options.fork = true
    options.forkOptions.jvmArgs << '-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop'
}


shadowJar {
    mergeServiceFiles()
}

run.classpath += configurations.developmentOnly
run.jvmArgs('-noverify', '-XX:TieredStopAtLevel=1', '-Dcom.sun.management.jmxremote')
```

Build the app
```
./gradlew clean build
```

Can see swagger yml file in `META-INF/swagger` but no UI folders under `META-INF`

Have also come across this stackoverflow post from 8 days ago with OP have same issue: https://stackoverflow.com/questions/59261044/micronaut-openapi-swagger-is-not-generating-views

**Comment by croudet** [comment]
What is the version of `micronaut-openapi`?

**Comment by rabidgremlin** [comment]
It would appear to be 1.2.3 ?

```
gradlew server:dependencyInsight --configuration annotationProcessor --dependency io.micronaut.configuration:micronaut-openapi

> Task :server:dependencyInsight
io.micronaut.configuration:micronaut-openapi:1.2.3 (by constraint)
   variant "runtime" [
      org.gradle.status   = release (not requested)
      org.gradle.usage    = java-runtime (not requested)
      org.gradle.category = library (not requested)
   ]

io.micronaut.configuration:micronaut-openapi:1.2.3
\--- io.micronaut:micronaut-bom:1.2.8
     \--- annotationProcessor

io.micronaut.configuration:micronaut-openapi -> 1.2.3
\--- annotationProcessor

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

I'm using v1.2.8 of Micronaut.

**Comment by rabidgremlin** [comment]
Also I can see the system property being passed to the JVM. From my gradle logs...

```
Starting process 'Gradle Worker Daemon 1'. Working directory: C:\Users\xxxxx\.gradle\workers Command: C:\Program Files\Amazon Corretto\jdk1.8.0_222\bin\java.exe -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop -Xmx512m -Dfile.encoding=windows-1252 -Duser.country=NZ -Duser.language=en -Duser.variant -cp C:\Users\xxxxx\.gradle\caches\5.3\workerMain\gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon 1'
Successfully started process 'Gradle Worker Daemon 1'
```

**Comment by croudet** [comment]
Try to use v1.3.3

**Comment by rabidgremlin** [comment]
That did it...

I changed the my dependency to be
```
annotationProcessor "io.micronaut.configuration:micronaut-openapi:1.3.3"
```

Should this be updated in the docs ?

**Comment by croudet** [comment]
The documentation mention version `1.3.3`: https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html

Maybe the bom is not up to date.

**Comment by puneetbehl** [comment]
Thanks, @croudet I created a PR (https://github.com/micronaut-projects/micronaut-core/pull/2549) to update BOM in micronaut-core to use 1.3.3.

A sidenote I faced a `java.lang.NullPointerException` as reported in https://github.com/micronaut-projects/micronaut-core/issues/2552 while debugging this issue. I think it worked for @rabidgremlin because I think it will only happen when you don't have any `GET` path in the application.

**Comment by martinanderssondotcom** [comment]
This issue needs to be re-opened as version `1.3.4` is now suffering the same issue; no views generated.

**Comment by graemerocher** [comment]
@croudet did something change regarding view generation in 1.3.4?

**Comment by croudet** [comment]
I am using it (java), it works fine.  The only change I can't think of is when you specify a different target file.

**Comment by thecodesmith** [comment]
I had this same issue (views not being generated) after following the setup here: https://micronaut-projects.github.io/micronaut-openapi/1.4.0/guide/index.html. I was able to resolve it by adding this dependency:
```
implementation 'io.micronaut:micronaut-views'
```
This was for a Groovy Micronaut app. I didn't see any reference to the above dependency in the docs, I just happened to notice it in a random GitHub repo. Should it be added to the docs?

**Comment by thecodesmith** [comment]
Actually, I just figured out the issue on my side (at least part of it). I had the Gradle build cache enabled, but the cache for the `compileGroovy` task doesn't know about the `swagger` output directory, so it doesn't add it to the cached output. I fixed it in my `build.gradle` by adding the `swagger` output dir to the main source set:
```
sourceSets {
    main {
        groovy {
            output.dir "$buildDir/classes/groovy/main/META-INF/swagger", builtBy: 'compileGroovy'
        }
    }
}
```
With this setup, it works without the `micronaut-views` dependency.

**Comment by hberrayana** [comment]
I'm having now the same issue with Micronaut 2.0.0.M3 with an application generated by https://launch.micronaut.io/

**Comment by graemerocher** [comment]
@hberrayana please report a separate issue with steps to reproduce. Thanks

**Comment by hberrayana** [comment]
@graemerocher I got it while generating with other dependencies from the starter but was unable to reproduce. I'll report it in a separate issue when I get a clear scenario.

**Comment by graemerocher** [comment]
Thanks!
