### ISSUE TITLE
Missing and Incorrect global security configuration

### ISSUE THREAD

**Issue by brianwyka** [micronaut-projects/micronaut-openapi#12]
We need some annotation or configuration be able to apply global operation parameter, such as a authentication / authorization header to all API requests.  These headers are not inherently included in controllers since they are processed by filters.

**Comment by sdelamo** [comment]
For security we are defining the securiyt scheme in `Application.java` 

 */
```
@SecurityScheme(name = "BearerAuth",
        type = SecuritySchemeType.HTTP,
        scheme = "bearer",
        bearerFormat = "jwt")
@OpenAPIDefinition(
        info = @Info(
                title = "My service",
                version = "1.0",
                description = "My Service"
        )
)
public class Application {
```

and then in controllers which require authentication: 

We do: 

```
@SecurityRequirement(name = "BearerAuth")
    @Secured(SecurityRule.IS_AUTHENTICATED)
    @Operation(summary = "Logged-Info User info", description = "Logged-Info User info",
            responses = {
                    @ApiResponse(responseCode = "204", description = "if every requested field is blank or null"),
                    @ApiResponse(responseCode = "200", description = "user info",
                            content = @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = User.class)
                            )),
                    @ApiResponse(responseCode = "401", description = "Returned if request is submitted by an anonymous user or if the access token is invalid e.g. expired"),

            })
    @Get("/user{?fields}")
    Single<HttpResponse<User>> userInfo(Principal principal, @QueryValue @Nullable List<String> fields) {
```

Is this what you are looking for?

**Comment by brianwyka** [comment]
Thanks @sdelamo.  Is there any way to configure the `SecurityRequirement` by path from yaml, or must everything be done though the annotations for AOT?

**Comment by brianwyka** [comment]
Our JWT token is passed in a header named `JWT` without a `bearer` prefix.  Any direction on how to configure that?

**Comment by brianwyka** [comment]
Looks like we can use the `apiKey` type instead.  In getting that to work, I found an issue.  After adding the `@SecurityScheme` at the application level, only controllers annotated with `@SecurityRequirement` are generated to openapi.  Is this a bug?

**Comment by puneetbehl** [comment]
@brianwyka Yes, I believe it's a bug if other controller paths are not included in OpenAPI definition after adding `@SecurityScheme`

**Comment by brianwyka** [comment]
@puneetbehl is there a way to globally define a `@SecurityScheme` to be used by path, instead of having to include the `@SecurityRequirement` on every controller?

**Comment by puneetbehl** [comment]
@brianwyka I think you can define `@SecurityRequirement` on the Application class which will generate `security` section on the root level as:

```yaml
openapi: 3.0.1
info:
  title: openapi-demo
  version: "0.0"
security:
- name:
  - myOauth2Security
components:
  securitySchemes:
    myOauth2Security:
      type: apiKey
      name: myOauth2Security
      in: header
```
And, you can override on the operation(controller) level to use a different authentication type, different OAuth/OpenID scopes, or no authentication at all.

**Comment by ctoestreich** [comment]
@puneetbehl @sdelamo @brianwyka After banging my head against the wall, stabbing needles in my eyes and setting my hair on fire... I FINALLY was able to determine why our UI isn't working with the auth.  There is indeed a bug with how micronaut generates the security spec for the yaml.

## Individual Operation Tokens
The INCORRECTLY generated code looks as following

<img width="518" alt="Screen Shot 2019-05-08 at 10 30 44 AM" src="https://user-images.githubusercontent.com/691357/57387741-843d3d00-717c-11e9-8e62-ddd06b0d260e.png">

According to the spec it should be

<img width="557" alt="Screen Shot 2019-05-08 at 10 30 56 AM" src="https://user-images.githubusercontent.com/691357/57387784-98813a00-717c-11e9-8d8d-f532b7538b78.png">

## Global Tokens

When adding the global security to the Application class like 

```java
@SecurityRequirement(name = "X-Token-JWT")
public class Application {
    public static void main(final String[] args) {
        Micronaut.run(Application.class, args);
    }
}
```

It generates MOST of the correct spec which is

<img width="341" alt="Screen Shot 2019-05-08 at 10 30 18 AM" src="https://user-images.githubusercontent.com/691357/57387885-c5355180-717c-11e9-9969-7f139e01e6b6.png">

However it is missing the global security configuration as following

<img width="433" alt="Screen Shot 2019-05-08 at 10 30 13 AM" src="https://user-images.githubusercontent.com/691357/57387912-d2ead700-717c-11e9-84fc-b3b4ac848544.png">

## Conclusion

When I "fix" the generated yaml and add these changes then our APIs and authentication works and is applied to the swagger UI params.

## UI Screens After Manual Fix

<img width="330" alt="Screen Shot 2019-05-08 at 10 38 22 AM" src="https://user-images.githubusercontent.com/691357/57388319-8fdd3380-717d-11e9-8062-858cf4f6e748.png">

<img width="238" alt="Screen Shot 2019-05-08 at 10 38 35 AM" src="https://user-images.githubusercontent.com/691357/57388329-94095100-717d-11e9-858d-2f84f781a581.png">

<img width="743" alt="Screen Shot 2019-05-08 at 10 38 39 AM" src="https://user-images.githubusercontent.com/691357/57388345-9b305f00-717d-11e9-802d-318052f3d6be.png">

<img width="256" alt="Screen Shot 2019-05-08 at 10 38 50 AM" src="https://user-images.githubusercontent.com/691357/57388365-a1264000-717d-11e9-9a86-a61ced5cd3b9.png">

**Comment by reanimated** [comment]
This change does not appear to be in any build? (1.1.2.BUILD-SNAPSHOT or 1.2.0.BUILD-SNAPSHOT)

**Comment by andydoe19** [comment]
Hi @brianwyka to set the jwt header globally you just need to annotate the Application.java like this:

```
//basic info for swagger startup
@OpenAPIDefinition(
        info = @Info(
                title = "your app name",
                version = "0.1",
                description = "your endpoints description",
                license = @License(name = "Apache 2.0", url = "https://yourlicenceurl"),
                contact = @Contact(url = "https://yourapidocurl", name = "yourusername", email = "info@yourdomain.com")
        )
)
//swagger config to set globally the jwt authentication header on the api doc page
@SecurityScheme(
        name = "BearerAuth",
        type = SecuritySchemeType.HTTP,
        scheme = "bearer",
        bearerFormat = "jwt"
)
//swagger config to set globally the security property for 'BearerAuth'
@SecurityRequirement(name = "BearerAuth")
public class Application {
...
}
```
In your case with the custom authentication header, you could do it like this: 


```
//basic info for swagger startup
@OpenAPIDefinition(
        info = @Info(
                title = "your app name",
                version = "0.1",
                description = "your endpoints description",
                license = @License(name = "Apache 2.0", url = "https://yourlicenceurl"),
                contact = @Contact(url = "https://yourapidocurl", name = "yourusername", email = "info@yourdomain.com")
        )
)
//swagger config to set globally the jwt authentication header on the api doc page
@SecurityScheme(
        type = "apiKey",
        name = "JWT",
        in = "header"
)
//swagger config to set globally the security property for 'JWT'
@SecurityRequirement(name = "JWT")
public class Application {
...
}
```
