### ISSUE TITLE
OpenAPI Generator generates classes that can't build for models with two (or more) levels of inheritance and a discriminator

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-openapi#1206]
### Expected Behavior

When the OpenAPI Generator generates classes for a OpenAPI definition with a model with two (or more) levels of inheritance and using a discriminator, the generated classes should build, and the discriminator field should not be part of the constructor parameters in any of the generated classes.

### Actual Behaviour

The sub-class (BasicBookInfo in my example below) is generated correctly, but the sub-sub-class (DetailedBookInfo in my example below) has the discriminator field as part of the constructor parameters and calls it's parent's (BasicBookInfo) constructor with incorrect parameters.

This means the generated classes can't build.

I think the problem is related to the fix done in [this issue](https://github.com/micronaut-projects/micronaut-openapi/issues/1168), since in version 4.0.3 of the OpenAPI plugin, the discriminator was part of all constructors, and the generated classes could build even with two levels of inheritance.

I think it is preferable, if the discriminator is not part of the constructor of any generated classes, as it is not required, and there's actually a [bug in Micronaut Serialization](https://github.com/micronaut-projects/micronaut-serialization/issues/550), that causes the discriminator field to be output twice in the JSON when serializing, if it is set in the model.

But if it is not possible to both get this and classes that build, I suppose classes that build are preferable 🙂 

### Steps To Reproduce

1. Clone the project https://github.com/runenielsen/discriminatorconstructorbug
2. Try to build.
3. See that it fails and inspect the constructor in the generated class `DetailedBookInfo`. The parameter `name` is missing in the call to the super class. Also `TypeEnum type` should not be a parameter in `DetailedBookInfo`'s constructor signature.
4. Try and downgrade the OpenAPI plugin to 4.0.3 in `build.gradle.kts` (`id("io.micronaut.openapi") version "4.0.3"`) and see that now it builds.
5. To get the tests in the project to run with 4.0.3, you need to change all occurrences of "DETAILED" to "DetailedBookInfo" in `SerdeWithDiscriminatorTest` due to [this unrelated bug](https://github.com/micronaut-projects/micronaut-openapi/issues/1163), that was fixed in version 4.1.0.

### Environment Information

OS: MacOS
JDK: 17

### Example Application

https://github.com/runenielsen/discriminatorconstructorbug

### Version

4.1.0

**Comment by altro3** [comment]
Ok, I'll fix it on the weekend

**Comment by runenielsen** [comment]
@altro3 : Thanks a lot. I also just created another issue, that is simiar: https://github.com/micronaut-projects/micronaut-openapi/issues/1208 , so it may be easier to fix both at the same time.

This issue (no. 1206) is more important to fix though, since I think that it is functionality used more often.
