### ISSUE TITLE
OpenAPI Client Generator generates classes that can't build for models with required readonly fields and inheritance

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-openapi#1208]
### Expected Behavior

When the OpenAPI Client Generator generates classes for an OpenAPI definition with required readonly fields and inheritance, the generated classes should build.

### Actual Behaviour

The super-class (`BookInfo` in my example below) is generated correctly, but the constructor in the sub-class (`ExtendedBookInfo`) is generated incorrectly and makes the class unable to build. The required readonly parameter `requiredReadOnly` is not part of the constructor signature (which is correct), but it still tries to include it in the call to the super class' constructor.

The problem only exists for generated client models and is related to the fix done in [this issue](https://github.com/micronaut-projects/micronaut-openapi/issues/1160).

### Steps To Reproduce

1. Clone the project `https://github.com/runenielsen/readonlyconstructorbug.git`.
2. Try to build and see it fail.
3. Inspect the constructor in the generated class `ExtendedBookInfo` and see, that it is incorrect.
4. See the file `readonlyconstructorbug.yml` for the OpenAPI definitions.

### Environment Information

OS: MacOS
JDK: Java 17

### Example Application

https://github.com/runenielsen/readonlyconstructorbug.git

### Version

4.1.0

**Comment by altro3** [comment]
@runenielsen Hi! Hm... I test your example app and can't reproduce the problem. with yor yaml file I have 2 classes and ExtendedBookInfo is correct:
```java
...

/**
 * ExtendedBookInfo
 */
@Serdeable
@JsonPropertyOrder(ExtendedBookInfo.JSON_PROPERTY_ISBN)
@Introspected
public class ExtendedBookInfo extends BookInfo {

    public static final String JSON_PROPERTY_ISBN = "isbn";

    @NotNull
    @Pattern(regexp = "[0-9]{13}")
    @Schema(name = "isbn", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ISBN)
    private String isbn;

    public ExtendedBookInfo(String isbn, String name, String requiredReadOnly) {
        super(name, requiredReadOnly);
        this.isbn = isbn;
    }
...
```

**Comment by altro3** [comment]
@runenielsen Could you try to use latest micronaut-openapi version - 5.1.1 and also build from master ?

**Comment by altro3** [comment]
@runenielsen Sorry, I didn't read it carefully. Yes, indeed, the problem is only in the client generator....

**Comment by runenielsen** [comment]
@altro3 : Thanks a lot 🙂

**Comment by runenielsen** [comment]
@altro3 : Do you know when Micronaut OpenAPI will be released again? [Last release was 2 months ago](https://github.com/micronaut-projects/micronaut-openapi/releases), and my project needs your fixes 🙂

**Comment by altro3** [comment]
@runenielsen I just can ask about it.

@graemerocher Could we release micronaut-openapi 5.2.0 or we need to wait micronaut-core 4.2.0 release?
