### ISSUE TITLE
@Valid annotation is not added to lists in generated models and APIs

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-openapi#1235]
### Expected Behavior

`@Valid` annotation should be added to lists in generated models and APIs.

*IMPORTANT:* The annotation can only be added to lists containing introspected model beans. If for instance it is a list of String, this error occurs, if `@Valid` is added:

```
Cannot validate java.lang.String. No bean introspection present. Please add @Introspected to the class and ensure Micronaut annotation processing is enabled
```

### Actual Behaviour

`@Valid` annotation is not added to lists in generated models and APIs.

This means any Jakarta validations in beans in a list are ignored.

The annotation IS added to model objects.

### Steps To Reproduce

1. Clone the repository https://github.com/runenielsen/mn-openapi-list-validation-bug
2. Build the code and see the `BookControllerTest` test fails.
3. Inspect the generated classes `BooksContainer` and `BooksApi` and see that the `@Valid` annotation is missing for the property / parameter `List<Book> books`
4. Go to `build.gradle.kts` and comment the code under the line `TODO: Comment the code below in to fix the generated classes and to fix the tests` in. This adds the `@Valid` annotation to the lists in the models and the API.
5. Build again and see that now the `BookController` test succeeds.

### Environment Information

- macOS
- JDK 17

### Example Application

https://github.com/runenielsen/mn-openapi-list-validation-bug

### Version

4.1.3

**Comment by altro3** [comment]
Fixed here https://github.com/micronaut-projects/micronaut-openapi/pull/1242
