### ISSUE TITLE
Jakarta validation constraint annotations are not added to Strings, Integers, Longs, etc. inside lists in generated models and apis, if constraints are specified in the OpenAPI specification

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-openapi#1239]
### Expected Behavior

Jakarta validation constraint annotations should be added to Strings, Integers, Longs, etc. inside lists in generated models and apis, if constraints are specified in the OpenAPI specification. They should be added inside the diamond operator. For instance:

```
List<@Pattern(regexp = "[a-zA-Z ]+") @Size(max = 10) String> books
```

### Actual Behaviour

Jakarta validation constraint annotations are not added to Strings, Integers, Longs, etc. inside lists in generated models and apis, if constraints are specified in the OpenAPI specification. So instead of the above, they look like this:

```
List<String> books
```

The Jakarta validation constraint annotations are added correctly, when the types are used directly inside a model bean (without being wrapped in a list).

### Steps To Reproduce

1. Clone https://github.com/runenielsen/mn-openapi-primitive-list-validation-bug
2. Build the code and see the BookControllerTest test fails.
3. Inspect the generated classes BooksContainer, CountsContainer and BooksApi and see that the constraint annotations are missing inside the diamond operator in the lists.
4. Go to build.gradle.kts and comment the code under the line `TODO: Comment the code below in to fix the generated classes and to fix the tests` in. This updates the generated classes to how I think, they should look.
5. For some reason the annotations inside the diamond operator do not work in the API, when they are only in the API interface (they do work in the models!), so one of the tests will still be failing. To fix this test, comment in the method with the `TODO: Add this in instead of the above to see the validation work` comment in and remove the method just above it in the API implementation `BookController`.
6. Despite point 5, I think the annotations should be added in the API interface as well. Point 5 is probably caused by a separate bug somewhere else, but that shouldn't keep the generated interface to be fixed to be correct.

### Environment Information

- macOS
- JDK Temorin 17

### Example Application

https://github.com/runenielsen/mn-openapi-primitive-list-validation-bug

### Version

4.1.3

**Comment by altro3** [comment]
Done

**Comment by runenielsen** [comment]
Awesome. Thank you, @altro3!
