### ISSUE TITLE
Endpoints with OPTION method not added to generated OpenAPI spec

### ISSUE THREAD

**Issue by jayeshkapadnis** [micronaut-projects/micronaut-openapi#1246]
### Issue description

I am trying to upgrade my application from Micronaut version 3.8.7 to 4.1.3. 

We use `micronaut-openapi` to generate specs yaml. We have few apis with Http Method `OPTION` to ensure we can add an extension details to it.

With changes as part of PR #1067, when `SchemaUtils.setOperationOnPathItem` is invoked it doesn't consider any HttpMethods from `HEAD`, `OPTIONS` & `TRACE`.  Earlier it was part of `AbstractOpenApiEndpointVisitor.setOperationOnPathItem`. 

 Is there a specific reason to remove these ? Is there any workaround to include endpoints with these methods in generated OpenAPI spec ?

**Comment by altro3** [comment]
No, it's just a bug. Fixed here: https://github.com/micronaut-projects/micronaut-openapi/pull/1248

**Comment by altro3** [comment]
@jayeshkapadnis hi! Hm... I don't know when next released planned, but I thought that we can wait micronaut core 4.2.0 release and also fix KSP support. Also I want to release these new features - https://github.com/micronaut-projects/micronaut-openapi/pull/1254 and https://github.com/micronaut-projects/micronaut-openapi/pull/1233
