### ISSUE TITLE
Runtime swagger spec file path generation no longer working in micronaut-openapi 5.1.0

### ISSUE THREAD

**Issue by timholt81** [micronaut-projects/micronaut-openapi#1249]
### Expected Behavior

Using micronaut-openapi 4.9.2 and following the approach [here](https://micronaut-projects.github.io/micronaut-openapi/latest/guide/#serverFilter) to set _contextPath_ via a cookie, the swagger spec file path can be determined at runtime as opposed to compile time.

### Actual Behaviour

After upgrading to micronaut-openapi 5.1.0 and following the same approach, it seems the runtime swagger spec file path generation using the _contextPath_ value is ignored in favour of a new _urls_ parameter which does not use _contextPath_. The relevant section of code generated in swagger-ui index.html:

```
ui = SwaggerUIBundle({
    url: contextPath + '/swagger/my-app-1.yml',
    dom_id: '#swagger-ui',
    presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
    ],
    plugins: [
        SwaggerUIBundle.plugins.DownloadUrl,
        f
    ],
    urls:[{"url":"/swagger/my-app-1.yml", "name":"1"}], // Newly added in 5.1.0, does not use contextPath
    deepLinking: true,
    displayRequestDuration: true,
    layout: "StandaloneLayout",
    tagsSorter: "alpha",
    validatorUrl: null
});
```

### Version

5.1.0

**Comment by altro3** [comment]
Could you create a sample project to reproduce problem?

**Comment by altro3** [comment]
In general, an example is not required. I figured out what the problem was and already fixed it

**Comment by timholt81** [comment]
Thanks for the quick turnaround! Was just about to put together a sample project :-)
