### ISSUE TITLE
Micronaut's OpenAPI view generation does not insert line breaks

### ISSUE THREAD

**Issue by martinanderssondotcom** [micronaut-projects/micronaut-openapi#128]
According to the [`@Info` JavaDocs of Swagger](http://docs.swagger.io/swagger-core/v2.1.1/apidocs/io/swagger/v3/oas/annotations/info/Info.html#description--), CommonMark is supported in the description:

> A short description of the application. CommonMark syntax can be used for rich text representation.

..which is a backslash character according to [this page](https://commonmark.org/help/tutorial/03-paragraphs.html):

> For a line break, add either a backslash \ or two blank spaces at the end of the line.

I have tried both of these, a backslash and two blank spaces, but Micronaut won't insert a line break. The workaround is to instead use a `<br>` (the text that is, inside the String where the line break should be rendered).

I am using version `1.3.3` as this is the only version that works to generate views (#118).

**Comment by croudet** [comment]
It is up to the renderer (rapidoc, swagger-ui) to transform the common mark.

**Comment by croudet** [comment]
I have tested that with swagger-ui and rapidoc on the `description` field of `info` and it works fine.
```java
@OpenAPIDefinition(
	    info = @Info(
	            title = "Title",
	            version = "1.0",
	            description = "a line break should appear\\\n"
	                    + "here"
```
