### ISSUE TITLE
POST service: parameter duplicated in Header and body 

### ISSUE THREAD

**Issue by outersky** [micronaut-projects/micronaut-openapi#130]
## Case 1:

```kotlin
    @Post("/create2")
    fun create2(@Header("X-Session-Id") sessionId: String, phone: String, name: String): String {
        return """{"sessionId":"$sessionId", "phone":"$phone", "name":"$name"}"""
    }
```

create2: sessionId will appear twice in both header and body:

```yml
/create2:
    post:
      operationId: create2
      parameters:
      - name: X-Session-Id
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId:
                  type: string
                  nullable: false
                phone:
                  type: string
                  nullable: false
                name:
                  type: string
                  nullable: false
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                type: string
```

## Case 2

```kotlin
    @Get("/find1")
    fun find2(name: String): String {
        return """{"name":"$name"}"""
    }
```
find1: name is ignored in swagger file, but it's a query parameter by default in micronaut.

```yml
/find1:
    get:
      operationId: find2
      parameters: []
      responses:
        default:
          content:
            application/json:
              schema:
                type: string
```

I created a [demo project here](https://github.com/outersky/micronaut-openapi-bug-yml.git)

**Comment by croudet** [comment]
I am not sure I understand the problem with case 2. `name` does not appear in your uri.

**Comment by outersky** [comment]
@croudet  For case 2, "name" should be included in parameters:[] 

    curl http://localhost:8080/find1?name=outersky

**Comment by croudet** [comment]
For case #2, I think you still need to declare it in the uri, for instance for a `PathVariable`:
`@Get(/find1/{name})`
or `QueryValue`:
`@Get(/find1{?name}`

**Comment by outersky** [comment]
I know that will work , just feel like a little bit noisy and result in a lot of work . 
As in case 1, both `phone` and `name` need not be annotated, and it will generate the right openapi file.
so I think it might be better if we can recognize the default behaviour in micronaut .

**Comment by croudet** [comment]
The two merged pull requests should fix both issues.

**Comment by outersky** [comment]
thanks , but it's still not ok with case #2
