### ISSUE TITLE
Micronaut OpenAPI Generator (still) generates classes that can't build for models with two (or more) levels of inheritance and a discriminator

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-openapi#1315]
### Expected Behavior

The error originally reported in this [closed issue](https://github.com/micronaut-projects/micronaut-openapi/issues/1206) is unfortunately not fixed, even if a change was made in that issue, and it still does not work in version 4.2.0. See [the original issue](https://github.com/micronaut-projects/micronaut-openapi/issues/1206) for description.

### Actual Behaviour

See [the original issue](https://github.com/micronaut-projects/micronaut-openapi/issues/1206) for description.

In addition the `DetailedBookInfo` classes still has `TypeEnum type` as a constructor parameter. This was supposed to have been removed in [this issue](https://github.com/micronaut-projects/micronaut-openapi/issues/1168). Note the `TypeEnum type` constructor parameter has been removed in the two super classes (as expected).

### Steps To Reproduce

See [the original issue](https://github.com/micronaut-projects/micronaut-openapi/issues/1206).

### Environment Information

- macOS
- JDK 17

### Example Application

https://github.com/runenielsen/discriminatorconstructorbug (I upgraded it to use Micronaut 4.2.0)

### Version

4.2.0

**Comment by altro3** [comment]
I think, gradle plugin use old version of micronaut-openapi https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/867

**Comment by altro3** [comment]
yeah, it's true
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/3d14b1d2-7a29-407e-947a-60073d70e1c5)

**Comment by altro3** [comment]
@runenielsen frrom documentation:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/88e8bebf-469f-46df-ada9-baf20b481a90)

You can set version `6.1.0` of micronaut-openapi yourself

**Comment by altro3** [comment]
Wait this PR: https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/807 and new gradle plugin release

**Comment by runenielsen** [comment]
Thanks, @altro3 🙂

**Comment by altro3** [comment]
@runenielsen try to use https://github.com/micronaut-projects/micronaut-gradle-plugin/releases/tag/v4.2.1

**Comment by runenielsen** [comment]
@altro3 : Thanks.

I haven't checked out the Serde model generator, right now we are using the Jackson generator due to the problems in the other one.

In the Jackson generator, I am with the newest Gradle plugin v4.2.1 now getting private constructors in my generated model classes without required parameters... so they can't be instantiated 🙁
