### ISSUE TITLE
MicronautCodeGeneratorEntryPoint clientOptions are not propagated to DefaultGenerator via JavaMicronautClientCodegen

### ISSUE THREAD

**Issue by oliverkuntze** [micronaut-projects/micronaut-openapi#1325]
### Expected Behavior

When passing for example additionalClientTypeAnnotations in ClientOptions to MicronautCodeGeneratorEntryPoint, the annotations are generated in the corresponding API interface.

### Actual Behaviour

When passing for example additionalClientTypeAnnotations in ClientOptions to MicronautCodeGeneratorEntryPoint, the annotations are NOT generated in the corresponding API interface.
This behaviour is true for various client options as well as other general and server options.

This is because the OpenAPI DefaultGenerator only tries to get these information from additionalProperties.

For example MicronautCodeGeneratorEntryPoint sets additionalClientTypeAnnotations in JavaMicronautClientCodegen's additionalClientTypeAnnotations NOT in additionalProperties.
The processOpts() method(s) never set additionalClientTypeAnnotations, clientId etc. to additionalProperties.
So these client configs are never passed to OpenAPI DefaultGenerator and as a result they never get generated in the API interface.

I've extended the OpenApiClientGeneratorSpec in micronaut-openapi-plugin and debugged all the way to the DefaultGenerator class.
The properties handling in MicronautCodeGeneratorEntryPoint and JavaMicronautClientCodegen doesn't seem consistent with what DefaultGenerator expects. A couple of properties one can configure for example in micronaut-openapi-plugin's OpenApiSpec, OpenApiClientSpec, OpenApiServerSpec don't get propagated to DefaultGenerator and therefore are not generated.
The tests only tests for TaskOutcome.SUCCESS which isn't sufficient. 

### Steps To Reproduce

Configure a micronaut project with
micronaut {
                openapi {
                    client(file("petstore.json")) {
                        additionalClientTypeAnnotations = [ '@Header(name="Api-Key", value="somekey")' ]
                        clientId = "someid"
                    }
                }
            }
and generate the code.

### Environment Information

All OS, all JDKs

### Version

4.2.0

**Comment by altro3** [comment]
Good catch! Fixed it here: https://github.com/micronaut-projects/micronaut-openapi/pull/1328
