### ISSUE TITLE
param descriptions of data model / responses are not pulled from javadocs (kotlin)

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-openapi#134]
consider:

```kotlin
/**
 * @param more This property identifies if there is more content available based on the search criteria. The absence of this property means the value is false.
 * @param next This property identifies the server provided value of the next record or set of records in the paginated data set. This property ​MAY​ be populated if the ​more​ property is set to ​true.​
 * @param objects This property contains one or more STIX Objects. Objects in this list ​MUST​ be a STIX Object (e.g., SDO, SCO, SRO, Language Content object, or a Marking Definition object).
 */
@Schema(name = "envelop", description = "The envelope is a simple wrapper for STIX 2 content. When returning STIX 2 content in a TAXII response the HTTP root object payload \u200BMUST\u200B be an \u200Benvelope\u200B. This specification does not define any other form of content wrapper for objects outside of STIX content.")
data class Envelop(
        @get:Schema(description = "This property identifies if there is more content available based on the search criteria. The absence of this property means the value is false.")
        val more: Boolean = false,
        
        val next: String? = null,
        val objects: List<Map<String, Any>?> = listOf() // Is this supposed to be a null or empty list?
)
```

The `@get:Schema(description = "This property identifies if there is more content available based on the search criteria. The absence of this property means the value is false.")` had to be added for the description to be provided.  It was not "auto" pulled from the class' javadoc

**Comment by StephenOTT** [comment]
Using 1.3.4

**Comment by alvarosanchez** [comment]
Is this the same as #265?

**Comment by scprek** [comment]
@alvarosanchez I think it's similar but I could not get the `@Operation` annotation working with `parameters`

@StephenOTT the only way I was able to get all 3 (endpoint description, summary and parameter description) to work and be distinctive is with below. Additionally, documented my failed attempts.

### TL;DL
 Use a combo of javadoc for params only and `@Operation` for everything else. Additionally you can have description alone, but if you want a summary, description must be defined and be a non zero length string.

## Works

### Combo of javadoc for params only and `@Operation` for everything else

```kotlin
/**
 * @param id UUID of test
 */
@Operation(
    summary = "Delete a thing",
    description = "description test"
)
```

### Same as above but no summary

```kotlin
/**
 * @param id UUID of test
 */
@Operation(
    description = "description test"
)
```

Oddly enough only having summary does NOT WORK!?

## Failed attempts

### Adds same text to summary and description

> Using only javadoc

```kotlin
/**
 * Description and summary here
 * @param id UUID of test
 */
```

### Fails with cannot render

<img width="351" alt="Screen Shot 2021-02-10 at 2 09 14 PM" src="https://user-images.githubusercontent.com/2783947/107567854-dc07a400-6bab-11eb-8b3d-7852dbd9f10a.png">

> When trying to use explicit `Parameter` array. Also concerned about this clashing with the auto generated swagger doc for the param

```kotlin
@Operation(
    summary = "Delete a thing",
    description = "description test",
    parameters = [Parameter(name = "id", description = "id description")]
)
```

### Shows param description but lost summary

> When there is a missing or empty description

```kotlin
/**
 * @param id UUID of test
 */
@Operation(
    summary = "Delete a thing",
    description = ""
)
```

```kotlin
/**
 * @param id UUID of test
 */
@Operation(
    summary = "Delete a thing"
)
```
