### ISSUE TITLE
OpenAPI specification  occasionally created with default file name

### ISSUE THREAD

**Issue by davidsonnabend** [micronaut-projects/micronaut-openapi#1345]
### Expected Behavior

OpenAPI specification filename will be created according to the following pattern `${info.title}-${info.version}.yml` when info block is set (as described in the docs).

### Actual Behaviour

Occasionally the OpenAPI specification will be created using the default filename `swagger.yml` even though the info block is set correctly.

Seems that the `@OpenAPIDefinition` will not be handled by `kspCompile` if no relevant changes where made and gradle just compiles the other files.

### Steps To Reproduce

1. Clone example application
2. Run test using `./gradlew test`
3. Test will pass because OpenAPI spec was created with filename `micronaut-swaggerui-demo-1.0.0.yml`
4. Open `HelloWorldController.kt` and add an empty new line within the class.
5. Run test using `./gradlew test` 
6. Test will fail because OpenAPI spec was created with filename `swagger.yml`
5. Run test using `./gradlew clean test`
6. Test will pass again

### Environment Information

- Operating System: Ubuntu 23.10
- JDK Version: 21.0.1-zulu

### Example Application

https://github.com/davidsonnabend/micronaut-swaggerui-versioned-api-bug

### Version

4.2.1 (with micronaut-openapi:6.3.0)

**Comment by altro3** [comment]
I can't reproduce your problem  with your sample. But I found mistake in your gradle script: you set micronaut-openapi dependency twice. Most likely, you were connecting to an old version of micronaut-openapi. Try my script

This is my build.gradle file with it all works fine:
```kotlin
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.9.21"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.9.21"
    id("com.google.devtools.ksp") version "1.9.21-1.0.15"
    id("io.micronaut.application") version "4.2.1"
    id("io.micronaut.aot") version "4.2.1"
}

version = "0.1"
group = "com.example"

repositories {
    mavenCentral()
}

dependencies {
    ksp("io.micronaut:micronaut-http-validation")
    ksp("io.micronaut.serde:micronaut-serde-processor")
    ksp("io.micronaut.openapi:micronaut-openapi:6.3.0!!")

    compileOnly("io.micronaut:micronaut-http-client")
    compileOnly("io.micronaut.openapi:micronaut-openapi-annotations:6.3.0!!")

    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    runtimeOnly("ch.qos.logback:logback-classic")
    runtimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")
    runtimeOnly("org.yaml:snakeyaml")

    testImplementation("io.micronaut:micronaut-http-client")
}


application {
    mainClass.set("com.example.ApplicationKt")
}
java {
    sourceCompatibility = JavaVersion.toVersion("21")
}
kotlin {
    jvmToolchain(21)
}


graalvmNative.toolchainDetection.set(false)
micronaut {
    runtime("netty")
    testRuntime("kotest5")
    processing {
        incremental(true)
        annotations("com.example.*")
    }
    aot {
    // Please review carefully the optimizations enabled below
    // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        optimizeServiceLoading.set(false)
        convertYamlToJava.set(false)
        precomputeOperations.set(true)
        cacheEnvironment.set(true)
        optimizeClassLoading.set(true)
        deduceEnvironment.set(true)
        optimizeNetty.set(true)
    }
}
```

**Comment by davidsonnabend** [comment]
Thank you for the hint regarding the duplicated dependency. 

Unfortunately, removing the duplicate dependency hasn't changed anything.
Also when I use your complete gradle build file I can reproduce the described behavior.

To prevent any issues with cached dependencies I also deleted the whole `.gradle` folder but can reproduce the described issue.

Any ideas why you can't reproduce the error?
What can/should I change/try?

**Comment by altro3** [comment]
@davidsonnabend Hm...Yes, I was able to reproduce this bug. Well, we need to figure out why the file name changes to the default one. I'll try to get it done this week

**Comment by altro3** [comment]
@davidsonnabend I don't know is it bug or KSP feature. Looks like an incremental annotation processing, when with second build KSP re-process only changed classes (for speed, of course). The same problem if you have multiple controllers.

Now I can only advise you one thing: disable incremental processing of ksp: add to `gradle.properties` this:
```properties
ksp.incremental=false
```

**Comment by altro3** [comment]
@davidsonnabend second solution - run `clean test` instead of `test`

**Comment by davidsonnabend** [comment]
Thank you for the feedback. I already used `clean test` to prevent the error.

Setting `ksp.incremental` to `false` also did the job for me. I will check which approach fits best for us in the project.

Meanwhile I will have a look at the issue to see if it is a bug or simply a ksp feature.
Please let me know if you need help regarding this issue.

**Comment by altro3** [comment]
I created issue in core module, becuse it's not  micronaut-openapi problem. I think, need to continue discussion here:
https://github.com/micronaut-projects/micronaut-core/issues/10253
