### ISSUE TITLE
@Schema oneOf/anyOf/allOf included in unison

### ISSUE THREAD

**Issue by sk-jdriven** [micronaut-projects/micronaut-openapi#1346]
### Expected Behavior

When using the `@Schema` annotation with a `oneOf`, `anyOf` or `allOf` parameter specified, only the specified parameter is included in the resulting specification. 

### Actual Behaviour

When using the `@Schema` annotation, `oneOf`, `anyOf`, `allOf` are all included in the resulting specification, where the unspecified parameters are included as an empty array. 

### Steps To Reproduce

In a micronaut project with io.micronaut.openapi:micronaut-openapi, include the following controller:

```
@Controller("/test")
public class TestController {

  @Get
  @Operation(
    summary = "summary",
    description = "description",
    responses = {
      @ApiResponse(
        description = "response",
        content = @Content(
          mediaType = MediaType.APPLICATION_JSON,
          schema = @Schema(oneOf = {String.class, UUID.class})
        )
      )
    }
  )
  void test() {
  }
}
```

Observe that in micronaut 4.1.2 the resulting spec contains:

```
  /test:
    get:
      summary: summary
      description: description
      operationId: test
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                oneOf:
                - type: string
                - type: string
                  format: uuid
```
Observe that in micronaut 4.2.0 the resulting spec contains:

```
  /test:
    get:
      summary: summary
      description: description
      operationId: test
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                allOf: []
                anyOf: []
                oneOf:
                - type: string
                - type: string
                  format: uuid
```

### Environment Information

openjdk version: 17.0.9
gradle: 8.1.1

defect versions:
micronaut: 4.2.0
micronaut-openapi-annotations: 6.1.0
io.swagger.core.v3:swagger-annotations: 2.2.19

working versions:
micronaut: 4.1.2
micronaut-openapi-annotations: 5.1.1
io.swagger.core.v3:swagger-annotations: 2.2.15

### Version

4.2.0

**Comment by altro3** [comment]
I fixed it, but it is a bug in core module: https://github.com/micronaut-projects/micronaut-core/issues/10242

**Comment by sk-jdriven** [comment]
Thank you for your efforts. I'll be awaiting the merge of your PR :+1:
