### ISSUE TITLE
Java 8 Instant: Swagger: shows as int64

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-openapi#135]
as per: https://github.com/micronaut-projects/micronaut-core/pull/1051/files#diff-7d8651bbcaeaf26de54ffc84226d1673R85

Is the proper usage of Instant to be returned as a int64? rather than a date-time (without timezone)

Seems that int64 should be converted to date-time format?

**Comment by croudet** [comment]
Yes

**Comment by StephenOTT** [comment]
@croudet I was working on 1.3.4 and still seeing the same int64 in the swagger files.
Based on the examples in the files you linked to, you have to explicitly set the schema for each java date property as "date-time" or is there auto-magic by micronaut openapi to add these based on the type?

**Comment by croudet** [comment]
Looks like it is how swagger-core handles Instant:

https://github.com/swagger-api/swagger-core/blob/8c815ad9c0bbc1f9e41676175067f5526185f20a/modules/swagger-core/src/main/java/io/swagger/v3/core/util/PrimitiveType.java#L248

**Comment by StephenOTT** [comment]
The workaround for this is to use add `@Schema(type = "string", format = "date-time")` to the field or wrapping class

**Comment by graemerocher** [comment]
Seems reasonable. Don’t think we should change swaggers default behavior here

**Comment by StephenOTT** [comment]
agreed.
