### ISSUE TITLE
@Version annotation prevents the swagger-ui page from loading

### ISSUE THREAD

**Issue by sk-jdriven** [micronaut-projects/micronaut-openapi#1361]
### Expected Behavior

When visiting the `swagger-ui/index.html` page, the Swagger page loads correctly.

### Actual Behaviour

After migrating to micronaut 4, a `@Version("beta")` annotation adds a new breaking element called `urls` to the index.html script, causing a `Uncaught SyntaxError: Unexpected identifier 'beta' (at index.html:57:84)`:

```
<script>
window.onload = function() {

         ... 

            ui = SwaggerUIBundle({
                    url: contextPath + '/swagger/my-specification.yml',
                    dom_id: '#swagger-ui',
                    presets: [
                        SwaggerUIBundle.presets.apis,
                        SwaggerUIStandalonePreset
                    ],
                    plugins: [
                        SwaggerUIBundle.plugins.DownloadUrl,
                        f
                    ],
                    
                    urls: [{url: contextPath + '/swagger/my-specification.yml, name: 'beta'}],
                    deepLinking: true,
                    layout: "StandaloneLayout",
                    tagsSorter: "alpha",
                    validatorUrl: null
                });
        
        ...

</script>
```

### Steps To Reproduce

1. On a Micronaut 4.2.1 project with the following dependencies:
```
annotationProcessor("io.micronaut.openapi:micronaut-openapi")
compileOnly("io.micronaut.openapi:micronaut-openapi-annotations")
```

2. Define the following controller:
```
import io.micronaut.core.version.annotation.Version;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

@Version("beta")
@Controller("/test")
public class TestController {

    @Get
    void test() {
    }
}
```

3. Visit http://localhost:{port}/swagger-ui/index.html
4. Witness a blank page and the earlier mentioned SyntaxError in the console 
5. Removing the controller or the `@Version` annotation will resolve the issues.

### Environment Information

openjdk 17.0.9 2023-10-17
gradle-8.1.1

micronaut: 4.2.1
io.micronaut.openapi-annotations: 6.1.0

### Version

4.2.1

**Comment by altro3** [comment]
It's already fixed here: https://github.com/micronaut-projects/micronaut-openapi/pull/1322.

Juset, use micronaut-openapi 6.3.0
