### ISSUE TITLE
Micronaut for Spring Boot ignores path on @RestController

### ISSUE THREAD

**Issue by mikaelvik** [micronaut-projects/micronaut-openapi#144]
I've created an [example project](https://gitlab.com/mvik-micronaut/mvik-openapi/-/tree/master/mvik-openapi-microboot) using Micronaut to generate OpenAPI yaml for a Spring Boot application. 

Micronaut seems to ignore the path specified on `@RestController` annotations when generating the yaml file. 

The only Swagger annotation I've used is `@OpenAPIDefinition` on the Micronaut application class (and I'd like to keep it that way). 

Controller: 

```java
@RestController
@RequestMapping("/api/goodbyes") // edited
public class GoodbyeRestController {

    @GetMapping("/{name}")
    Map<String, String> goodbye(@PathVariable String name) {
        return Collections.singletonMap("goodbye", name);
    }
}
```

Excerpt from openapi.gradle (applied by build.gradle): 

```groovy
sourceSets {
    openapi {
        compileClasspath += sourceSets.main.compileClasspath
        java {
            srcDirs = [
                'src/main/java',
                'src/openapi/java'
            ]
        }
    }
}
```

Application class:

```java
@OpenAPIDefinition(info = @Info(title = "mvik-openapi-microboot", version = "0.1"))
public class MicronautApplication {

    public static void main(String[] args) {
        Micronaut.run(MicronautApplication.class);
    }
}
```
Output:

```yaml
openapi: 3.0.1
info:
  title: mvik-openapi-microboot
  version: "0.1"
paths:
  /{name}:
    get:
      operationId: goodbye
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: goodbye default response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
```

**Comment by graemerocher** [comment]
According to https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RestController.html

The value of `@RestController` represents the bean name in Spring and not the URI. I believe to get the behaviour you want have to use:

```java
@RestController
@RequestMapping("/api/goodbyes")
```

**Comment by mikaelvik** [comment]
Sorry for the terrible example code, the problem is also there when using `@RequestMapping`. I've used the same approach on an existing work project where all the `@RequestMapping` paths were ignored. 

I've changed the example code, and the path is still being ignored.

**Comment by mikaelvik** [comment]
The example uses Micronaut 1.3.1 and Spring Boot 2.2.4.RELEASE.

**Comment by graemerocher** [comment]
From the looks of this, it seems that Micronaut Spring turns `@RequestMapping` into Micronaut's `@UriMapping` here https://github.com/micronaut-projects/micronaut-spring/blob/master/spring-web-annotation/src/main/java/io/micronaut/spring/web/annotation/RequestMappingAnnotationMapper.java#L85

Micronaut OpenAPI only considers the `@Controller` annotation though unfortunately https://github.com/micronaut-projects/micronaut-openapi/blob/master/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java#L142

So the fix would be to also consider `@UriMapping` I imagine.

PRs welcome.

**Comment by graemerocher** [comment]
In fact since `@Controller` is an alias for `@UrlMapping` in Micronaut https://github.com/micronaut-projects/micronaut-core/blob/7f48aac4c8090974e56d1cc89830cb6b201dc1d2/http/src/main/java/io/micronaut/http/annotation/Controller.java#L58

Probably only `@UriMapping` needs to be considered

**Comment by mikaelvik** [comment]
I'll give it a try. Thanks for the feedback.

**Comment by mikaelvik** [comment]
PR created: https://github.com/micronaut-projects/micronaut-openapi/pull/150

**Comment by mikaelvik** [comment]
The fix worked on my example project, that's at least something. Thanks for the pointers.

**Comment by graemerocher** [comment]
@mikaelvik you can try the just release `1.4.0` version in your project. Let us know how it goes. Hope you write a blog post about what you are doing, seems really interesting :)

**Comment by mikaelvik** [comment]
> @mikaelvik you can try the just release `1.4.0` version in your project. Let us know how it goes. Hope you write a blog post about what you are doing, seems really interesting :)

The release worked perfectly, thanks. Looking forward to the next final release of Micronaut.

I'm not much of a blogger, but I'd be happy to contribute with a section to the docs. The idea is to use a separate source set for the openapi stuff to avoid leaking dependencies into the classpath of the Spring Boot application.

**Comment by graemerocher** [comment]
@mikaelvik sounds good
