### ISSUE TITLE
Gradle task kspKotlin never finishes using Micronaut 4.3.x

### ISSUE THREAD

**Issue by davidsonnabend** [micronaut-projects/micronaut-openapi#1455]
### Expected Behavior

Application code compiles successfully.

### Actual Behaviour

When using Micronaut 4.3.2 in combination with micronaut-openapi the application will not compile because gradle task `kspKotlin` never finishes.

### Steps To Reproduce

1. Clone example application or create a new one 
2. Run `./gradlew run`

### Environment Information

- Operating System: Ubuntu 23.10
- JDK Version: 21.0.1-zulu

### Example Application

https://github.com/davidsonnabend/micronaut-openapi-ksp-bug

### Version

4.3.2

**Comment by altro3** [comment]
I tried to run your sample project - all works fine

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/505f1f64-e259-4e13-bb79-22bf3f5510df)

Maybe it's your local troubles?

**Comment by altro3** [comment]
But I use Windows 11 and liberica-jdk

**Comment by davidsonnabend** [comment]
After deleting the `.gradle` folder it also works for me.

Unfortunately this simple step doesn't fix the issue in my "real" project. Here I need to remove `micronaut-openapi` to make the project compile using Micronaut 4.3.2. I will try to reproduce it in the demo project and keep you updated.

**Comment by altro3** [comment]
It would be nice to get an example from you to reproduce the problem. Because I didn't add MappedEntity support to micronaut-openapi. Maybe I can solve the problem.

**Comment by davidsonnabend** [comment]
I already spent quite some time to isolate the problem to reproduce the error in a demo project but didn't managed it. As soon as I can reproduce the error without sharing our whole project I will let you know.

**Comment by altro3** [comment]
@davidsonnabend any news about this? Or we can close this issue?

**Comment by davidsonnabend** [comment]
Unfortunately, I didn't have time to reproduce the error in a demo project. Sorry! 

So yes - let's close the issue for now.
