### ISSUE TITLE
Swagger cannot redirect to redirect_uri because it was generated incorrectly

### ISSUE THREAD

**Issue by guima** [micronaut-projects/micronaut-openapi#1468]
### Expected Behavior

Could generate the callback URL including swagger-ui directory before oauth2-redirect.html when property swagger-ui.oauth2RedirectUrl is undefined in openapi.properties.

The callback URL could be:
```sh
https://authorizationserver.com/oauth2/authorize?response_type=code&client_id=11111111-1111-1111-1111-111111111111&redirect_uri=https%3A%2F%2Fexample-app.com%2Fapi%2Fswagger-ui%2Foauth2-redirect.html&scope=openid&state=xxx
```

### Actual Behaviour

The callback URL cannot find oauth2-redirect.html generated in the swagger-ui directory because it is missing.

Wrong callback URL:
```sh
https://authorizationserver.com/oauth2/authorize?response_type=code&client_id=11111111-1111-1111-1111-111111111111&redirect_uri=https%3A%2F%2Fexample-app.com%2Fapi%2Foauth2-redirect.html&scope=openid&state=xxx
```

### Steps To Reproduce

1. Add openapi.properties without swagger-ui.oauth2RedirectUrl
   ```sh
   swagger-ui.enabled=true
   swagger-ui.oauth2.clientId=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
   swagger-ui.oauth2.clientSecret=bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
   swagger-ui.oauth2.scopes=openid
   swagger-ui.oauth2.useBasicAuthenticationWithAccessCodeGrant=true
   redoc.enabled=false
   rapidoc.enabled=false
   ```
2. Open Swagger UI 
   ```sh
   https://example-app.com//api/swagger-ui 
   ```
3. Click on Authorize button

### Environment Information

- Micronaut Version: 4.3.4
- Micronaut OpenAPI Version: 6.6.3
- Operating System: Ubuntu Linux 22.04.1
- JDK Version: 21

### Version

4.3.4

**Comment by altro3** [comment]
@guima  Please, add a sample application to reproduce your problem. But for now I don’t understand why you can’t just add the `oauth2RedirectUrl` property to swagger-ui . In any case, please describe it. more specifically what's wrong, because I haven't figured out how to reproduce your problem yet

**Comment by altro3** [comment]
I'll explain in more detail: I tried to reproduce your problem, but it didn't work. My example:

1. openapi.properties - the same as yours
2. Application.java:
```java
@OpenAPIDefinition(
         info = @Info(
                 title = "broken-micronaut-openapi-expand",
                 version = "sdsd",
                 description = "my desc"
         )
)
@SecurityScheme(name = "myOauth2Security",
         type = SecuritySchemeType.OAUTH2,
         flows = @OAuthFlows(
                 implicit = @OAuthFlow(authorizationUrl = "http://localhost:8080",
                         scopes = @OAuthScope(name = "write:pets", description = "modify pets in your account"))))
@ContextConfigurer
public class Application implements ApplicationContextConfigurer {

     @Override
     public void configure(ApplicationContextBuilder builder) {
         System.out.println("Java configurer loaded");
         builder.deduceEnvironment(false)
                 .banner(false)
                 .defaultEnvironments("local");
     }

     public static void main(String[] args) {
         Micronaut.run(Application.class, args);
     }
}
```
3. Generated swagger UI settings in `index.html`:
```js
                ui = SwaggerUIBundle({
                    url: contextPath + '/swagger/broken-micronaut-openapi-expand-sdsd.yml',
                    dom_id: '#swagger-ui',
                    presets: [
                        SwaggerUIBundle.presets.apis,
                        SwaggerUIStandalonePreset
                    ],
                    plugins: [
                        SwaggerUIBundle.plugins.DownloadUrl,
                        f
                    ],
                    
                    
                    deepLinking: true,
layout: "StandaloneLayout",
tagsSorter: "alpha",
validatorUrl: null
                });
                ui.initOAuth({
clientId: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
clientSecret: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
scopes: "openid",
useBasicAuthenticationWithAccessCodeGrant: true
});
            window.ui = ui;
            
        };
```

4. Swagger UI: 
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/1ced2d05-7b50-43f6-9880-dd1ccd60078f)

5. Result:
```json
{
  "_links": {
    "self": [
      {
        "href": "/?response_type=token&client_id=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fswagger-ui%2Foauth2-redirect.html&scope=openid%20write%3Apets&state=VGh1IE1hciAwNyAyMDI0IDEzOjUyOjI5IEdNVCswNzAwICjQndC%2B0LLQvtGB0LjQsdC40YDRgdC6LCDRgdGC0LDQvdC00LDRgNGC0L3QvtC1INCy0YDQtdC80Y8p",
        "templated": false
      }
    ]
  },
  "_embedded": {
    "errors": [
      {
        "message": "Page Not Found"
      }
    ]
  },
  "message": "Not Found"
}
```

As you see, `redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fswagger-ui%2Foauth2-redirect.html`

**Comment by guima** [comment]
This is my [Example Application](https://github.com/guima/example-app-swagger).

Maybe the use of /api as context path is causing this problem, but that's just a guess.

**Comment by guima** [comment]
I can't just add the `oauth2RedirectUrl` property to the `openapi.properties` file because that URL is added at compile time. The authorization server URL may vary in different environments. To achieve this, it would be necessary to build an artifact for each environment.

**Comment by altro3** [comment]
Hm... I still can't reproduce your problem. By your example:

1. First, I've added environment variable `AUTHZSERVER_URL=http://localhost:8080` for build stage
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/a8f9f699-d0c1-4b72-a4a2-9483f246cfcd)
2. Generated swaggerfile:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/9092eb8a-f755-4781-9912-11d867f9b6a4)

3. Add  variable `AUTHZSERVER_URL=http://localhost:8080`  for runtime environment
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/2b238595-eeed-4ee9-8066-ab7a00fb1ef9)

4. Swagger UI
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/766154f2-b8e0-4374-bc8b-686ada57b89d)
5. Authorize form 
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/c2a06ef6-0b8e-47d6-af26-4e5921d05148)
6. Click to `Authorize` 
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/3a22f387-60e4-4078-b902-80d739f26d5f)

As you see all is ok: 
Full address: `"/oauth2/authorize?response_type=code&client_id=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fapi%2Fswagger-ui%2Foauth2-redirect.html&scope=openid&state=RnJpIE1hciAwOCAyMDI0IDE0OjM5OjE4IEdNVCswNzAwICjQndC%2B0LLQvtGB0LjQsdC40YDRgdC6LCDRgdGC0LDQvdC00LDRgNGC0L3QvtC1INCy0YDQtdC80Y8p"`

redirectUri: `redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fapi%2Fswagger-ui%2Foauth2-redirect.html`

**Comment by altro3** [comment]
Oh, now I see...

If I changed `AUTHZSERVER_URL=http://localhost:8080` to `AUTHZSERVER_URL=http://localhost:8080/api`, I see this:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/31ff0d78-2ad0-4c57-b1dd-6813f29d34c9)
After click `Authorize`:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/d3cc25cf-98f6-4cd9-93c4-9bcf9a408149)
`redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fapi%2Foauth2-redirect.html`
Hmm... It looks like a swagger-ui specific.

**Comment by altro3** [comment]
The single solution as I see, just set swagger-ui `oauth2RedirectUrl` property manually. For it, remove file `openapi.properties` and add your openapi properties to your annotation processor:
```xml
<arg>-Amicronaut.openapi.views.spec=swagger-ui.enabled=true,swagger-ui.oauth2.clientId=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa,swagger-ui.oauth2.clientSecret=bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb,swagger-ui.oauth2.scopes=openid,swagger-ui.oauth2.useBasicAuthenticationWithAccessCodeGrant=true,swagger-ui.oauth2RedirectUrl=http://localhost:8080/api/swagger-ui/oauth2-redirect.html</arg>
```
Just add this line to your pom.xml. Also, you can generate this string yourself on build stage and replace `http://localhost:8080/` to yor value.

Unfortunately, at the moment it is not possible to set each property separately for swagger-ui through system variables or environment variables, but, as you can see, you can set all values separated by commas through the `micronaut.openapi.views.spec` system variable

After this you will see correct redirect url:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/4c051a44-a4cb-4668-a9e9-11de6db4f685)

**Comment by altro3** [comment]
@guima Good news for you. You can divide variables into different sources so as not to write such a long inconvenient line. You can leave fixed values as they are in the openapi.properties file, and move dynamic values to system variables or environment variables:

openapi.properties:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/cdcb8835-b412-4a60-9f1e-92f4026657b7)

pom.xml:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/88a9d119-7c2c-4758-96b2-0346fd16d50c)

Or you can set environment variable like this:

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/161129f5-df75-4092-916e-0db927c5a67a)

**Comment by altro3** [comment]
As I told you, this is swagger-ui specific

**Comment by guima** [comment]
Thanks for your help.
