### ISSUE TITLE
Kotlin build with gradle as a task?

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-openapi#154]
Given the following https://github.com/micronaut-projects/micronaut-openapi/commit/8580053fa8eba6ef7240ebcf32124bb570202f18#diff-be736fa0603c7b3afef21219b6a05e38

Is there a solution to running this as a regular build task? It seems you cant run this within a ide like Intellij as a regular build task.  You have to run it manually through terminal.

**Comment by croudet** [comment]
This is only mandatory if you want to use views (swagger-ui, ...)

**Comment by croudet** [comment]
if you want to generate views with 1.4.0, you can create a file `openapi.properties` at the root level of your project dir.
```
rapidoc.enabled=true
rapidoc.bg-color=#14191f
rapidoc.text-color=#aec2e0

rapipdf.enabled=true
rapipdf.pdf-footer-text=My Company

redoc.enabled=true

swagger-ui.enabled=true
swagger-ui.theme=flattop
```

**Comment by StephenOTT** [comment]
Thanks. Works in 1.4.0

**Comment by StephenOTT** [comment]
Would like a PR for docs update?

**Comment by croudet** [comment]
I think the doc is up to date, but if you find something missing PRs ar welcome.
