### ISSUE TITLE
Bug with referencing openapi parameters

### ISSUE THREAD

**Issue by zac1wz** [micronaut-projects/micronaut-openapi#1548]
### Expected Behavior

@PathVariable should be generated instead of nothing being generated

### Actual Behaviour

WeatherForecastApisApi.java:56: error: The route declares a uri variable named [id], but no corresponding method argument is present

### Steps To Reproduce

Reproducible example below. 
Just run `./gradlew build`

### Environment Information

macOS Sonoma 14.4
JDK Amazon Corretto 17.0.8

### Example Application

https://github.com/CezaryBD/micronaut-openapi-path-variable-problem-01

### Version

4.4.0

**Comment by HristoP96** [comment]
Same here

**Comment by zac1wz** [comment]
Small hint: If you completely remove **hourly** param reference, the app compiles and generates @PathVariable.
