### ISSUE TITLE
Adding /login endpoint to Open API

### ISSUE THREAD

**Issue by zokica8** [micronaut-projects/micronaut-openapi#156]
Is there a way to add a /login endpoint generated by Micronaut itself with login enabled true in application.yml to Swagger Documentation?

**Comment by andydoe19** [comment]
Hello @alvarosanchez If this is a duplicate, where can I find the answer please?

**Comment by alvarosanchez** [comment]
@andydoe19 #197 duplicates #156

I don't know what "answer" are you looking for, but #156 is still open and therefore not implemented

**Comment by JouperCoding** [comment]
+ 1 for this request in addition it would be nice to have /oauth/access_token & /logout added to the generated swagger.

**Comment by dargenn** [comment]
Is there a way to manually add those entries?

**Comment by ilopmar** [comment]
@dargenn Yes, you can use this: https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#mergingSchemas

**Comment by TorosyanV** [comment]
@alvarosanchez why you are marking it as duplicate, but still no answer?

**Comment by alvarosanchez** [comment]
@TorosyanV you are probably misinterpreting the history of this issue.

This issue was never marked as duplicate. #197 was, as said in https://github.com/micronaut-projects/micronaut-openapi/issues/156#issuecomment-701951706

This issue was closed as fixed by #364
