### ISSUE TITLE
Remote references for schema not working

### ISSUE THREAD

**Issue by ricker-flow** [micronaut-projects/micronaut-openapi#1613]
### Expected Behavior

OpenAPI supports remote references for schema. Instead of reference components inside the document `$ref: '#/components/schema/Foo'` it can refer to a external files such as `$ref: '../folder/foo.json'`. See https://swagger.io/docs/specification/using-ref/ 

### Actual Behaviour

Using a remote reference returns an error `Failed to get the schema name:`

### Steps To Reproduce

1. Create a OpenAPI yaml file with a remote reference for a schema
2. Run the Micronaut OpenApi Gradle plugin

### Environment Information

- Mac
- Kotlin
- Micronaut OpenAPI 4.4.0

### Example Application

https://github.com/ricker-flow/openapi-demo

### Version

4.4.0

**Comment by altro3** [comment]
Yes, it's true. Currently we support only one file specifications.

Please add an example of using this feature, then I can solve this problem faster.

Did I understand correctly that you have a specification in several files and are trying to use openapi generator?

**Comment by ricker-flow** [comment]
I have the schema of the object separate from the API YAML. I created an example https://github.com/ricker-flow/openapi-demo

**Comment by altro3** [comment]
So, the problem is that openapi-generator itself does not support such schema descriptions. So if you want this feature to be added, then create a ticket here: https://github.com/OpenAPITools/openapi-generator

**Comment by ricker-flow** [comment]
Seems it has been an open issue for 6 years https://github.com/OpenAPITools/openapi-generator/issues/1123

**Comment by altro3** [comment]
@ricker-flow Sorry, that was my mistake. openapi-generator supported multiple files specifications. Problem fixed here: https://github.com/micronaut-projects/micronaut-openapi/pull/1738

I tested this fix also with your sample - all works fine, but in your sample was mistke in bookinfo.json file - wrong place for required block.
