### ISSUE TITLE
Add support for adding extensions under path

### ISSUE THREAD

**Issue by leenanimbekar** [micronaut-projects/micronaut-openapi#167]
openapi supports adding extensions under path as well, but with micronaut-openapi, not able to add one. Need to add extension under path as given here https://help.apiary.io/api_101/swagger-extensions/ .

expected :
```
openapi: 3.0.1
paths:
  /some-path:
    get:
      description: Finds a squirrel's location.
    x-extension: extension-value
```
actual: 
```
openapi: 3.0.1
paths:
  /some-path:
    get:
      description: Finds a squirrel's location.
      x-extension: extension-value
```

**Comment by croudet** [comment]
Can you show the annotation mapping?

**Comment by leenanimbekar** [comment]
```
   @Get("/some-path", produces = ["application/json"])
   @Operation(extensions = [
       Extension(name="", properties = [
           ExtensionProperty(name = "extension", value = "extension-value")
       ])], description = "Finds a squirrel's location.")
```

**Comment by croudet** [comment]
I don't think it is currently possible to do it with annotation, see swagger tests:

- https://github.com/swagger-api/swagger-core/blob/1e38c2828809e330b830398fae41fc7bea7c14ac/modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java#L527
- https://github.com/swagger-api/swagger-core/blob/26d72bf5fd2d54e5e514ddcf3861d125d2f95b42/modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/extensions/OperationExtensionsResource.java
- 
https://github.com/swagger-api/swagger-core/blob/1e38c2828809e330b830398fae41fc7bea7c14ac/modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/extensions/ExtensionsResource.java

**Comment by leenanimbekar** [comment]
Can this be added ?

**Comment by croudet** [comment]
You should ask this on a swagger forum.
