### ISSUE TITLE
Custom headers used in API calls are not correctly used in the HTTP call

### ISSUE THREAD

**Issue by theobisproject** [micronaut-projects/micronaut-openapi#1676]
### Expected Behavior

The HTTP request uses the defined OpenAPI spec header names.

```
DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP HEAD to http://localhost:8080
TRACE i.m.h.client.netty.DefaultHttpClient - x-test-crc32: test-crc32
TRACE i.m.h.client.netty.DefaultHttpClient - x-test-sha512: test-sha512
TRACE i.m.h.client.netty.DefaultHttpClient - x-test-size: 100
TRACE i.m.h.client.netty.DefaultHttpClient - host: localhost:8080
```

I already checked that in the https://github.com/micronaut-projects/micronaut-core/blob/4.6.x/http-client-core/src/main/java/io/micronaut/http/client/bind/DefaultHttpClientBinderRegistry.java#L111 the value from the generated @Header annotation is not taken from the name value. But hyphenated from the argument name.

### Actual Behaviour

The HTTP request has different headers than defined in the OpenAPI spec.

```
DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP HEAD to http://localhost:8080
TRACE i.m.h.client.netty.DefaultHttpClient - xt-estcrc32: test-crc32
TRACE i.m.h.client.netty.DefaultHttpClient - xt-estsha512: test-sha512
TRACE i.m.h.client.netty.DefaultHttpClient - xt-estsize: 100
TRACE i.m.h.client.netty.DefaultHttpClient - host: localhost:8080
```

### Steps To Reproduce

1. Use the unit test in the example repository
2. See the log taces

### Example Application

https://github.com/theobisproject/openapi-micronaut-test

### Version

4.4.2

**Comment by altro3** [comment]
Your example app doesn't work:

![изображение](https://github.com/user-attachments/assets/c6b9f93d-36a8-42ee-8108-4f9517351607)

**Comment by altro3** [comment]
I checked it with another way, but all works fine

![изображение](https://github.com/user-attachments/assets/64557ae0-d526-42aa-adae-2e83a60ed26d)

Check with my test project here: https://github.com/altro3/micronaut3-bug

Anyway, if you have a problem, that's wrong project for it. There is project for openapi specification generating by code and vice versa. If you have problems with client requests, need to create issue in core project: https://github.com/micronaut-projects/micronaut-core

**Comment by theobisproject** [comment]
Sorry, should have noted that at the api endpoint there has to be some http server running. Otherwise the request runs into the connection refused error you have posted.

The problem is right there in the middle of your screeshot. The header should be `x-test-crc32` and not `xt-estcrc32`.
As far as I can tell the problem is the generation of the @Header value for the method. It is currently generated as `@Header(name = "X-TEST-crc32")` but I think it only works if it is `@Header(value = "X-TEST-crc32")`.

Sorry if this is the wrong project. All those different repos are quite confusing for someone new :wink: I thought this is a generation error so I opened it here.

**Comment by altro3** [comment]
All clear. Well, I ran your example again, but with version micronaut-openapi 6.12.0-SNAPSHOT. I have already fixed this problem, now the generated code for headers sets the value attribute, not the name as before. And the error went away by itself, so wait for the release of 6.12.0

![изображение](https://github.com/user-attachments/assets/be6b4dd9-14cd-48d8-be14-6cda6a35a53c)

![изображение](https://github.com/user-attachments/assets/ff25a809-f871-4d8b-9ac8-f677096ccca3)

**Comment by theobisproject** [comment]
Thanks for checking :heart:  Then I will wait for the next release

**Comment by altro3** [comment]
@theobisproject Anyway, you found a bug, but not in openapi, just in core module. I created issue for this:

https://github.com/micronaut-projects/micronaut-core/issues/11053
