### ISSUE TITLE
`@Schema` annotation on DTO field generates an OpenAPI spec with description (readOnly, requiredMode, etc) under allOf instead of on the property

### ISSUE THREAD

**Issue by kevin-wise** [micronaut-projects/micronaut-openapi#1680]
### Expected Behavior

Annotating a field with `@Schema(description = "abc")` should result in the description in the generated OpenApi spec being on the component model property, the same as if the field had a JavaDoc comment.

### Actual Behaviour

The generated OpenApi spec puts the description on under `allOf`, where it can't be used by generators as the property description. Also some generators create a subclass just to hold the description, which is not at all the intended effect.

### Steps To Reproduce

```java
@Schema(description = "A simple DTO")
public class MyDto {
  @Schema(description = "A string field")
  private String field1;
  // ...
}

@Schema(description = "A DTO containing the other DTO")
public class MyDto2 {
  @Schema(description = "A field containing another DTO") // <== This description should be on the property not the nested schema
  private MyDto field2;
  // ...
}
```

generates an openapi spec with 
```yaml
components:
  schemas:
    MyDto:
      type: object
      properties:
        field1:
          type: string
          description: A string field
      description: A simple DTO
    MyDto2 :
      type: object
      properties:
        field2:
          allOf:
            - $ref: "#/components/schemas/MyDto"
            - description: A field containing another DTO
      description: A DTO containing the other DTO
```
But it should be:
```yaml
components:
  schemas:
    MyDto:
      type: object
      properties:
        field1:
          type: string
          description: A string field
      description: A simple DTO
    MyDto2 :
      type: object
      properties:
        field2:
          allOf:
            - $ref: "#/components/schemas/MyDto"
          description: A field containing another DTO
      description: A DTO containing the other DTO
```

Note that in the expected output, the description `"A field containing another DTO"` is on the property. In the first one, it's on the allOf schema.

A partial workaround is to remove the `@Schema` annotation and put the description in the JavaDoc for the field. That does generate the correct OpenApi spec in some cases but not in others.

Also, this may not be limited to just `description`. Other schema properties like `required` or `requiredMode` should also be placed on the property, not pushed under `allOf`. For example: `@Schema(requiredMode = RequiredMode.REQUIRED)`.

### Environment Information

Java 21

### Version

4.4.3

**Comment by altro3** [comment]
In general, strictly speaking, the Openapi file is generated correctly. It's more likely the generators' fault that they don't interpret the allOf block correctly. This was done precisely because the specification does not specify which schema properties will be taken into account if you use allOf . For example, `required`, `deprecated`, `title`, `description`, `nullable` are taken into account, but `maximum`, `minimum`, `type` etc. are ignored.

If you have a correct list of properties that we can unwrap, then it would be nice if you wrote them.

**Comment by altro3** [comment]
anyway, I fixed it :-)

**Comment by kevin-wise** [comment]
Thanks! It does seem like something that the OpenAPI team could build into their normalizer. But this way we don't have to wait for them to fix it.

If I get a chance later today I'll pull it down, build it and let you know how it works with my current service.

> If you have a correct list of properties that we can unwrap, then it would be nice if you wrote them.

I'm guessing you no longer need that list :)

**Comment by kevin-wise** [comment]
Tested locally, it seems to be working as intended
![image](https://github.com/user-attachments/assets/9b53a699-9f62-4121-affa-5372562ae547)

I did notice a new problem, which seems unrelated. I can write up another issue if you would like.  In cases where `:` is part of the path, it's inserting an extra `/` before the `:`. For example:
![image](https://github.com/user-attachments/assets/85046149-d13a-4d8a-a627-2e5d35da2508)
Is that unrelated?

**Comment by altro3** [comment]
Yes, that's another problem. Please create a separate issue with an example

**Comment by altro3** [comment]
@kevin-wise Fixed it here: https://github.com/micronaut-projects/micronaut-openapi/pull/1687

**Comment by kevin-wise** [comment]
Wow, thanks for the quick turnaround!
