### ISSUE TITLE
Kotlin server generator adding suffix and prefix to builtins types

### ISSUE THREAD

**Issue by KDanisme** [micronaut-projects/micronaut-openapi#1690]
### Expected Behavior

When speficying schema of a model as: 
```
type: string
format: uuid
```

The type of the model should use: 
`java.util.UUID`

### Actual Behaviour

The actual type is: `<modelPackageName>.<prefix>UUID<suffix>`
For example: `com.example.model.UUIDDTO`
Which doesn't exist.

This doesn't happen when generating for java obviously.

### Steps To Reproduce

1. Configure gradle with:
```
micronaut {
    openapi {
        server(file("openapi.yml")) {
            modelNameSuffix = "DTO"
            lang = "kotlin"
        }
    }
}
```
2. generate models

### Environment Information

- Operating System: `Nixos`
- jdk: `graalvm-ce-22.0.2`

### Version

4.4.2

**Comment by altro3** [comment]
Hmmm... By specification for UUID you need to specify schema like this:
```yaml
type: string
format: uuid
```

**Comment by KDanisme** [comment]
> Hmmm... By specification for UUID you need to specify schema like this:
> 
> ```yaml
> type: string
> format: uuid
> ```

Sorry i made a typo.
It is indeed: 
```
type: string
format: uuid
```
I'll edit the issue

**Comment by altro3** [comment]
Fixed. Wait release 6.12.0

**Comment by KDanisme** [comment]
> Fixed. Wait release 6.12.0

That was fast! much appreciated
