### ISSUE TITLE
openapi not able to generate using kotlin 2.0.10

### ISSUE THREAD

**Issue by byronwong-dev** [micronaut-projects/micronaut-openapi#1697]
### Expected Behavior

openapi spec is able to generate in folder `build/generated/ksp/main/resources/META-INF`

### Actual Behaviour

when bump kotlin to version 2.0.10, it does not generate any openapi spec

### Steps To Reproduce

Run `./gradlew kspKotlin`  in project

### Environment Information

- MacOS/linux
- JDK 21
- Gradle

### Example Application

https://github.com/byronwong-dev/micronaut-openapi-kotlin-issue/tree/master

### Version

4.5.1

**Comment by altro3** [comment]
@byronwong-dev Can't reproduce it with your sample. All works fine:
![изображение](https://github.com/user-attachments/assets/4e4892a1-a288-4725-ba37-109303a9d908)

**Comment by byronwong-dev** [comment]
might've been my side. thanks for verifying!
