### ISSUE TITLE
 Default Values not set for QueryValues that are of type array

### ISSUE THREAD

**Issue by scprek** [micronaut-projects/micronaut-openapi#1719]
Unknown if this affects all Controller method types `@Header`, `@QueryValue`, etc

### Expected Behavior

```json
{
  "parameters": [
    {
      "name": "ids",
      "in": "query",
      "description": "if passed will return all active orders for a given ids",
      "required": false,
      "schema": {
        "type": "array",
        "items": {
          "type": "integer"
        },
        "default": null
      }
    }
  ]
}
```

Sets default to null

```kotlin
@QueryValue("ids") @Nullable ids: List<@NotNull Int>? = null
```

### Actual Behaviour

```kotlin
@QueryValue("ids") @Nullable ids: List<@NotNull Int>?,
```

Just to check, I also made the Ints insid the list Nullable and still no default value

```kotlin
@QueryValue("ids") @Nullable ids: List<@Nullable Int?>?,
```

### Steps To Reproduce

Expansion from https://github.com/micronaut-projects/micronaut-openapi/issues/1686

It appears this also works with my `QueryValue`'s too, but not when it's a list? Should I create a new ticket?

## Simple Type Example

This one worked

```json
{
  "parameters": [
      "MarketId": {
        "name": "market_id",
        "in": "query",
        "schema": {
          "type": "string",
          "default": null
        }
      }
  ]
}
```

```kotlin
@QueryValue("market_id") @Nullable marketId: String? = null,
```

## List Example

```json
{
  "parameters": [
    {
      "name": "ids",
      "in": "query",
      "description": "if passed will return all active orders for a given ids",
      "required": false,
      "schema": {
        "type": "array",
        "items": {
          "type": "integer"
        },
        "default": null
      }
    }
  ]
}
```

result

```kotlin
@QueryValue("ids") @Nullable ids: List<@NotNull Int>?,
```

### Environment Information

```kotlin
micronaut{
    openapi {
        // Fixes kotlin codegen with auth
        version.set("6.12.0-SNAPSHOT")
    }
}
```

### Version

4.5.1

**Comment by altro3** [comment]
@scprek Just add `nullable` flag to `ids` parameter

**Comment by altro3** [comment]
The problem in flag `required = false`. So kotlin generator understood, that parameter can be null, because it's not required, but nullable flag doesn't set. I added a condition that if the default value is not specified and the nullable flag is not specified, but it is indicated that the parameter is optional, then the default value null is added

**Comment by scprek** [comment]
🤦‍♂️ I missed the array is not nullable in the spec. Sorry about that. I had it set on all my other query params and totally missed the array. Regardless thanks!
