### ISSUE TITLE
Swagger ui does not render in 6.12.2 (platform 4.6.0)

### ISSUE THREAD

**Issue by krickert** [micronaut-projects/micronaut-openapi#1728]
### Expected Behavior

Swagger UI should render if setup with the tutorial

### Actual Behaviour

Swagger ui hangs and does not render.  The title page shows up though

### Steps To Reproduce

1. Download the swagger full solution project https://guides.micronaut.io/latest/micronaut-openapi-swagger-ui-maven-java.html
2. Change the version to 4.6.0 micronaut-platform
3. Recompile and run
4. Go to the swagger-ui page, the title renders but the page does not http://localhost:8080/swagger-ui

### Environment Information

Ubuntu LTS

java -version
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

Also tried with
krickert@krick:~/IdeaProjects/swagger-example$ java -version
openjdk version "17.0.12" 2024-07-16 LTS
OpenJDK Runtime Environment Corretto-17.0.12.7.1 (build 17.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.12.7.1 (build 17.0.12+7-LTS, mixed mode, sharing)

### Example Application

https://guides.micronaut.io/latest/micronaut-openapi-swagger-ui-maven-java.html

### Version

4.6.0

**Comment by krickert** [comment]
I just reverted back to 4.5 for now.  I honestly don't understand why it's not working - if you unzip the tutorial and just change it to 4.6.0 then it wouldn't render.  Chaange it back to 4.5.1 and it does.

I did attach it to a profiler and did see some calss not founds in it,but this could easily be unrelated.

**Comment by altro3** [comment]
@krickert hm.... something was changed in micronaut core. If you use micronaut-openapi 6.12.2 with micronaut-core modules 4.5.4 - all works fine. I'll look for what's changed... Apparently it's not worth updating the platform version to 4.6.0 until I figure this out. But you can use version 4.5.1 and connect the latest version of micronaut-openapi 6.12.2

**Comment by krickert** [comment]
@altro3  thanks!  Yeah, it's not a big deal on my side.  4.5.1 had a really bad bug with grpc (it was netty that caused it) so I was excited to jump onto 4.6.0.

I was making some big changes to my app and changed all my packages to 4.6.0, so I blamed myself at first.  I'm so glad you had that sample app sitting around so I was able to quickly distill that it wasn't my refactoring that caused it.

I'll update to 6.12.2 and keep a close eye on this one...

**Comment by altro3** [comment]
Here is issue with this bug: https://github.com/micronaut-projects/micronaut-core/issues/11114

**Comment by krickert** [comment]
Thanks for getting on this so quickly.  I saw similar issues in my profiler - I'll test as soon as it's ready.  Thanks again, looking forward to this build.

**Comment by krickert** [comment]
Looks like the fix for this was just merged - since it's a pretty big bug, I expect we'll see a release fairly soon.
