### ISSUE TITLE
Schema.oneOf annotation is ignored 

### ISSUE THREAD

**Issue by pditommaso** [micronaut-projects/micronaut-openapi#175]
As Micronaut is supporting Swagger `@Schema` annotation, it's expected the when using the `oneOf` property the corresponding definition is generated. 

For example:  

https://github.com/pditommaso/mn-openapi-oneof/blob/master/src/main/groovy/mn/openapi1/MyResponse.groovy#L7-L11

However corresponding metadata is generated, see 

https://github.com/pditommaso/mn-openapi-oneof/blob/7d2588357668da3a14d5d98934d2910c89496fbf/build/classes/groovy/main/META-INF/swagger/mn-openapi1-0.0.yml

Refer Swagger docs for details 
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/ 

Reproducible project: https://github.com/pditommaso/mn-openapi-oneof/

**Comment by croudet** [comment]
Can you try to add a test case to the project that reproduce the issue.

**Comment by pditommaso** [comment]
Not familiar with MN testing system, sorry.

**Comment by croudet** [comment]
It will help to know if it is a groovy only issue. Can you try to reproduce with Java?

**Comment by pditommaso** [comment]
Ok, let me try .

**Comment by pditommaso** [comment]
It provides even less meta info 

Java version [here](https://github.com/pditommaso/mn-openapi-java/blob/master/build/classes/java/main/META-INF/swagger/mn-openapi1-0.0.yml)

Groovy version [here](https://github.com/pditommaso/mn-openapi-oneof/blob/master/build/classes/groovy/main/META-INF/swagger/mn-openapi1-0.0.yml)

**Comment by croudet** [comment]
Thanks.

I have modified a bit your classes:
```java
package mn.openapi.java;

import io.swagger.v3.oas.annotations.media.Schema;

public class MyResponse {

    @Schema()
    Payload payload;

    public Payload getPayload() {
        return payload;
    }

    public void setPayload(Payload payload) {
        this.payload = payload;
    }
}
```
```java
package mn.openapi.java;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(oneOf = {PayloadFoo.class, PayloadBar.class})
public interface Payload {
}
```

generated yaml looks good with those modifications.

**Comment by pditommaso** [comment]
Gotcha. it also works for the groovy implementation. However should not also work when specifying the `Schema.oneOf` directly in the attribute. Looking at the definition of the annotation it should be allowed.

**Comment by croudet** [comment]
I am not enough of an expert to say.

**Comment by pditommaso** [comment]
Thanks for the feedback so far!
