### ISSUE TITLE
Datetime format in Http Client is Blank

### ISSUE THREAD

**Issue by scprek** [micronaut-projects/micronaut-openapi#1755]
> Is this user error? There appears to be a template for `@Format()` in https://github.com/micronaut-projects/micronaut-openapi/blob/6.12.x/openapi-generator/src/main/resources/templates/kotlin-micronaut/client/params/type.mustache

### Expected Behavior

Maybe 2 issues

1. Format
2. Pattern

## Format

Give this openapi spec

```json
{
  "paths": {
    "/api/{version}/unassigned-orders": {
      "get": {
        "operationId": "asdfasdf",
        "parameters": [
          {
            "name": "before",
            "in": "query",
            "description": "The date to search before (ATOM format)",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date-time"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns unassigned orders"
          }
        }
      }
    }
  }
}
```

I'd expect some default format string.

```kotlin
@QueryValue("before") @NotNull @Format(<some default for ZonedDateTime?>) before: ZonedDateTime,
```

## Pattern

Specifying a customer pattern in the `"pattern":` openapi spec like

```json
            "schema": {
              "type": "string",
              "format": "date-time",
              "pattern": "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
            }
```

Should add to the format, not a new `@Pattern` annotation?

```kotlin
@QueryValue("before") @NotNull @Format("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'") before: ZonedDateTime,
```

## Format

Format is empty

```kotlin
@QueryValue("before") @NotNull @Format("") before: ZonedDateTime,
```

## Pattern

But if I supply an openapi spec `"pattern":` it will create a `jakarta.validation.constraints;` `@Pattern` along with the empty format. 

```kotlin
@QueryValue("before") @NotNull @Pattern(regexp =  "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'") @Format("") before: ZonedDateTime,
```

### Steps To Reproduce

Query param (probably others path, normal variable, etc)

```
"type": "string",
"format": "date-time",
```

### Environment Information

- 6.12.0 openapi version

### Version

4.5.1

**Comment by altro3** [comment]
Fixed it here: https://github.com/micronaut-projects/micronaut-openapi/pull/1756

Check it, please

**Comment by scprek** [comment]
Looks good (know it got merged already). Thanks for the fastest turn around!
