### ISSUE TITLE
Optional path parameters are always set to required

### ISSUE THREAD

**Issue by dancarasco** [micronaut-projects/micronaut-openapi#184]
Optional path parameters {/example} are not respected in the yaml output.

![Screenshot from 2020-04-02 11-14-28](https://user-images.githubusercontent.com/49026110/78237493-4e5f2080-74d3-11ea-8940-d9ceabedd979.png)

This results in Swagger UI preventing any request with optional parameters to be made until all parameter requirements are met. It doesn't seem to be able to parse the optional syntax: {/x}

It seems Swagger expects all path parameters to be required:
https://swagger.io/docs/specification/describing-parameters/

>  The parameter name must be the same as specified in the path. Also remember to add required: true, because path parameters are always required.

**Comment by croudet** [comment]
Please show your controller method.

**Comment by dancarasco** [comment]
Interface:

![Screenshot from 2020-04-02 14-30-17](https://user-images.githubusercontent.com/49026110/78254904-7f991a00-74ee-11ea-9a8e-8e3208c3e225.png)

Implementation:

![Screenshot from 2020-04-02 14-30-37](https://user-images.githubusercontent.com/49026110/78254950-8e7fcc80-74ee-11ea-9307-c95b8bfbf5d7.png)

**Comment by croudet** [comment]
What is the version of micronaut-openapi?

**Comment by dancarasco** [comment]
> What is the version of micronaut-openapi?

_gradle.properties_
`micronautVersion=1.3.3`

_build.gradle_
```
annotationProcessor("io.micronaut.configuration:micronaut-openapi:1.4.2")
implementation("io.swagger.core.v3:swagger-annotations")
```

**Comment by croudet** [comment]
https://github.com/swagger-api/swagger-core/blob/ffd172052abb2578332592f9d743e4d73366d612/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/parameters/Parameter.java#L105
```java
public void setIn(String in) {
        if ("path".equals(in)) {
            this.required = true;
        }
        this.in = in;
 }
```
Required is always set to true when parameter is in path

**Comment by dancarasco** [comment]
@croudet This effectively makes this API unusable with Micronaut since optional path parameters are supported by the latter, and used quite commonly.

**Comment by graemerocher** [comment]
You can always add `@Parameter(required=false)` as a workaround to the parameter in question

**Comment by dancarasco** [comment]
> You can always add `@Parameter(required=false)` as a workaround to the parameter in question

Thank you!
