### ISSUE TITLE
Update OpenAPITolls Docs to send to This repo instead

### ISSUE THREAD

**Issue by scprek** [micronaut-projects/micronaut-openapi#1867]
### Issue description

Discord link https://discord.com/channels/1121511613250412714/1285993235482673172/1285993235482673172

This comes up enough in the community, should we get a PR in https://github.com/OpenAPITools/openapi-generator to say micronaut is not actively developed here? Spring is an option in their own for server and within the [Kotlin Client generators as library options.](https://openapi-generator.tech/docs/generators/kotlin).

Micronaut and [Quarkus](https://github.com/quarkiverse/quarkus-openapi-generator) Seem to be similar in having "forks"

**Comment by altro3** [comment]
@scprek https://github.com/OpenAPITools/openapi-generator/pull/20107
