### ISSUE TITLE
Adding Exceptions?

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-openapi#195]
Is it possible to have exceptions be added when using the `@Error` micronaut annotation?
Or is there another helper provided?

The goal would be to have the defined exceptions without having to add all of the typical openapi annotations and scheme annotations

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](https://stackoverflow.com/questions/tagged/micronaut).

You can also try with asking in [Gitter](https://gitter.im/micronautfw/).
