### ISSUE TITLE
micronaut.openapi.target.file usage and implications?

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-openapi#196]
What are the usage and implications of using micronaut.openapi.target.file?

Assuming it is used, it would seem to mean much of the other sections of the docs become irrelevant because the files are outside of the jar?

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](https://stackoverflow.com/questions/tagged/micronaut).

You can also try with asking in [Gitter](https://gitter.im/micronautfw/).
