### ISSUE TITLE
Add support for swagger generation of enabled Micronaut Security Endpoints

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-openapi#197]
Such as login, refresh, etc.

**Comment by alvarosanchez** [comment]
Duplicates #156

**Comment by andydoe19** [comment]
Hello @alvarosanchez If this is a duplicate, where can I find the answer please?

**Comment by alvarosanchez** [comment]
@andydoe19 see https://github.com/micronaut-projects/micronaut-openapi/issues/156#issuecomment-701951706

And please don't do cross-posting across several issues for the same question. Thanks!
