### ISSUE TITLE
Add openapi support for Jackson's JsonUnwrapped annotation

### ISSUE THREAD

**Issue by stottpaul** [micronaut-projects/micronaut-openapi#206]
We would like the generated openAPI schemas to honour the JsonUnwrapped annotation.

This support was added to swagger-core a couple of years ago via https://github.com/swagger-api/swagger-core/issues/1682

JsonUnwrapped allows us to encapsulate common property sets so they can be reused across multiple response schema types and flattened in the openApi schema spec.

**Comment by graemerocher** [comment]
Resolved by the awesome contributions of @croudet
