### ISSUE TITLE
Per-endpint security not output to openapi.yml

### ISSUE THREAD

**Issue by ftes** [micronaut-projects/micronaut-openapi#212]
I have a spec with a global/root `security` configuration.
OpenAPI 3 allows overriding `security` per endpoint.
But per-endpoint `security` definitions are not added to the `path` in the generated .yml file.

I define them on path level via an annotation on the controller method: `@Operation(security = [])`.

# Input
`Application.kt`
```kt
@OpenAPIDefinition(
    security = [
        SecurityRequirement(name = "bearerAuth", scopes = [])
    ]
)
@SecurityScheme(name = "bearerAuth", type = SecuritySchemeType.HTTP, scheme = "bearer", bearerFormat = "JWT")
object Application {
```

`UserController.kt`
```
@Secured(SecurityRule.IS_AUTHENTICATED)
@Controller("/users")
class UserController {
    @Post("/")
    @Operation(security = [])
    @Secured(SecurityRule.IS_ANONYMOUS)
    fun register(@Body user: UserWrite): UserRead {
        return toAPI(repo.save(toDomain(user)))
    }
```

# Output
```yml
openapi: 3.0.1
info:
  title: rentals
  version: "0.1"
security:
- bearerAuth: []
paths:
  /users:
    post:
      operationId: register
...
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

# Expected output
```yml
paths:
  /users:
    post:
      security: []
```

**Comment by croudet** [comment]
Lokks fine to me.
You define spec level security so it appears at spec level in the yaml.
See https://github.com/swagger-api/swagger-core/blob/26d72bf5fd2d54e5e514ddcf3861d125d2f95b42/modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/security/SecurityTest.java#L116

**Comment by ftes** [comment]
Thanks for looking into this so quickly.

I don't see any method/path level security annotation in the test case. That's where my problem lies:
`@Operation(security = [])`

https://swagger.io/docs/specification/authentication/
>Global security can be overridden in individual operations to use a different authentication type, different OAuth/OpenID scopes, or no authentication at all:

**Comment by ftes** [comment]
Thank you!
