### ISSUE TITLE
(some of the times) micronaut-openapi:1.5.0 generates swagger specifications for non-controller classes

### ISSUE THREAD

**Issue by JoaoRXFernandes** [micronaut-projects/micronaut-openapi#238]
There seems to be an issue with "io.micronaut.configuration:micronaut-openapi:1.5.0" where it generates swagger specifications for non-controller classes (i.e.: http client classes that make use of io.micronaut.http.annotation.Get and/or io.micronaut.http.annotation.Header annotations).

To replicate, create a micronaut solution with an http api controller, an http client class and run the following bash script:
```
for i in `seq 10` ; do
    echo "Starting new build..."
    ./gradlew clean assemble && cat ./build/classes/java/main/META-INF/swagger/*.yml | grep "<http client operation id>"
    echo
    echo
done
```

Hope that helps.

Let me know should you need any further details.

Thanks,

Joao

**Comment by csbiggar** [comment]
We are seeing this too, and it's non deterministic - sometimes it works (no spurious endpoints created for non controller classes) and sometimes it doesn't (spurious endpoints created)  , on successive builds with no code changes.

**Comment by graemerocher** [comment]
Would be helpful if someone attached an example application that reproduces the issue

**Comment by csbiggar** [comment]
Yep, I can't share my work one where we're seeing it but I'll see if I can recreate it with a sample project. Tricky due to the non-deterministic nature grr ... will hopefully update later or tomorrow

**Comment by graemerocher** [comment]
Thanks, any help would be appreciated

**Comment by croudet** [comment]
What version of micronaut-core are you using?

**Comment by csbiggar** [comment]
We're using 1.3.5
We've just upgraded to micronaut-openapi 1.5.1 (from 1.5.0) today and also as a workaround we've added `@Hidden` to the client endpoints to see if that forces it to ignore them .. we haven't had enough builds yet to see if it's made a difference

**Comment by croudet** [comment]
Is it with java or kotlin?

**Comment by csbiggar** [comment]
sorry, it's with Kotlin (1.3.61 at the moment)

**Comment by JoaoRXFernandes** [comment]
This was with micronaut-bom:1.3.5
Had to downgrade to io.micronaut.configuration:micronaut-openapi:1.4.5

Running the above from original report reproduces the issue every run.

Think the issue might be that the controller class level filter is not being applied anymore? (can't take credit for that)

Hope that helps,

Joao

**Comment by croudet** [comment]
Ok, I was able to reproduced the issue and to narrow down the problem.
Problem is in `micronaut-core`:
```java
public LoadedVisitor(TypeElementVisitor visitor,
                         JavaVisitorContext visitorContext,
                         GenericUtils genericUtils,
                         ProcessingEnvironment processingEnvironment) {
        this.visitorContext = visitorContext;
        this.visitor = visitor;
        Class<? extends TypeElementVisitor> aClass = 

        TypeElement typeElement = processingEnvironment.getElementUtils().getTypeElement(aClass.getName());
        if (typeElement != null) {
            List<? extends TypeMirror> generics = genericUtils.interfaceGenericTypesFor(typeElement, TypeElementVisitor.class.getName());
            classAnnotation = generics.get(0).toString();
            elementAnnotation = generics.get(1).toString();
        } else {
            Class[] classes = GenericTypeUtils.resolveInterfaceTypeArguments(aClass, TypeElementVisitor.class);
            if (classes != null && classes.length == 2) {
                classAnnotation = classes[0].getName();
                elementAnnotation = classes[1].getName();
            } else {
                classAnnotation = Object.class.getName();
                elementAnnotation = Object.class.getName();
            }
        }
    }
```

Sometimes `GenericTypeUtils.resolveInterfaceTypeArguments(aClass, TypeElementVisitor.class);` returns an empty array, some trace I put:
Good:
```
io.micronaut.openapi.visitor.OpenApiEndpointVisitor@71cc30ed - classes: [interface io.micronaut.management.endpoint.annotation.Endpoint, class java.lang.Object]
```
Bad:
```
 io.micronaut.openapi.visitor.OpenApiControllerVisitor@a2c4d6d - classes: []
```

So I will propos a PR:
in `GenericTypeUtils`:
```java
private static Set<Type> getAllGenericInterfaces(Class<?> aClass) {
        Set<Type> interfaces = new HashSet<>();
        return populateInterfaces(aClass, interfaces);
    }
```
I will replace `HashSet` with `LinkedHashSet` so that the most 'specialized' interface will be first.
In this case there are two times `TypeElementVisitor`:
```
[io.micronaut.inject.visitor.TypeElementVisitor<io.swagger.v3.oas.annotations.OpenAPIDefinition, java.lang.Object>,
io.micronaut.inject.visitor.TypeElementVisitor<C, E>]
```
and sometimes the most specific is first in the set, sometimes not.

**Comment by csbiggar** [comment]
Oh brilliant, well done! (Doubly pleased as now I don't have to come up with an example project ;) 

Will look out for the release with the fix. Many thanks
