### ISSUE TITLE
Add path ordering to open-api generated spec

### ISSUE THREAD

**Issue by stottpaul** [micronaut-projects/micronaut-openapi#249]
We would like to be able to move our deprecated paths to the bottom of the swagger-ui pages, however there does not appear to be a way to control the ordering of the paths within the generated open-api specification.   In fact it appears to be non-deterministic at present as the ordering changes frequently upon build.

**Comment by croudet** [comment]
Rapidoc has `sort-tags` and `sort-endoints-by` options.
https://mrin9.github.io/RapiDoc/api.html
