### ISSUE TITLE
Infer Operation summary and description attributes from Javadoc

### ISSUE THREAD

**Issue by pditommaso** [micronaut-projects/micronaut-openapi#265]
The Micronaut support is very convenient because it allows the generation of OpenAPI definition from the defined controller classes.

The ability to generate the proper API parameters documentation from the [Javadoc annotation allows the saving of a lot of duplicate coding](https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#controllersAndSwaggerAnnotations).

However, in order to provide the operation *summary* and *description* it is required the use of the swagger `@Operation`  annotation, by using which MN does not fetch anymore the parameter description from the Javadoc, vanishing the benefit described above. 

This enhancement proposes to infer the operation *summary* and *description* attributes from the Javadoc comment in the same manner as done for the parameters, with the convention to use the first line as the summary attribute and any following text as the value for the description attribute.

**Comment by scprek** [comment]
@pditommaso I ran into the same issue, but also noticed weirdness around parameter descriptions. See my post here. https://github.com/micronaut-projects/micronaut-openapi/issues/134#issuecomment-777007210

**Comment by scprek** [comment]
Note that `@Operation` with summary alone works fine if there are no javadocs WITH `@param` before it.

**Comment by graemerocher** [comment]
I think the correct thing to do would be to plug something like https://github.com/chhorz/javadoc-parser into the javadoc parsing instead of the rather dumb regex approach used now and to support this better
