### ISSUE TITLE
is request and response content of type protof buf supported

### ISSUE THREAD

**Issue by SushmaReddyLoka** [micronaut-projects/micronaut-openapi#273]
Is it possible to generate open api spec when request and response content are of type protof buf ?

**Comment by croudet** [comment]
Generation of spec should work for protobuf.

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](https://stackoverflow.com/questions/tagged/micronaut).

You can also try with asking in [Gitter](https://gitter.im/micronautfw/).
