### ISSUE TITLE
Endpoints in Swagger UI are not expandable & a loading spinner is shown

### ISSUE THREAD

**Issue by swaechter** [micronaut-projects/micronaut-openapi#292]
### Steps to Reproduce

1.) Generate a Micronaut application with the OpenAPI integration
2.) Add a hello world endpoint
3.) Enable Swagger YML/Swagger UI and serve them via static router configuration
4.) Start the app and open Swagger UI
5.) Click on the endpoint and see a loading spinner that never stops spinning. The endpoint content is not shown and can't be triggered

### Expected Behaviour

5.) Being able to expand and trigger the endpoint

### Actual Behaviour

5.) Loading spinner that never stops + the following messages in Chromium 83:

Note: Sometimes I receive a SameSite origin warning that was reenabled in Chrome 80+ (Maybe related). In addition another Micronaut project that is half a year old stopped working too (So this doesn't look like a regression or so).

```
DevTools failed to load SourceMap: Could not load content for https://unpkg.com/swagger-ui-themes@3.0.0/themes/3.x/swagger-ui.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
layout.js:99 Warning: escaping deep link whitespace with `_` will be unsupported in v4.0, use `%20` instead.
(anonymous) @ isEventSupported.js:18
(anonymous) @ swagger-ui-bundle.js:1
(anonymous) @ deep-extend.js:30
(anonymous) @ isEventSupported.js:18
r @ swagger-ui-bundle.js:91
(anonymous) @ swagger-ui-bundle.js:91
h @ swagger-ui-bundle.js:91
Ur @ swagger-ui-bundle.js:91
window.onload @ swagger-ui:45
load (async)
(anonymous) @ swagger-ui:20
```

### Environment Information

- **Operating System**: Debian Testing & Alpine Container
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11

### Example Application

Live link: https://obscure-depths-17784.herokuapp.com/swagger-ui
Source link: https://github.com/swaechter/micronaut-openapiissue

**Comment by ameet123** [comment]
This doesn't load on local or even when I deploy remotely in the cloud.
micronaut 2.0.0, java amazon coretto 11. gradle 6.5.1 as well as 6.4.1
I tried with all versions of java 8, 11, 14. no dice.
I tried with micronaut: 1.3.4 as well. same issue

**Comment by graemerocher** [comment]
Weird seems to be a bug in Swagger UI unrelated to Micronaut. 

It is actually manifesting at https://snapshot.micronaut.io/swagger/views/swagger-ui/index.html

In the meantime suggest using RAPI doc which works fine https://snapshot.micronaut.io/swagger/views/rapidoc/index.html

**Comment by graemerocher** [comment]
Seems to be a bug in Swagger UI https://github.com/swagger-api/swagger-ui/issues/6254

**Comment by swaechter** [comment]
@graemerocher  Thanks a lot for digging into this. I checked the issue tracker a few hours ago.

Unrelated and maybe more a feature request: Would it be possible to rely on Webjars/embedded JS/CSS files? Two reasons:

1.) At the moment the Swagger integration requires an internet connection with a working DNS. Many of our customers have restricted production networks and the integration breaks (No connection to the CDN)

2.) Issues like the current one (I mean: Why does the issue happen now? Is it browser related? CND related? Is the version not fixed? --> Deterministic behaviour)

Best,
Simon

**Comment by graemerocher** [comment]
It would be better yes. PRs are of course welcome

**Comment by croudet** [comment]
Seems to be fixed: https://github.com/swagger-api/swagger-ui/issues/6249
https://github.com/swagger-api/swagger-ui/releases

**Comment by swaechter** [comment]
Yes, the problem is fixed (Micronaut uses the latest Swagger UI bundle)
