### ISSUE TITLE
Building OpenAPI for multiple content types in separate methods results in one overriding the other

### ISSUE THREAD

**Issue by jaksah** [micronaut-projects/micronaut-openapi#303]
Building the OpenAPI spec for multiple content types in separate methods results in that only one of them is present in the output. For example.

```
@Controller("/upload")
public class UploadController {
    @Consumes(MediaType.APPLICATION_JSON)
    @Post("/")
    HttpResponse uploadByUrl(@Body RemoteUpload upload) { ... }
        
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Post("/")
    HttpResponse uploadByFile(CompletedFileUpload file) { ... }
}

public class RemoteUpload { 
    private URL url;
    ...
}
```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
1. Create a controller with two routes with the same path but that consumes different media types.
2. Generate openapi spec

### Expected Behaviour

Both media types should be represented in the generated openapi spec.

### Actual Behaviour

only one of the media types is added to the openapi spec

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.2.9
- **JDK Version:** Java 11

### Example Application

I have forked the repo and added a test case that fails: https://github.com/jaksah/micronaut-openapi/commit/2578d2f376e03be52b0be0a539d0048c6bddd5fb

**Comment by ilopmar** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-openapi/pull/306
