### ISSUE TITLE
[maven] Swagger-UI is not generated

### ISSUE THREAD

**Issue by Adito5393** [micronaut-projects/micronaut-openapi#314]
The swagger file `swagger.yml` is generated in `META-INF/swagger`, however the swagger-ui not.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Generate a new project [here](https://micronaut.io/launch/) with:
   - application type (v2.0.1)
   - Java 11 & Java language
   - Build Maven & JUnit
2. Run mn:run maven goal
3. Check target folder and there is no 'META-INF/swagger/views/swagger-ui'

### Expected Behaviour

The `application.yml` looks like this:

```bash
micronaut:
  application:
    name: helloWorldLaunch
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
```
The `pom.xml` important info:

```bash
-----
<dependencies>
  <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-annotations</artifactId>
      <scope>compile</scope>
    </dependency>
-----------------
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerArgs>
            <arg>-Amicronaut.processing.group=helloLaunch</arg>
            <arg>-Amicronaut.processing.module=hello-world-launch</arg>
            <arg>-J-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop</arg>
          </compilerArgs>
-----------------
```

### Actual Behaviour

No views are generated and also the browser is not showing anything at `http://localhost:8080/swagger-ui`

### Environment Information

- **Operating System**: Win10
- **Micronaut Version:** 2.0.1 & latest openapi version= 1.5.2
- **JDK Version:** TODO

### Example Application

If you can't reproduce this issue with the official launcher than I will prepare a Github project.

**Comment by Adito5393** [comment]
The files got generated with the `fork` flag set to `true` BEFORE the `<compilerArgs>`:

```bash
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerArgs>
            <arg>-Amicronaut.processing.group=helloLaunch</arg>
            <arg>-Amicronaut.processing.module=hello-world-launch</arg>
            <arg>-J-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop</arg>
          </compilerArgs>
```

**Comment by rolox05** [comment]
This solution is not working can you provide more information ? I'm in the same situation as @Adito5393, you could get it working?

**Comment by Adito5393** [comment]
Highly depends on how you set up your project.... try using their [launcher](https://micronaut.io/launch/) and select the feature "**openapi**" and compare their pom.xml with yours. (or the build.gradle file)

I found that the [docs](https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html) had enough info to help me, I just did not pay attention to all the details. 

Reply with more details on the errors or what do you expect to happen and I can try to help you out to debug it.

**Comment by szachmati** [comment]
In docs there is no info that default static-resources should be enabled. This config should work
```
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:swagger
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
```

**Comment by cprashantgupta** [comment]
The issue seams to be still there, as soon as one add context path to micronaut application. 

`micronaut:
  application:
    name: vcart
  server:
    port: 8080
    cors:
      enabled: true
    context-path: /vcart
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        enabled: true
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /vcart/swagger-ui/**
      web:
        paths: classpath:web
        mapping: /**
`

http://localhost:8080/vcart/swagger-ui
![image](https://user-images.githubusercontent.com/43907358/205054315-a168af7a-21a3-4860-b814-6047791f7e9a.png)
