### ISSUE TITLE
Body schema doesn't include extra method parameters

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-openapi#318]
It's possible to define something like this:

```
   @Post("/v1/my-ep")
    public Result myEp(String myId, @Body @Valid MyBody myBody) {
        return ...
    }
```
And receive `{"myId": 123, ....}` then `myId` is propagated as a method parameter.

Unfortunately `myId` is not included in the API specification.

I think it should generate extra body schema:

```
MyEpBody:
      allOf:
      - $ref: '#/components/schemas/MyBody'
      - required:
        - myId
        type: object
        properties:
          myId:
            minLength: 1
            type: string
```

**Comment by graemerocher** [comment]
Wow I am surprised this works, seems to be there would be a lot of problems to disambiguate what belongs to the body and what doesn't 🤔

**Comment by dstepanov** [comment]
@graemerocher Actually it's a pretty good feature. I don't see any problems here, parameters are just extracted from the incoming body and if the body also defines `myId` it will be included there as well.
