### ISSUE TITLE
Support Jackson's @JsonNaming and @JsonProperty

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-openapi#319]
It would be nice if schema models were generated according to `@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)` and `@JsonProperty`

**Comment by graemerocher** [comment]
I thought `@JsonProperty` was already handled If not I think there should be an annotation mapper that maps it to `@Bindable(value=..)` in case we want to support other annotation sets

**Comment by dstepanov** [comment]
I might be wrong about `@JsonProperty` I checked the sources briefly to check if it's supported.
