### ISSUE TITLE
Why are Javadoc comments added to summary AND description?

### ISSUE THREAD

**Issue by Panthaaaa** [micronaut-projects/micronaut-openapi#323]
I tried to add some documentation using Javadoc to our spec and was quite surprised that method javadocs is added to summary AND description. I couldn't find any reasoning behind that behaviour, which is coded here:
https://github.com/micronaut-projects/micronaut-openapi/blob/b8923df234876231fb304cf7ded7e940512e0665/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java#L676-L690

As the summary should be short and the description can be as long as necessary I would propose to use the first sentence for the summary (either ended by . or newline) and add the rest or complete text as description.

**Comment by graemerocher** [comment]
Seems like a good idea, would you like to send a PR?

**Comment by Panthaaaa** [comment]
I just saw #265 which proposes the exact same approach. Therefore I would link both tickets and make a PR which closes both.

**Comment by alvarosanchez** [comment]
Duplicate of #265
