### ISSUE TITLE
Unable to expand properties

### ISSUE THREAD

**Issue by alberto-pelosi** [micronaut-projects/micronaut-openapi#337]
Hi,

I'm using micronaut-openapi v 1.5.2

In the documentation (https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#configuration) there is an example about how to expand properties, but it doesn't seem to work.

I have defined openapi.properties file and put it in src/main/resources

```micronaut.openapi.expand.openapi.description=A nice API```

This is the main class:

```
package com.codermine.cookbook;

import io.micronaut.runtime.Micronaut;
import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.info.*;

@OpenAPIDefinition(
        info = @Info(
                title = "cookbook",
                version = "0.0",
                description = "${openapi.description}",
                license = @License(name = "WTFPL", url = "xyz"),
                contact = @Contact(url = "https://contact-url.com", name = "Micronaut Supporter", email = "helpdesk@mail.com")
        )
)
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class, args);
    }
}
```

At runtime, description value is "${openapi.description}", but the expected value is "A nice API"

**Comment by graemerocher** [comment]
According to https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#configuration it has to be in your project root

**Comment by alberto-pelosi** [comment]
Ok, it works. 
Thank you!
