### ISSUE TITLE
Add support for @RequestBean

### ISSUE THREAD

**Issue by asodja** [micronaut-projects/micronaut-openapi#345]
With Micronaut 2.0.0 there is new Bindable annotation `@RequestBean`. It looks like it does not work out of the box with OpenApi.

https://docs.micronaut.io/latest/guide/index.html#binding

`@RequestBean` maps bindable values to object. So object would probably need to be unwrapped in to OpenApi schema somehow.

**Comment by morki** [comment]
The same fix is needed for "exploded operator" on get queries, example from documentation:

```java
@Get("/bookmarks/list{?paginationCommand*}")
public HttpStatus list(@Valid @Nullable PaginationCommand paginationCommand) {
    return HttpStatus.OK;
}
```

Now they are presented as object type.
