### ISSUE TITLE
No feature for swagger-java

### ISSUE THREAD

**Issue by perty** [micronaut-projects/micronaut-openapi#349]
Following the documentation here: https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html .

Creating an app does not work as described.

### Steps to Reproduce

1. > mn create-app my-openapi-app --features swagger-java
| Error The requested feature does not exist: swagger-java
2. > mn --version
Micronaut Version: 2.0.3
3. > mn create-app -h | grep swagger
>

### Expected Behaviour

A directory with an micronaut app that has support for swagger.

### Actual Behaviour

An error message

### Environment Information
> java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

Mac

**Comment by ilopmar** [comment]
This is again another doc issue. The name of the feature is now `openapi` and it doesn't matter if you use Java, Groovy or Kotlin.

One hint. If you are not sure about the doc of something doesn't work, my advice is going to https://micronaut.io/launch/ and generate the project there.
