### ISSUE TITLE
Micronaut Built-In Endpoints - cache

### ISSUE THREAD

**Issue by natka1130** [micronaut-projects/micronaut-openapi#353]
referring to the following documentation (https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#endpoints) I tried to enable the appropriate endpoints.

It turns out that only the following are available and visible in the swagger:

endpoints.routes.class = io.micronaut.management.endpoint.routes.RoutesEndpoint
endpoints.beans.class = io.micronaut.management.endpoint.beans.BeansEndpoint
endpoints.health.class = io.micronaut.management.endpoint.health.HealthEndpoint
endpoints.loggers.class = io.micronaut.management.endpoint.loggers.LoggersEndpoint
endpoints.refresh.class = io.micronaut.management.endpoint.refresh.RefreshEndpoint

What about the cache endpoint? Is there any possibility that it could also be available?

**Comment by croudet** [comment]
It should work for Cache endpoint. Just add an entry with the proper class name.

**Comment by alvarosanchez** [comment]
Also make sure to add `io.micronaut.cache:micronaut-cache-management` as a dependency.
