### ISSUE TITLE
Is there any Api gateway swagger implementation example.

### ISSUE THREAD

**Issue by anandjaisy** [micronaut-projects/micronaut-openapi#357]
The open API with swagger UI for each microservice is fine, is there any example of API gateway swagger implementation?

Something similar to spring gateway https://spring.io/projects/spring-cloud-gateway

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](https://stackoverflow.com/questions/tagged/micronaut).

You can also try with asking in [Gitter](https://gitter.im/micronautfw/).
