### ISSUE TITLE
Add support for @Schema(accessMode = ...) in classes

### ISSUE THREAD

**Issue by tcrespog** [micronaut-projects/micronaut-openapi#363]
It would be useful to take into account the [`accessMode`](https://docs.swagger.io/swagger-core/v2.1.5/apidocs/io/swagger/v3/oas/annotations/media/Schema.html#accessMode--) element of `@Schema` in classes.

This way some fields could be specified only for requests or responses. For instance:
```java
@Schema(name="MyPet", description="Pet description")
class Pet {
    private int age;
    private String name;

    public void setAge(int a) {
        age = a;
    }

    @Schema(description="Pet age", maximum="20", accessMode = Schema.AccessMode.WRITE_ONLY)
    public int getAge() {
        return age;
    }

    public void setName(String n) {
        name = n;
    }

    @Schema(description="Pet name", maxLength=20, accessMode = Schema.AccessMode.READ_ONLY)
    public String getName() {
        return name;
    }
}
```
Given the definition above: `age` would only appear wherever `Pet` is part of a request body, whereas `name` would only appear wherever `Pet` is part of a response body.

**Comment by LajosPolya** [comment]
This is defined in the OpenAPI spec [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schemaObject). How come this wasn't implemented by Micronaut?

I'd really like to see this feature as well.

**Comment by graemerocher** [comment]
Nobody got round to it yet, but PRs welcome!

**Comment by LajosPolya** [comment]
@graemerocher I've forked the repo, and I'm trying to replace my dependency with the source code but I can't find the micronaut-openapi jars in my module settings in IntelliJ. How can I replace compile time dependencies so I can debug the code?

**Comment by LajosPolya** [comment]
@graemerocher I forked the repo, but when I try to run :spotlessApply but it converts all line endings to CRLF making the build fail. Can you help me out?

**Comment by LajosPolya** [comment]
@graemerocher  Can you please take a look at my PR?
