### ISSUE TITLE
Groovy POGO Schemas missing

### ISSUE THREAD

**Issue by sjrd218** [micronaut-projects/micronaut-openapi#373]
It appears that the generation of schema information for Groovy POGOs is not working

### Steps to Reproduce

1. Create a project from Micronaut launch that includes the openapi feature and uses Groovy
2. Create a POGO and annotate it with the Swagger Schema annotation
3. Build the project
4. Look at the generated open api file and note that there are no entries for the POGO that was previously created

### Expected Behaviour

The generated open api file should contain the schema information for the POGO

### Actual Behaviour

No schema info in open api file

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 2.1.3
- **JDK Version:** 1.8 and 11 tested

### Example Application

https://github.com/sjrd218/openapi-groovy-gen

**Comment by ilopmar** [comment]
This is not a bug, it works as expected. Just for the fact that you have classes (POGOs or any other class) on your project doesn't mean that you want to expose them as part of you public Open API definition. If you create a controller that uses those POGOs, then they will included in the openapi spec.
