### ISSUE TITLE
The @ArraySchema annotation is not interpreted correctly

### ISSUE THREAD

**Issue by henriquelsmti** [micronaut-projects/micronaut-openapi#384]
Currently the Micronaut is not generating the specification correctly when using @ArraySchema annotation

When adding @ArraySchema to @ Content.array, the type of the array item is not added to the yaml file.
Ex 1:
Controller
    
    @ApiResponse(
        content = @Content(
            array = @ArraySchema(
                    schema = @Schema(implementation = Bacon)
                )
        )
    )
    @RequestBody(
        content = @Content(
            array = @ArraySchema(
                    schema = @Schema(implementation = Bacon)
               )
            )
	)

    @Post('/single')
    Single<List<Bacon>> singleExemple(@Body Single<List<Bacon>> single) {
        return single.map((it) -> it + [new Bacon(name: 'banana')])
    }

yaml:

    /arrayschema/single:
      post:
        operationId: singleExemple
        parameters: []
        requestBody:
          content:
            application/json:
              schema:
                type: array
          required: true
        responses:
          default:
            content:
              application/json:
                schema:
                  type: array

Ex 2:
Controller:,

        @Get('/streamedFileExemple')
            StreamedFile streamedFileExemple(){
                InputStream inputStream = new ByteArrayInputStream('[{"name":"banana"}]'.bytes)
                new StreamedFile(inputStream, MediaType.APPLICATION_JSON_TYPE)
        }

yaml:

        /arrayschema/streamedFileExemple:
            get:
              operationId: streamedFileExemple
              parameters: []
              responses:
                default:
                  content:
                    application/json:
                      schema:
                        type: array

I noticed that when removing @ApiResponse and @RequestBody in cases using Single or Observable, the type of the array item added as object

### Expected Behaviour

Adicionar o tipo do item no arquivo yaml

### Actual Behaviour

The item type is omitted or added as an object

### Environment Information

- **Operating System**: Kubuntu 18.4
- **Micronaut Version:** 2.1.3
- **JDK Version:** 11

### Example Application

https://github.com/henriquelsmti/openapi-micronaut-generation

**Comment by henriquelsmti** [comment]
Note that io.micronaut.openapi.visitor.OpenApi ArraySchema Spec is failing on the master

**Comment by henriquelsmti** [comment]
Performing some tests, I found that the problem happens only in OpenJ9, in HotSport it works normally

**Comment by henriquelsmti** [comment]
Apparently Jackson doesn't render yaml correctly in OpenJ9.
I don't know if it makes sense to keep this issue open.

**Comment by henriquelsmti** [comment]
Apparently BeanMap does not return all properties when running on OpenJ9
![image](https://user-images.githubusercontent.com/9632578/99525888-3a403480-2979-11eb-877d-de84d3155d5f.png)

**Comment by croudet** [comment]
Seems related to https://github.com/micronaut-projects/micronaut-views/issues/4
