### ISSUE TITLE
name property from @Schema annotation on field level is not picked up in generated swagger yml

### ISSUE THREAD

**Issue by JacobAae** [micronaut-projects/micronaut-openapi#4]
When the @Schema annotation is used on class level, the name="xxx" setting is reflected in the generated swagger yml file. But when @Schema is used on a field level, it is not.

Project that shows this is available here: https://github.com/JacobAae/swaggerdemo-for-schema-issue

The `@RequestBody Pet` class `petName` field has these annotations

```
@Schema(
            description = """The name of the pet""",
            defaultValue = "",
            name = "pet_name", // Ignored - bug I think!
            title = "The name of the pet - for demo",
            example = "Kitty"
    )
    @JsonProperty("pet_name")
    String petName
```
And the generated file has:

```
components:
  schemas:
    Pet Class:
      type: object
      properties:
        petName:
          title: The name of the pet - for demo
          type: string
```

Expected behavior was the property petName should have been `pet_name`

**Comment by StephenOTT** [comment]
for future reference, for this to work with kotlin, you need to have `@field:Schema(name = "field_name")`.  If you just have `@Schema` without the target, it will not update the property names in the yaml/swagger
