### ISSUE TITLE
Generate endpoints and schemas in the same order into swagger.yml

### ISSUE THREAD

**Issue by adamkobor** [micronaut-projects/micronaut-openapi#409]
We are using the generated OpenAPI spec in a custom manner, which means that the generated YAML is also included in our applications' repository to track the changes of it. This means that every time Micronaut regenerates the file, a custom Gradle task updates it in our repo as well. Because the generator doesn't order the endpoints and schemas by their name, two consequent run can end up in YAMLs that differ in the order of endpoints and schemas only.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a controller with multiple endpoints that have different paths (i.e. `/route-one` and `/route-two`)
2. Let Micronaut to generate the OpenAPI specs (swagger.yml) for the application again and again

### Expected Behaviour

The endpoints and schemas in the generated YAML should be in the same order for every run.

### Actual Behaviour

The endpoints and schemas are ordered randomly between different runs.

### Environment Information

- **Operating System**: MacOS Big Sur
- **Micronaut Version:** 2.2.1
- **JDK Version:** 11

I would be happy to contribute and fix this issue, but I'm quite unsure about where should I start it. I was browsing the source code, and it seems that sorting the endpoints (paths) would also solve the order of schemas implicitly.

**Comment by graemerocher** [comment]
Contributions welcome! Good place to start is to look at the existing tests

The file itself is written here https://github.com/micronaut-projects/micronaut-openapi/blob/master/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java#L479

**Comment by dstepanov** [comment]
We have the same problem and I think it's caused by Javac processing not having consistent order. We have solved it by sorting yaml in Gradle, it looks ugly but works.

**Comment by asodja** [comment]
@adamkobor can you maybe test if https://github.com/micronaut-projects/micronaut-openapi/pull/433 fixes the issue for you?
