### ISSUE TITLE
doc not generating for security endpoints

### ISSUE THREAD

**Issue by pavan2sunny** [micronaut-projects/micronaut-openapi#41]
yml is not generated for security endpoints

**Comment by puneetbehl** [comment]
It seems to be working fine, see the following example application:
[testapp.zip](https://github.com/micronaut-projects/micronaut-openapi/files/3829963/testapp.zip)

**Comment by pavan2sunny** [comment]
when i said yml not generatd for security endpoints i meant  default login / oauth api endpoints where not generated in the yml like i cont see them

**Comment by puneetbehl** [comment]
Please see [Merging Schemas](https://micronaut-projects.github.io/micronaut-openapi/snapshot/guide/index.html#mergingSchemas)
