### ISSUE TITLE
OpenAPI yaml has incorrect syntax for basic auth

### ISSUE THREAD

**Issue by hheberhardt** [micronaut-projects/micronaut-openapi#43]
Hi!

With the following OpenAPI definition:

```
@OpenAPIDefinition(
  info = Info(
    title = "Any-Service",
    version = "1.0",
    description = "Any Service API"
  ),
  security = [SecurityRequirement(name = "basicAuth")]
)
@SecuritySchemes(
  value = [SecurityScheme(name = "basicAuth", type = SecuritySchemeType.HTTP, scheme = "basic")])
```

This part of the open-api-specification-yaml is created:
```
openapi: 3.0.1
info:
  title: Any-Service
  description: Any Service API
  version: "1.0"
security:
- name:
  - basicAuth
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
```
I entered this created yaml in https://editor.swagger.io/ but there you can easily check, that the security part is not read correctly.

If i compare with the specification on https://swagger.io/docs/specification/authentication/basic-authentication/, the generated yaml should look like:
```
openapi: 3.0.1
info:
  title: Any-Service
  description: Any Service API
  version: "1.0"
security:
  - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
```

A workaround for me is for now, giving the SecuritySchema the name "name", because then it's correctly parsed from swagger-ui ... but hope this can be fixed easily to support multiple security schema.

Problem seems to be the yaml-serialization. The "- name" property must not be printed out.

**Comment by dstepanov** [comment]
It's fixed in the latest version 1.2.0

**Comment by hheberhardt** [comment]
Hi!
I have updated the dependency manually and you are right. In ApplicationClassVisitor it seems to be fixed, but on 'operation-level' this issue seems still be there:

```
@Post("/any")
  @Operation(
    description = "ding dong",
    security = [SecurityRequirement(name = "basicAuthentication")])
```
if i put this on a function, i would also assume, that in generated yaml this is correctly interpreted.

but in this case, i got:
```
/any:
    post:
...
      security:
      - name:
        - basicAuthentication
```

but should be:

```
/any:
    post:
...
      security:
        - basicAuthentication[]
```

Could you please verify?
Thanks.

**Comment by dstepanov** [comment]
I have only tested `@SecurityRequirement` on a method directly.
This should work:
```
@Post("/any")
@SecurityRequirement(name = "basicAuthentication")
@Operation(description = "ding dong")
```

**Comment by hheberhardt** [comment]
Thanks, yes! that works! Maybe you can also intergrate this to '@Operation'  annotation processing in next release - but i can work so far.
