### ISSUE TITLE
Request body generated in Swagger YAML for POST/PUT with no body

### ISSUE THREAD

**Issue by HoaBo** [micronaut-projects/micronaut-openapi#44]
This is to reopen https://github.com/micronaut-projects/micronaut-core/issues/1200

I found the related code here https://github.com/micronaut-projects/micronaut-openapi/blob/23409f4537aa64f07f0558a6ca9c92e797536127/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java#L435

If all the body parameters are skipped, e.g. all of them are hidden parameters, then the body will be empty. In this case, I think body should not be required as in
https://github.com/micronaut-projects/micronaut-openapi/blob/23409f4537aa64f07f0558a6ca9c92e797536127/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java#L459

Consequences (not related to this repo): when I use codegen to generate client code from the generated swagger.yml, it requires me to pass in an empty object although it shouldn't

**Comment by jaecktec** [comment]
I think this bug still persists:

when you have a post with a parameter (not a body) like so:
```
  @Post("/a/{foo}/bar")
  @Status(HttpStatus.NO_CONTENT)
  suspend fun bar(@PathVariable(name = "foo") foo: String) {
    service.bar(foo)
  }
```
it generates:
```
  /a/{foo}/bar:
    post:
      operationId: bar
      parameters:
      - name: foo
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                p0:
                  type: string
                  nullable: false
```

**Comment by swaechter** [comment]
@graemerocher @jaecktec Somehow I ran into the same problem for POST and PUT. Is there a workaround to generate an empty request body, e.g via @Content / @Schema?

```java
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Post;

@Controller("/api")
public class SampleController {

    @Post("/execute")
    public void executePostAction() {
        System.out.println("Hello world!");
    }
}
```

Produces:

```
  /api/execute:
    post:
      operationId: executePostAction
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        "200":
          description: executePostAction 200 response
```

**Comment by jaecktec** [comment]
No, but there is still an open issue here: #402
