### ISSUE TITLE
Does not handle multipart form data as expected; regression?

### ISSUE THREAD

**Issue by RobynDalgleish** [micronaut-projects/micronaut-openapi#443]
### Steps to Reproduce

1. Create a basic endpoint that takes multipart form data, and returns a non-200 status code, e.g. 201
2. Enable the OpenApi annotation processor
3. CompileJava to generate docs

### Expected Behaviour

- The multipart form body has all of its parts documented or at least visible when the @Part annotation is used
- There are no added response codes even when having not added @Status(HttpStatus.CREATED) OR this being necessary is documented
- Shows name of part as defined on the part annotation

Example of the generated YAML output:

```yml
openapi: 3.0.1
info:
  title: swaggerDocs
  version: "0.0"
paths:
  /:
    post:
      summary: summary
      description: description
      operationId: postMultipartForm
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties: 
                part: 
                  type: string
                  format: binary
        required: true
      responses:
        "201":
          description: it was created
```

### Actual Behaviour

- The multipart form body has no properties defined on it (when the @Part annotation is passed as a parameter)
- There is an unspecified status response of 200, which we can only disabled by using @Status(HttpStatus.CREATED), and this is not documented

Example of the generated YAML output:

```yml
openapi: 3.0.1
info:
  title: swaggerDocs
  version: "0.0"
paths:
  /:
    post:
      summary: summary
      description: description
      operationId: postMultipartForm
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
        required: true
      responses:
        "201":
          description: it was created
        "200":
          description: postMultipartForm 200 response
          content:
            application/json:
              schema:
                type: string
```

### Environment Information

- **Operating System**: macOS Mojave
- **Micronaut Version:** 2.2.3
- **JDK Version:** 14

### Example Application

Application was generated using Micronaut Launch, and enabling the OpenApi feature

- [link to github repository with example that reproduces the issue](https://github.com/RobynDalgleish/swaggerDocs)

**Comment by scprek** [comment]
See the same thing. The `@Part` annotation is screwing up the spec.

Without `@Part` using the parameter name as-is
```yaml
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - partName1
              - partName2
              type: object
              properties:
                partName1:
                  type: string
                  format: binary
                partName2:
                  type: string
                  format: binary
        required: true
```


With `@Part` to modify the name to snake case.

```yaml
 parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
        required: true
```
