### ISSUE TITLE
missing version in pom.xml for dependency micronaut-http

### ISSUE THREAD

**Issue by kristofvb** [micronaut-projects/micronaut-openapi#444]
### Steps to Reproduce

1. using Micronaut Launcher create a new project with feature open-api and build tool maven
2. download and unzip demo
3. run mvn package

### Expected Behaviour

Maven build expected to succeed.

### Actual Behaviour

There is a warning
[WARNING] Invalid POM for io.micronaut.openapi:micronaut-openapi:jar:2.3.0, transitive dependencies (if any) will not be available, enable debug logging for more details

When running with mvn -X package you also get this line
[ERROR] 'dependencies.dependency.version' for io.micronaut:micronaut-http:jar is missing. @ line 31, column 17

### Environment Information

- **Operating System**: macos
- **Micronaut Version:** 2.3.0
- **JDK Version:** JDK 11

**Comment by alvarosanchez** [comment]
This was caused by https://github.com/micronaut-projects/micronaut-build/pull/77.

It needs a new release.
