### ISSUE TITLE
OpenAPI YAML file sorting POJO properties alphabetically

### ISSUE THREAD

**Issue by jacobmims** [micronaut-projects/micronaut-openapi#467]
This is likely a result of #433. While it is now consistent, this can result in awkward OpenAPI docs, where alphabetical sorting does not match the expected order of the properties.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an object with properties not in alphabetical order
2. Generate the OpenAPI spec file
3. Properties in the spec file are in alphabetical order

### Expected Behaviour

Option 1: Unless specified, properties should be sorted in definition order. 

Option 2: Alphabetical is the default sort order, but provide support for `@Order` annotation.

### Actual Behaviour

Fields are ordered alphabetically regardless of definition order or usage of `@Order` annotation. 

### Environment Information

- **Operating System**: macOS 10.15.7
- **Micronaut Version:** 2.3.2
- **JDK Version:** 11.0.9.hs

### Example Application

[Example Repo](https://github.com/jacobmims/property-naming)

**Comment by graemerocher** [comment]
hmm yeah not sure what we can do about this, the fix for #433 isn't easy to customise

**Comment by asodja** [comment]
Yeah, maybe it's was not the best idea to modify ObjectMapper...

Original issue was, that paths and schemas had different order on different runs. So maybe it would be enough to just sort these two before putting out yaml. Smth like:
```
  // Sort paths
  Map<String, PathItem> sortedPaths = new TreeMap<>(openAPI.getPaths());
  openAPI.getPaths().clear();
  sortedPaths.forEach((k, v) -> openAPI.getPaths().put(k, v));
  
  // Sort schemas
  Map<String, Schema> schemas = openAPI.getComponents().getSchemas();
  openAPI.getComponents().setSchemas(new TreeMap<>(schemas));
  
  writeYaml(openApi);
```

**Comment by jacobmims** [comment]
That sounds like a good compromise @asodja. I experienced the issue with the paths and schemas, so this fixed that issue beautifully. Impacting the properties seems like an unintended side effect, so if we can isolate the sorting to the paths/schemas, that would be the best of both.

**Comment by asodja** [comment]
@jacobmims Could you maybe try my fix? How you can test it:
```
git clone git@github.com:asodja/micronaut-openapi.git
git checkout CONDISTENT-ORDER-V2 (hehe nice typo)
./gradlew publishToMavenLocal
add mavenLocal() to your repositories and set
annotationProcessor("io.micronaut.openapi:micronaut-openapi:2.4.0-SNAPSHOT") 
```

**Comment by graemerocher** [comment]
If it is still an issue please re-open

**Comment by jacobmims** [comment]
@asodja I just wanted to follow up: it looks like it's working great. Thank you for jumping on this so quickly!

**Comment by swaechter** [comment]
Hey @asodja I tried to build your project and reference it in my OpenAPI sample repo (https://github.com/swaechter/openapiproblems).

```
git clone https://github.com/asodja/micronaut-openapi.git
cd micronaut-openapi
git checkout CONSISTENT_ORDER (I am unable to find your version)
Change version to 2.4.4-SNAPSHOT (I know that Micronaut OpenAPI uses an own versioning that Micronaut)
./gradlew publishToMavenLocal (I checked the files in the .m2\repository\io\micronaut\openapi\micronaut-openapi\2.4.4-SNAPSHOT. They do exist)
```

In the project (You can find the change here: https://github.com/swaechter/openapiproblems/commit/b12be12d4e3356ee539e81d75aa41c964642fca1):
```
add mavenLocal() to my build
annotationProcessor("io.micronaut.openapi:micronaut-openapi:2.4.4-SNAPSHOT") 
implementation("io.micronaut.openapi:micronaut-openapi:2.4.4-SNAPSHOT")
```

Do I miss something like overwriting the annotation processor version? Schem attributes are still sorted in an alphabetical way.

**Comment by asodja** [comment]
Hey @swaechter,

this should probagly fix your issue:
```
diff --git a/build.gradle b/build.gradle
index 05cd06a..a9fa7e1 100644
--- a/build.gradle
+++ b/build.gradle
@@ -7,7 +7,6 @@ version = "0.1"
 group = "ch.swaechter"
 
 repositories {
-    mavenLocal()
     mavenCentral()
     maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
 }
@@ -19,12 +18,13 @@ micronaut {
         incremental(true)
         annotations("ch.swaechter.*")
     }
+    version = "2.4.2"
 }
 
 dependencies {
     annotationProcessor("io.micronaut:micronaut-management")
-    annotationProcessor("io.micronaut.openapi:micronaut-openapi:2.4.4-SNAPSHOT")
-    implementation("io.micronaut.openapi:micronaut-openapi:2.4.4-SNAPSHOT")
+    annotationProcessor("io.micronaut.openapi:micronaut-openapi:2.4.0-SNAPSHOT!!")
+    implementation("io.micronaut.openapi:micronaut-openapi:2.4.0-SNAPSHOT!!")
     implementation("io.swagger.core.v3:swagger-annotations")
     implementation("io.micronaut:micronaut-http-client")
     implementation("io.micronaut:micronaut-runtime")

```

Note: it also works without `!!` at the end of version if you include `version = "2.4.2"` in Micronaut definition. But just to be sure, you can force it with `!!`.  When new OpenApi is released you can remove it.

To know what version your app is using use: `./gradlew dependencies `.

I hope that helps.

**Comment by swaechter** [comment]
@asodja Thanks a lot for the diff (It works). Now I can save my coworker from mixing password/username in the Swagger GUI ;)
