### ISSUE TITLE
Schema attributes are in alphabetical and not natural class order

### ISSUE THREAD

**Issue by swaechter** [micronaut-projects/micronaut-openapi#482]
### Steps to Reproduce

1.) Clone the repository https://github.com/swaechter/openapiproblems and run it
2.) Take a look at the attribute order of the class https://github.com/swaechter/openapiproblems/blob/master/src/main/java/ch/swaechter/Owner.java
3.) Take a look at the attribute order of `Owner` in http://localhost:8080/swagger/views/swagger-ui/index.html

### Expected Behaviour

The attribite order is the same as in the Java class: id, vehicle, town, name (Natural attribute order)

### Actual Behaviour

The attributes are sorted in an alphabetical way: id, name, town, vehicle

It's not a critical bug, but a nasty own: When you write a class/schema you always fill in the Swagger values in the same order, only to realize this won't work ;)

### Environment Information

- **Operating System**: Windows 10 x64
- **Micronaut Version:** 2.3.3 (Maybe earlier too) - 2.4.2 Snapshot
- **JDK Version:** AdoptJDK jdk-11.0.10.9-hotspot

### Example Application

https://github.com/swaechter/openapiproblems

**Comment by asodja** [comment]
This was probably fixed in https://github.com/micronaut-projects/micronaut-openapi/issues/467, there was just no release yet.
