### ISSUE TITLE
micronaut-openapi v2.3.1 error - io.micronaut.context.exceptions.DependencyInjectionException

### ISSUE THREAD

**Issue by manti4ka** [micronaut-projects/micronaut-openapi#486]
### Steps to Reproduce

1. Micronaut + Kotlin project, includes micronaut-openapi - version 2.3.1 and swagger-annotations - version 2.1.7
2. Application has no problem to start and swagger documentation is generated but and gets error while injecting micronaut services 
3. Error = "io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [...] of class: com.example.TestService

Message: No bean of type [com.example.TestRestApi] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor)."

### Expected Behaviour

Not having problems with injection of beans

### Actual Behaviour

Error when injecting beans

### Environment Information

- **Operating System**: Windows 10 Pro
- **Micronaut Version:** 2.1.0
- **Kotlin Version:** 1.4.10

### Example Application

- TODO: link to github repository with example that reproduces the issue

### Workaround 

It works with micronaut-openapi version 2.2.2

**Comment by ilopmar** [comment]
I can't reproduce this. If this still happens in recent versions, please file provide an application that reproduces the problem.
