### ISSUE TITLE
Swagger UI Views not generating in 2.5.6

### ISSUE THREAD

**Issue by jcfrk101** [micronaut-projects/micronaut-openapi#520]
I have configured my micronauts project to compile swagger docs, and I can see a /swagger directory with an openapi yaml file, yet I cannot get swagger UI views to generate. I'm not sure this is a bug, it may be a configuration issue on my end, but I haven't been able to figure out what is wrong. A portion of my pom is copied below.

<build>
    <plugins>
      <plugin>
        <groupId>io.micronaut.build</groupId>
        <artifactId>micronaut-maven-plugin</artifactId>
      </plugin>
      
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          
          

          <annotationProcessorPaths combine.children="append">
            <path>
              <groupId>io.micronaut.openapi</groupId>
              <artifactId>micronaut-openapi</artifactId>
              <version>${micronaut.openapi.version}</version>
            </path>
          </annotationProcessorPaths>
          <compilerArgs>
            <arg>-Amicronaut.processing.group=com.redeye.rig</arg>
            <arg>-Amicronaut.processing.module=webservices</arg>
            <arg>-J-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop</arg>
          </compilerArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>

**Comment by ilopmar** [comment]
As a workaround you can create the file `openapi.properties` in the root of your project:

```properties
swagger-ui.enabled=true
redoc.enabled=true
rapidoc.enabled=true
```

**Comment by ilopmar** [comment]
The docs were wrong. The right argument is `-Amicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop` with `-A` instead of `-J-D`. See #576
