### ISSUE TITLE
Using Mono<Void> as return type for a endpoint generates and uses a Void schema as response body instead of nothing

### ISSUE THREAD

**Issue by nfode** [micronaut-projects/micronaut-openapi#570]
### Expected Behavior

The expected behavior is like it worked for us before updating to the latest micronaut and micronaut-openapi version. Before, we were using micronaut 2.1.1 and micronaut-openapi 1.5.3.

We tried to reproduce and debug the issue with versions in between our version and the latest micronaut and micronaut-api versions, but could not find in which version the behaviour changed.

When having endpoints with a Mono<Void> or Flux<Void> return type ([like here](https://github.com/flip-corp/micronaut-openapi-mono-void-bug/blob/7eb1e9a9e4a4f220587dc53cd3ce9a0b873dbd49/src/main/kotlin/com/example/api/Controller.kt#L20) or [here](https://github.com/flip-corp/micronaut-openapi-mono-void-bug/blob/7eb1e9a9e4a4f220587dc53cd3ce9a0b873dbd49/src/main/kotlin/com/example/api/Controller.kt#L25)), it is expected that the response has only a description and no content. This behavior works when using a non-reactive endpoint with no return type (endpoint defined like [here](https://github.com/flip-corp/micronaut-openapi-mono-void-bug/blob/7eb1e9a9e4a4f220587dc53cd3ce9a0b873dbd49/src/main/kotlin/com/example/api/Controller.kt#L16)).

Here is an example how it should look like:
```
	"200":
          description: ...
```

### Actual Behaviour

Behavior was observed with an [example project](https://github.com/flip-corp/micronaut-openapi-mono-void-bug.git) created with Micronaut Launch.

Here is the response when using Mono<Void> or Flux<Void>.

The response:
```
	"200":
          description: mono 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
```

The additional created schema:
```
    Void:
      type: object
```

Interestingly, this cannot be fixed by using a `@ApiResponse` annotation like this ([full method definition](https://github.com/flip-corp/micronaut-openapi-mono-void-bug/blob/7eb1e9a9e4a4f220587dc53cd3ce9a0b873dbd49/src/main/kotlin/com/example/api/Controller.kt#L31)):

```
@ApiResponse(content =  [Content(schema = Schema())])
```

This results in the following response:

```
		"200":
          content:
            application/json:
              schema:
                type: object
```

### Steps To Reproduce

1. Run `./gradlew kaptKotlin` in the provided example project
2. Check the generated spec under `build/tmp/kapt3/classes/main/META-INF/swagger/demo-0.0.yml`

### Environment Information

- JDK Version: AdoptJDK 15 & OpenJDK 16
- Various operating systems

### Example Application

https://github.com/flip-corp/micronaut-openapi-mono-void-bug

### Version

micronaut 3.0.1 and micronaut-openapi 3.0.3

**Comment by ilopmar** [comment]
So, after giving a second though and try with all latest minor version from 3.0.x down to 2.1.x (also including 2.1.1). The behavior is the same in all versions. I've also tried with `Maybe` just in case and the output is:

```yaml
openapi: 3.0.1
info:
  title: openapi-570
  version: "0.0"
paths:
  /mono:
    get:
      operationId: mono1
      parameters: []
      responses:
        default:
          description: mono1 default response
          content:
            application/json:
              schema:
                type: string
  /monoVoid:
    get:
      operationId: monoVoid
      parameters: []
      responses:
        default:
          description: monoVoid default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
  /fluxVoid:
    get:
      operationId: fluxVoid
      parameters: []
      responses:
        default:
          description: fluxVoid default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Void'
  /singleVoid:
    get:
      operationId: singleVoid
      parameters: []
      responses:
        default:
          description: singleVoid default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
components:
  schemas:
    Void:
      type: object
```

**Comment by ilopmar** [comment]
In cases like this which is not 100% clear what to do, I try to do the same with Spring Boot just to check what the Spring team decided. 

This is the output and I don't really like it because it creates those artificial schemas like `MaybeVoid`, `MonoString`,...

```yaml
...
  /570/void:
    get:
      tags:
      - hello-controller
      operationId: returnVoid
      responses:
        "200":
          description: OK
  /570/singleVoid:
    get:
      tags:
      - hello-controller
      operationId: singleVoid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MaybeVoid'
  /570/mono:
    get:
      tags:
      - hello-controller
      operationId: mono1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MonoString'
  /570/monoVoid:
    get:
      tags:
      - hello-controller
      operationId: monoVoid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MonoVoid'
  /570/fluxVoid:
    get:
      tags:
      - hello-controller
      operationId: fluxVoid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FluxVoid'
components:
  schemas:
    MaybeVoid:
      type: object
    MonoString:
      type: object
    MonoVoid:
      type: object
    FluxVoid:
      type: object
      properties:
        prefetch:
          type: integer
          format: int32
```

**Comment by nfode** [comment]
It is interesting that no one ever had a problem with the artificial schemas for Mono/Flux<Void> return types. For me, it felt natural that when a blocking method with Void/Unit as type results in no response body, the reactive way should too. And if I understand correctly, using Mono<Void>/Flux<Void> is the reactive way of saying there is no response.

I would be ok with having artificial schemas if others want that, and if Spring is also doing this, there might be good reasons. But then, we should be able to say we do not want a body using annotations, which also does not work as described above.

I never used Maybe, so I don't have input on that.

**Comment by ilopmar** [comment]
> And if I understand correctly, using Mono/Flux is the reactive way of saying there is no response.

I don't think this is true. Returning a `Mono/Flux` means that you return a reactive type. In the case of `Mono` it means that it can be one element or no element at all, but doesn't imply "no respose".

> I would be ok with having artificial schemas if others want that, and if Spring is also doing this, there might be good reasons. But then, we should be able to say we do not want a body using annotations, which also does not work as described above.

Using the `@Schema` annotation doesn't work because by default it uses `Void`:

![image](https://user-images.githubusercontent.com/559192/134135198-e42db02f-f95d-4f91-a701-fefa70f8feaf.png)

**Comment by nfode** [comment]
> I don't think this is true. Returning a Mono/Flux means that you return a reactive type. In the case of Mono it means that it can be one element or no element at all, but doesn't imply "no respose".

In some sense, it does. It signals that there is only completion, but no return value. From the [reactor doc](https://projectreactor.io/docs/core/release/reference/#mono): "Note that you can use a Mono to represent no-value asynchronous processes that only have the concept of completion (similar to a Runnable). To create one, you can use an empty Mono<Void>." In my understanding, it is similar to write a non-blocking method with a Void return type. You signal that you process something, but there is no return value.

> Using the @Schema annotation doesn't work because by default it uses Void

That is what I am wondering about. If I write a non-blocking method with Void as return type (by having no return type at all) micronaut-openapi interprets it as having no response, but when I explicitly tell it via annotation that I want Void as implementation it handles it differently. 

Thank you for your time and looking into my issue.

**Comment by ilopmar** [comment]
I'm not sure about the `Void` type. With the following in my controller:

```java
@Get("/void")
void returnVoid() {
}

@Get("/voidType")
Void returnVoidType() {
    return null;
}
```

I get:

```yaml
  /void:
    get:
      operationId: returnVoid
      parameters: []
      responses:
        "200":
          description: returnVoid 200 response
  /voidType:
    get:
      operationId: returnVoidType
      parameters: []
      responses:
        "200":
          description: returnVoidType 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
```

**Comment by nfode** [comment]
That means defining no return type results in an empty response, and defining a return type results in a generated schema no matter what the type is.

In my opinion, Void should be a special case here, since there is no other way of saying I do not want a response that results in additional schemas. But I can understand if micronaut-openapi does not want to change that behavior because of one person complaining.

As a side note: Do you think it would make sense to somehow implement this as a flag? Something like: `interpret_void_as_no_response` (working title?

**Comment by ilopmar** [comment]
> As a side note: Do you think it would make sense to somehow implement this as a flag? Something like: `interpret_void_as_no_response` (working title)?

Having that behavior by default is a bad idea because it's a breaking change and nobody has complained about it. But I can see that `Void` could be a special case, so it makes sense to treat it like that behind some flag.
Feel free to send a PR and I'm gladly review it :-)

**Comment by nfode** [comment]
Can you give me some pointers where I would implement that feature? I already had a look at the code but had no idea where I would implement this :)

**Comment by ilopmar** [comment]
Sorry for the delay, I've been fighting with Gradle :sob: 

You can set a breaking point in this method: https://github.com/micronaut-projects/micronaut-openapi/blob/dd718e9fa9b6a0d1d3e7324ab4acb461d5c8a7c4/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java#L636

In there `type` is the return type of the controller action, so in this case it would be `java.lang.Void`.
In that same method the code reaches https://github.com/micronaut-projects/micronaut-openapi/blob/dd718e9fa9b6a0d1d3e7324ab4acb461d5c8a7c4/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java#L720 and we generate a new `Schema` for that type. You would need to add an extra `if` before that to check for the `Void` type (also take into account the reactive types that may wrap it).
Do not forget to add test(s) for it. There are plenty of tests in the repo so you can find examples of pretty much everything. Also everything is easier to debug from a test.

Feel free to reach out if you get stuck or need any additional information or help.

**Comment by cemo** [comment]
I think I had resolved this issue as well. Can you try with latest master branch? If I can find a time, I will take a look today.

**Comment by ilopmar** [comment]
Given the following controller:

```java
@Controller
public class VoidController {

    @Get("/mono")
    Mono<String> mono() {
        return Mono.just("mono");
    }

    @Get("/monoVoid")
    Mono<Void> monoVoid() {
        return Mono.empty();
    }

    @Get("/fluxVoid")
    Flux<Void> fluxVoid() {
        return Flux.empty();
    }

    @Get("/maybeVoid")
    Maybe<Void> maybeVoid() {
        return Maybe.empty();
    }

    @Get("/void")
    void returnVoid() {
    }

    @Get("/voidType")
    Void returnVoidType() {
        return null;
    }
}
```

It generates the following openapi:

```yaml
openapi: 3.0.1
info:
  title: openapi-570
  version: "0.0"
paths:
  /fluxVoid:
    get:
      operationId: fluxVoid
      parameters: []
      responses:
        "200":
          description: fluxVoid 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Void'
  /maybeVoid:
    get:
      operationId: maybeVoid
      parameters: []
      responses:
        "200":
          description: maybeVoid 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
  /mono:
    get:
      operationId: mono
      parameters: []
      responses:
        "200":
          description: mono 200 response
          content:
            application/json:
              schema:
                type: string
  /monoVoid:
    get:
      operationId: monoVoid
      parameters: []
      responses:
        "200":
          description: monoVoid 200 response
  /void:
    get:
      operationId: returnVoid
      parameters: []
      responses:
        "200":
          description: returnVoid 200 response
  /voidType:
    get:
      operationId: returnVoidType
      parameters: []
      responses:
        "200":
          description: returnVoidType 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
components:
  schemas:
    Void:
      type: object
```

So, for this issue with `Mono<Void>` it works but for the other types: `Flux<Void>`, `Maybe<Void>` and `Void` it doesn't. 
@cemo you've changed something related to this in your last PR, would you like to give it a try to this one to fix what's left?

**Comment by oliver-doller** [comment]
Collegue of @nfode  here.

I tried it with the newest Snapshot `kapt("io.micronaut.openapi:micronaut-openapi:3.1.0-SNAPSHOT")` and it looked fine for me. 
The controllers in question all use `Mono <Void>`.

**Comment by ilopmar** [comment]
As I mentioned before, now it does work with `Mono<Void>` but it doesn't with `Flux<Void>` or `Maybe<Void>`.
