### ISSUE TITLE
Interface Inheritance

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-openapi#577]
### Expected Behavior

OpenApi spec must be created properly for interfaces too. 

### Actual Behaviour

It is working for classes but not interface based inheritance.

### Steps To Reproduce

1. checkout main branch
2. clone https://github.com/cemo/swagger-spec
3. mvn clean compile

Check `target/classes/META-INF/swagger/swagger-spec-0.0.yml`

It has **not including** `BaseQueryParams`

-----

switch into `working-properly`

Check `target/classes/META-INF/swagger/swagger-spec-0.0.yml`

It has **including** `BaseQueryParams`

### Example Application

https://github.com/cemo/swagger-spec

### Version

3.0.3

**Comment by graemerocher** [comment]
`@JsonProperty` is not an inherited annotation

**Comment by cemo** [comment]
@graemerocher  How can I make it inherited?

**Comment by cemo** [comment]
I cleaned all jsonProperty annotations. Result is same. Actually It was simplified version piece of code but I forgot to delete that annotations.

**Comment by cemo** [comment]
`  - $ref: '#/components/schemas/BaseQueryParams'` is missing in the first version. I can take a look if you guide me @graemerocher.

```
openapi: 3.0.1
info:
  title: swagger-spec
  version: "0.0"
paths:
  api/products:
    get:
      operationId: getProducts
      parameters: []
      responses:
        "200":
          description: getProducts 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdcatProductsResponse'
components:
  schemas:
    BaseQueryParams:
      type: object
      properties:
        locationId:
          type: string
        productId:
          type: integer
          format: int32
    ProdcatProductsResponse:
      type: object
      properties:
        searchMetadata:
          $ref: '#/components/schemas/ProdcatSearchMetadata'
    ProdcatSearchMetadata:
      allOf:
      - $ref: '#/components/schemas/BaseQueryParams'
      - type: object
        properties:
          page:
            $ref: '#/components/schemas/ProdcatSearchMetadata.Page'
    ProdcatSearchMetadata.Page:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalResults:
          type: integer
          format: int32

```

**Comment by cemo** [comment]
@graemerocher 
https://github.com/micronaut-projects/micronaut-openapi/blob/master/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java#L1200

this line is returning null for interfaces. I am blindly guessing but calling `classElement.isInterface()` with classElement.getInterfaces().get(0) may resolve issue. Would you accept a PR? :)

**Comment by cemo** [comment]
micronaut-openapi is using 2.5.x in the gradle config. This version brings `micronaut-inject` 2.5.x which does not have `getInterfaces` method. :) Any help will be helpful.

https://github.com/micronaut-projects/micronaut-openapi/blob/0c8f9fe13b7be0db8e73938b8b2f9e1807444a5f/gradle.properties#L4

Thanks

**Comment by cemo** [comment]
@graemerocher, gentle ping.
would you please provide necessary guidance?

**Comment by graemerocher** [comment]
PRs welcome

**Comment by cemo** [comment]
@graemerocher I will open a PR but I need to upgrade version of micronaut in the gradle properties. Is this accepted?

**Comment by graemerocher** [comment]
Yes but you will probably need to bump the minor version

**Comment by cemo** [comment]
@graemerocher 
The code is introduced against 3.x 
https://github.com/micronaut-projects/micronaut-core/commit/67b4590f292a728a9517927221f44aea41d54052
