### ISSUE TITLE
Generic support for operationId

### ISSUE THREAD

**Issue by b0c1** [micronaut-projects/micronaut-openapi#580]
### Issue description

Hi guys,

now the operationId is based on method name, but it's unusable when my controller methods is defined in a generic class (example CRUD). Maybe a custom annotation on the parent class will help, like this:

```java
@OpenApiDecorator(operationIdPrefix="userAdmin")
public class UserAdminCrudController extends AbstractCrudController<UserModel, UserModelMapper, UserDTO> {
//...
}

@OpenApiDecorator(operationIdPrefix="competitionAdmin")
public class CompetitionAdminCrudController extends AbstractCrudController<CompetitionModel, CompetitionModelMapper, CompetitionDTO> {
}
```

**Comment by ilopmar** [comment]
Can you please share a simple application with your use case and explain what would be the expected openapi?
