### ISSUE TITLE
Kotlin classes can not be marked as nullable in open api spec

### ISSUE THREAD

**Issue by Poorva17** [micronaut-projects/micronaut-openapi#582]
### Expected Behavior

val students: List<Student>? // works and generate as `null or array of objects`
val student: Student? // null or object
val name: String? // null or string

### Actual Behaviour

val students: List<Student>? // works as expected
val student: Student? // Does NOT work. It shows as non nullable field
val name: String? // works as expected

### Steps To Reproduce

Version:

kapt("io.micronaut.configuration:micronaut-openapi:1.5.2")

### Environment Information

- JDK version - JDK 11

### Version

1.5.2

**Comment by ilopmar** [comment]
Some things has changed since 1.5.2. Can you please try with micronaut-openapi 3.0.4 or 2.6.2?

**Comment by Poorva17** [comment]
Hello @ilopmar , thank you for quick response. 
https://mvnrepository.com/artifact/io.micronaut.configuration/micronaut-openapi Version 1.5.3 is the latest version available on maven central.

**Comment by ilopmar** [comment]
That's a really old version so I'm assuming you still use Micronaut 1.x. For Micronaut 2 we changed the groupId: https://mvnrepository.com/artifact/io.micronaut.openapi/micronaut-openapi

Can you please try with a fresh 3.0.2 application created from Launch (https://micronaut.io/launch) or at least share a simple application that reproduces the problem with latest version.

**Comment by ilopmar** [comment]
Closing due to the lack of feedback
