### ISSUE TITLE
 OpenAPI doc generation should be conditional on `@Requires` annotations on Controllers

### ISSUE THREAD

**Issue by volkert-fastned** [micronaut-projects/micronaut-openapi#584]
### Expected Behavior

Suppose you have a controller defined like this (I'm using Kotlin here, but the language doesn't matter in this context):

```kotlin
/**
 * Test functionality. Not intended for production environments.
 */
@Requires(env = ["test-env"])
@Validated
@Controller("/some/root/uri", produces = [MediaType.APPLICATION_JSON], consumes = [MediaType.APPLICATION_JSON])
class TestOnlyController() {

    @Post(uri = "/my-test-action")
    @Operation(tags = ["test-only-controller"])
    suspend fun myTestOnlyAction(): HttpResponse<*> {
        // Code here.
    }
}
```

Now if the application is launched  in a Micronaut environment other than `test-env`, this controller rightly is excluded. 

`micronaut-openapi` should then also exclude this endpoint from Swagger/OpenAPI documentation generation.

### Actual Behaviour

`micronaut-openapi` apparently does not evaluate the `@Requires` annotation and always generates Swagger/OpenAPI documentation for the endpoint, even if the endpoint is excluded from the currently active Micronaut environment.

Attempts to invoke the endpoint will then result in a 404 error with the message "page not found".
At the DEBUG level, the message `No matching route: POST /some/root/uri/my-test-action` will be logged.

### Steps To Reproduce

1. Build an application with the endpoint as defined under `Expected Behavior`
2. Launch the application with a Micronaut environment other than `test-env`
3. Navigate to the Swagger/OpenAPI UI and look for the endpoint
4. Use the UI to perform the POST request

### Version

3.x

**Comment by volkert-fastned** [comment]
Now I understand that Micronaut processes annotations like this at compile time and not at runtime. Perhaps a solution would be to generate different Swagger/OpenAPI docs for the different Micronaut environments that are defined in the `@Requires` annotations, and then select the applicable one on application startup, depending on what Micronaut environments are active?

**Comment by ilopmar** [comment]
You can annotate the controller or the action with `@Hidden` so it will be skipped. It's not exactly what you want but it will allow you to hide that endpoint for non-test environments.

**Comment by volkert-fastned** [comment]
@ilopmar Thanks. I am aware of that option, but an eventual dynamic solution would still be appreciated.
