### ISSUE TITLE
Exclude controllers from OpenAPI

### ISSUE THREAD

**Issue by hc-codersatlas** [micronaut-projects/micronaut-openapi#60]
Hi, OpenAPI scans all the controllers. Is there a way to exclude some? Or more specifically remove those used as part of e.g. Micronaut Views. Some controllers may not be an API controller.

**Comment by reanimated** [comment]
Have you tried using the @Hidden annotation?

**Comment by hc-codersatlas** [comment]
@reanimated thanks, that's working.
