### ISSUE TITLE
OpenAPI annotation processor for Groovy not works as expected

### ISSUE THREAD

**Issue by fmonorchio** [micronaut-projects/micronaut-openapi#602]
### Expected Behavior

Hi all,

I need to add the management endpoints to openapi specification file  with the annotation @OpenAPIManagement and import a controller endpoints from another gradle submodule with @OpenAPIInclude.
But in the generated specification nothing is present.

I added the compile dependency io.micronaut.openapi:micronaut.openapi
In my project I'm using Groovy 3 and Micronaut 3.1.0

### Environment Information

Ubuntu
JDK 11

### Version

3.1.0

**Comment by ilopmar** [comment]
Can you please share an application that reproduces your problem?

**Comment by fmonorchio** [comment]
Sure, I share it in a few days.

**Comment by fmonorchio** [comment]
https://github.com/fmonorchio/micronaut-openapi-test

**Comment by ilopmar** [comment]
The problem can be reproduced with a very simple Groovy project. The same project with Java works properly (adding the appropriate dependencies). I'll dig to see why this happens.

P.S: As an unsolicited advice, when you create an application that reproduces a problem, please try to make it as easy and simple as possible. Your sample application is more complex than it should be :sweat_smile:

**Comment by fmonorchio** [comment]
I have copied my source code as possible. :-)

Next time, I follow your advice for sure. Sorry @ilopmar

**Comment by ilopmar** [comment]
The code does nothing for Groovy because we are explicitly not running it, see https://github.com/micronaut-projects/micronaut-openapi/blob/master/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiIncludeVisitor.java#L45-L47

After removing that `if` there is an error during compilation. I've reported an issue (https://github.com/micronaut-projects/micronaut-core/issues/6503) to Micronaut core but it's probably that this is a Groovy bug an not something on our side.

**Comment by Maritims** [comment]
> The code does nothing for Groovy because we are explicitly not running it, see https://github.com/micronaut-projects/micronaut-openapi/blob/master/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiIncludeVisitor.java#L45-L47
> 
> After removing that `if` there is an error during compilation. I've reported an issue ([micronaut-projects/micronaut-core#6503](https://github.com/micronaut-projects/micronaut-core/issues/6503)) to Micronaut core but it's probably that this is a Groovy bug an not something on our side.

@ilopmar Is it correct that this would produce a similar result when using the `@OpenAPISecurity` annotation in combination with Groovy? That might explain the problem I'm having in #693 where this annotation does not result in the expected information being generated in the Swagger YAML.

**Comment by faireai-fmonorchio** [comment]
On my groovy project, I moved the @OpenApiDefinition inside a java class and
the annotations works as expected but I have found a strange behavior.
Two yml files are generated.

Here the logs:

> Task :sources:services:graphql-server:compileJava
Note: Generating OpenAPI Documentation
/home/fmonorchio/repositories/MyProject/sources/services/graphql-server/src/main/java/eu/myproject/graphqlserver/Application.java:54: warning: /home/fmonorchio/repositories/MyProject/sources/services/graphql-server/build/classes/groovy/main/META-INF/swagger/swagger.yml does not exist or is not a directory
class Application {
^
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
Note: Writing OpenAPI YAML to destination: /home/fmonorchio/repositories/MyProject/sources/services/graphql-server/build/classes/java/main/META-INF/swagger/**graphql-server-0.0.1.yml**
Note: Creating bean classes for 1 type elements
2 warnings

> Task :sources:services:graphql-server:compileGroovy
Note: Writing OpenAPI YAML to destination: /home/fmonorchio/repositories/MyProject/sources/services/graphql-server/build/classes/groovy/main/META-INF/swagger/**swagger.yml**

There is a chance to generate a single file or merge the two? Thanks
