### ISSUE TITLE
Error Type io.micronaut.management.endpoint.annotation.Endpoint not present, using OpenAPIInclude

### ISSUE THREAD

**Issue by bartoleo** [micronaut-projects/micronaut-openapi#618]
### Expected Behavior

Hi I want to add docs from compiled classes using @OpenAPIInclude 

### Actual Behaviour

To use it I must add the dependency:
`implementation("io.micronaut.openapi:micronaut-openapi:3.2.0")`

Withouth it I get
```
error: package io.micronaut.openapi.annotation does not exist
import io.micronaut.openapi.annotation.OpenAPIInclude;
                                      ^
1 error

FAILURE: Build failed with an exception.
```

Adding it:
```
    annotationProcessor("io.micronaut.openapi:micronaut-openapi:3.2.0") //for annotations
    implementation("io.micronaut.openapi:micronaut-openapi:3.2.0") //for OpenAPIInclude
    implementation("io.swagger.core.v3:swagger-annotations"
```

I get
```
Execution failed for task ':compileJava'.
> java.lang.TypeNotPresentException: Type io.micronaut.management.endpoint.annotation.Endpoint not present
```

### Steps To Reproduce

1. generate a new Micronaut app with "openapi" feature
2. change build.gradle to add implementation("io.micronaut.openapi:micronaut-openapi:3.2.0")
3. in Application.java add import to: import io.micronaut.openapi.annotation.OpenAPIInclude;

### Environment Information

Windows 10
Jdk 11

### Version

3.2

**Comment by bartoleo** [comment]
Sorry I found it, I was missing the dependency:
`    annotationProcessor("io.micronaut:micronaut-management:3.2.0") `

**Comment by ilopmar** [comment]
@bartoleo if you think the docs are not good enough to explain this use case, please feel free to send a PR to improve them. Thanks.
