### ISSUE TITLE
rapipdf.enabled=true not working

### ISSUE THREAD

**Issue by andreas-mausch** [micronaut-projects/micronaut-openapi#649]
### Expected Behavior

I expected to have a PDF file after running the build.

### Actual Behaviour

No PDF file was generated.

### Steps To Reproduce

Pass rapipdf.enabled=true to your build as described [here](https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#rapipdf).
No PDF will be generated.
Tested with micronaut-openapi Version 3.2.0.

I guess it's a bug, see here:
https://github.com/micronaut-projects/micronaut-openapi/blob/3c24f1268d5893c98efea007abcec5b37ae471b4/openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java#L106-L117

It handles all other methods, but not rapipdf.
rapidoc worked for me, so passing the parameters in general worked.

### Version

3.2.0

**Comment by ilopmar** [comment]
This works as expected. The documentation says: _It will add a button to the view to generate a PDF from the spec file._

![image](https://user-images.githubusercontent.com/559192/150775194-6cd727f8-f31e-477d-875d-c6f3dd02e44b.png)

Which means that a PDF file will be created on the fly when clicking on that new button that is now available on the UI.

![image](https://user-images.githubusercontent.com/559192/150775299-d94e2e45-2feb-40c8-9bd2-81990c3891e8.png)

You can download the generated PDF, for example: [df454875-0806-4c26-aca6-ec8939f6010f.pdf](https://github.com/micronaut-projects/micronaut-openapi/files/7925156/df454875-0806-4c26-aca6-ec8939f6010f.pdf)

**Comment by andreas-mausch** [comment]
Oh I see. Thanks for clarifying.
