### ISSUE TITLE
Add support for security annotations annotations to OpenAPI generator

### ISSUE THREAD

**Issue by Deepakkoli93** [micronaut-projects/micronaut-openapi#669]
### Feature description

I would like to have support for `@RequestAttribute` and `@RolesAllowed` annotations

`@RequestAttribute` helps in binding a bearer auth token to an arguments in a controller, currently bearer auth is not supported by the server code generator

`@RolesAllowed` works with the `@Secured` annotation to allow access only to users with certain roles. I saw that `@Secured` is supported in the current implementation but not sure about `@RolesAllowed`, it's not clear from the documentation.

**Comment by graemerocher** [comment]
@andriy-dmytruk can you look at what it takes to add support for these annotations to the generator

**Comment by Deepakkoli93** [comment]
Support for roles in openapi generator for micronaut was added through extension: https://github.com/OpenAPITools/openapi-generator/pull/11995.
