### ISSUE TITLE
@NotNull constraint not recognized

### ISSUE THREAD

**Issue by alphawolf1988** [micronaut-projects/micronaut-openapi#72]
Currently the @NotNull annotation isn't recognized correctly while generating the OpenAPI spec.
It seems to be, that for Micronaut 1.2.1, all fields are marked as required. If i add the annotation  @Nullable, the field is not marked as required, but this shouldn't be required in my eyes, since we have @NotNull for the required case.

**Comment by hayond** [comment]
@alphawolf1988 same problem，since 1.2.1，all properties marked as required. pr #65  for 1.2.1 and 1.2.2 seem to support requried and requiredProperties，and make all properties required. i think it is wrong. if all properties required, how to make requried and requiredProperties effect？

**Comment by graemerocher** [comment]
Would you like to send another PR to correct this?
