### ISSUE TITLE
Page should not be documented as an Iterable (Array)

### ISSUE THREAD

**Issue by ggerbaud** [micronaut-projects/micronaut-openapi#753]
### Expected Behavior

When a controller returns a `Page<Something>` (or `Mono<Page<Something>>`) the generated schema is an array of Something, because `io.micronaut.data.model.Page` is an `Iterable`.
But Page fields are then omited/missing.

### Actual Behaviour

Page schema should contains Page fields like totalSize, totalPages, size, offset, ...

### Steps To Reproduce

See this demo project : https://github.com/ggerbaud/demo-micronaut/tree/demo/openapi/page
mvn compile
then see target/classes/META-INF/swagger/*.yml file

### Example Application

https://github.com/ggerbaud/demo-micronaut/tree/demo/openapi/page

### Version

3.5.2 and previous

**Comment by altro3** [comment]
@ggerbaud Hi! I fixed this problem in this pull request: #756 , but this will only work after the changes from here are merged: #750
