### ISSUE TITLE
POST method with `@Body("name")` should generate correct request object schema

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-openapi#774]
### Expected Behavior

I would expect `HttpResponse<Genre> save(@Body("name") @NotBlank String name)` method to produce a OpenAPI with request format `{name: String} `.

### Actual Behaviour

The method is generated with a request simple schema:

```yaml
    post:
      operationId: save
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: save 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genre'
```

### Version

4.4.0

**Comment by altro3** [comment]
@dstepanov Hi! In this example, a correct shema is created according to the OpenApi specification: you indicate that the request body is mapped into the name parameter, but the request body according to the OpenApi specification cannot have a name, unlike queryValue or PathVariable

**Comment by dstepanov** [comment]
The example is alternative to having a DTO object with one property name. To send a request I need to modify the string and send “{“name”:”abc”}”.

**Comment by altro3** [comment]
@dstepanov yes, sorry, I already figured it out myself :-). I'll fix the problem here: https://github.com/micronaut-projects/micronaut-openapi/pull/777. Also, I fixed a bug: annotations were ignored when processing a parameter with the annotation Body
