### ISSUE TITLE
Compilation failure in Groovy projects since Micronaut OpenAPI 4.4.0

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-openapi#781]
@altro3 FYI, #761 has introduced a regression in Groovy projects. They won't compile because both `com.github.chhorz:javadoc-parser` and `com.vladsch.flexmark:flexmark-html2md-converter` need to be in the classpath (for Groovy projects):

https://github.com/micronaut-projects/micronaut-starter/runs/7563422170?check_suite_focus=true#step:5:3218

I wonder why the test suite here didn't catch this problem. Will investigate

**Comment by altro3** [comment]
@alvarosanchez Hi! Yes, sorry, I thought that these libraries are not required in the central bom file, so I did not prefix it with `managed` . It seems that I did not fully understand the logic - when it is required to prefix `managed` , and when not

**Comment by alvarosanchez** [comment]
Don't worry, like I said, the test suite should have raised the problem. Fortunately, it was caught by micronaut-starter
