### ISSUE TITLE
OpenAPI definition in multiple modules and only one view

### ISSUE THREAD

**Issue by weesftw** [micronaut-projects/micronaut-openapi#810]
### Expected Behavior

```
| 
|── main-app
|    |── Application.class
|
|── multi-modules
|   |── moduleA
|       |── ControllerA.class
|   |── moduleB
|       |── ControllerB.class
``` 

- Similar to issue [#225](https://github.com/micronaut-projects/micronaut-openapi/issues/225).

Inside modules A and B I have controllers containing OpenAPI annotations to map to Swagger's visualization layer. However, if my `main-app` uses both `moduleA` and `moduleB`, the view predominates only one module and does not merge `moduleB`, and the final result only shows the `ControllerA` endpoint due to the way the `micronaut-openapi` works.

Is it possible to do something so that my `main-app` inheriting both modules will map the two controllers to be displayed in the swagger UI?

### Steps To Reproduce

`multi-module`:
> mvn clean install 

`main`
> mvn clean compile

See the target folder generating the META-INF with the swagger index without all the module controllers.
See: http://localhost:8080/swagger-ui/#/ to result too.

### Example Application

https://github.com/weesftw/micronaut-multi-module-openapi

### Version

3.7.0

**Comment by abedurftig** [comment]
You can use the OpenApiInclude annotation to reference Controllers in other modules. https://micronaut-projects.github.io/micronaut-openapi/latest/guide/#openapiinclude Seems you have to add them one by one.

However one thing I noticed with the OpenApiInclude is that, it won't generate the components in the spec (response types).

**Comment by weesftw** [comment]
@abedurftig thanks, i'm aware, but I was wondering if there is any way for the micronaut to automatically include it.

**Comment by abedurftig** [comment]
>However one thing I noticed with the OpenApiInclude is that, it won't generate the components in the spec (response types).

@weesftw, have you solved this?

**Comment by abedurftig** [comment]
> @abedurftig I just tested it and it displays normally: 200, 404... with schema example included.

@weesftw strange, could you maybe share your working solution? Would be great! Thanks

**Comment by weesftw** [comment]
@abedurftig inside my project's dependencies, I have a module that contains a controller, I referenced it in the `@OpenAPIInclude` annotation in the initialization Main class.

**Comment by barm** [comment]
I have the same issue and haven't found a way to be able to include other compilation targets without explicitly listing the class path of each controller.

**Comment by altro3** [comment]
@weesftw @barm @abedurftig Yes, all this is supported, but in this case you will have to add each controller manually for processing. from what you need to do in your example and what will happen in the end:

1. Add `@OpenAPIInclude` annotation:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/b9a7bbbb-fb60-4144-812f-74be0e0e3957)
2. Fix mistake in `openapi.properties` configuration. Must be like this:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/1950dccc-3e28-465b-8c52-bd5440168d77)
3. Add compileOnly dependency to your main pom.xml:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/673b19e4-e2dd-4775-953a-cafba3e0e274)

After it you will see generated swagger file with both controllers:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/9cf2313a-c852-451d-bbab-6d2c5a1d8140)
