### ISSUE TITLE
Swagger Definition missing 'name' value in securitySchemes section for apiKey type

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-openapi#82]
Version 1.2.0 of micronaut correctly generates the following swagger 3.0 values under components/securitySchemes

      securitySchemes:
        key:
          type: apiKey
          name: yourKeyName
          in: query

In 1.2.5 the `name: yourKeyName` field is missing (the API key name field), and the schema fails to validate.

Documentation is at https://swagger.io/docs/specification/authentication/api-keys/

I can't see it saying it's mandatory, but no examples show it missing in the apiKey type.

**Comment by puneetbehl** [comment]
Please use [paramName](http://docs.swagger.io/swagger-core/v2.0.8/apidocs/io/swagger/v3/oas/annotations/security/SecurityScheme.html#paramName--) as: 

```
@SecurityScheme(name = "BearerAuthCookie",
        type = SecuritySchemeType.APIKEY,
        in = SecuritySchemeIn.COOKIE,
        paramName = "apiKey")

```
which correctly generates:

```
components:
  securitySchemes:
    key:
      type: apiKey
      name: apiKey
      in: query
```

I just tested with Micronaut 1.2.5, following is the sample application: [testapp.zip](https://github.com/micronaut-projects/micronaut-openapi/files/3823664/testapp.zip)

**Comment by markjfisher** [comment]
That worked. Thanks!
