### ISSUE TITLE
`@QueryValue(defaultValue = "") items: List<String>` with kapt and Kotlin breaks Micronaut

### ISSUE THREAD

**Issue by korri123** [micronaut-projects/micronaut-openapi#833]
### Expected Behavior

Micronaut should be able to start without exception and items initialized to empty list. Works correctly if `annotationProcessor` is used in place of `kapt`.

### Actual Behaviour

Application is unable to start, exception is 
```
Execution failed for task ':kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

### Steps To Reproduce

1. Create Micronaut Kotlin project with openapi module as a dependency:
`kapt("io.micronaut.openapi:micronaut-openapi:4.5.2")`

2. Create a controller that contains an endpoint that takes a `QueryValue` `List<String>` with `defaultValue = ""` (all required to trigger issue):

```java
package com.example

import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.http.annotation.QueryValue

@Controller
class TestController {
    @Get
    fun test(
        @QueryValue(defaultValue = "") items: List<String>
    ): String {
        return ""
    }
}
```

(Error also happens in a Java file controller)

3. Run application

4. Exception should happen: 

```
Execution failed for task ':kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

### Environment Information

- Ubuntu 22.04
- JDK 11

### Version

3.7.2

**Comment by altro3** [comment]
if the problem is something else, please write an example of an application to reproduce the error

**Comment by korri123** [comment]
Hey @altro3, thanks for looking into this. Apologies, I should have provided an example project from the start to be fully sure. Could you try reproducing with this? It should be enough to just launch the project.
[micronautdemo.zip](https://github.com/micronaut-projects/micronaut-openapi/files/9891187/micronautdemo.zip)

**Comment by altro3** [comment]
@korri123 Thanks for example. Ok, what I can say:

1. Yes, indeed, when using version 4.5.2 - an Exception is thrown. But I tried using the version with the latest fixes - no more errors. Try to connect the `4.6.0-SNAPSHOT` version - and you will see that everything works.

To connect a repository with snapshots, add this to the gradle:
```groovy
repositories {
    mavenCentral()
    mavenCentral {
        url "https://s01.oss.sonatype.org/content/repositories/snapshots/"
        mavenContent {
            snapshotsOnly()
        }
    }
}
```

2. As I said above, I fixed the problem that the defaultValue was not added to the swagger file in your case.

3. Regarding your question: I can tell you how to do it exactly in the swagger file (after my pull request is merged into the master): for this you need to add an annotation:
```java
@Schema(defaultValue = "[]") @QueryValue items: List<String?>?
```
but there is one big problem: micronaut-http does not allow you to set an empty list through parameters. Those. if you pass the items parameter, then the list will always be non-empty. If you don't pass it, it will be null . If you want to change this behaviour, then write an issue here: https://github.com/micronaut-projects/micronaut-core/issues

**Comment by korri123** [comment]
@altro3 Thank you for looking into it, I wasn't aware that this exception had been fixed in a snapshot release, will look into that for our codebase. Closing this issue.
