### ISSUE TITLE
Views are generated in root folder of project

### ISSUE THREAD

**Issue by ThraaxSession** [micronaut-projects/micronaut-openapi#859]
### Expected Behavior

The views are generated in build/target folder.

The issue is when I rename the target file. Do I have to use a full path for renaming??
![image](https://user-images.githubusercontent.com/3085830/204135885-85d58161-523e-432d-9e0f-f9192026393a.png)
![image](https://user-images.githubusercontent.com/3085830/204135875-7c25b93d-9d92-46b0-8d40-acd7c32350d6.png)

### Actual Behaviour

The views are generated under root of project:

> Task :kaptKotlin
Note: Generating OpenAPI Documentation
Note: Using KEBAB_CASE property naming strategy.
Note: Writing OpenAPI file to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\spaceup-openapi.yml
Note: Writing OpenAPI View to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\redoc\index.html
Note: Writing OpenAPI View Resources to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\redoc\res\res\redoc.standalone.js
Note: Writing OpenAPI View to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\rapidoc\index.html
Note: Writing OpenAPI View Resources to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\rapidoc\res\res\rapidoc-min.js
Note: Writing OpenAPI View to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\swagger-ui\index.html
Note: Writing OpenAPI View Resources to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\swagger-ui\res\res\swagger-ui.css
Note: Writing OpenAPI View Resources to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\swagger-ui\res\res\favicon-16x16.png
Note: Writing OpenAPI View Resources to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\swagger-ui\res\res\favicon-32x32.png
Note: Writing OpenAPI View Resources to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\swagger-ui\res\res\swagger-ui-bundle.js
Note: Writing OpenAPI View Resources to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\swagger-ui\res\res\swagger-ui-standalone-preset.js
Note: Writing OpenAPI View Resources to destination: D:\Projekte\Uberspace-Projekte\SpaceUp-Server\views\swagger-ui\res\material.css
Note: Creating bean classes for 37 type elements

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/3085830/204135438-0b5af9f9-7b69-4630-8c12-acb08237b752.png)
![image](https://user-images.githubusercontent.com/3085830/204135461-958c8f0c-3329-446c-b8df-bb5ea177e5aa.png)
![image](https://user-images.githubusercontent.com/3085830/204135801-3ab59d27-d524-4d12-b9ce-2c5d8298dbde.png)
![image](https://user-images.githubusercontent.com/3085830/204135740-93d7bf73-e1de-49e5-a9d9-7f87763438b9.png)

### Environment Information

Windows 11
Graalvm 22.2.0 

### Version

3.7.4

**Comment by altro3** [comment]
@ThraaxSession Hi! Could you create sample project to reproduce this problem? I tried to do it myself, but couldnt reproduce :-(

**Comment by ThraaxSession** [comment]
@altro3 did you change in the application configuration the "target.file" property? That is the point when the generation of views behaves weird. Else you can look up my mirror on GitHub spaceup-server.

**Comment by ThraaxSession** [comment]
@altro3 that's anyway somehow weird, as not only the property file is generated to the root but the whole package for swagger view.

**Comment by altro3** [comment]
@ThraaxSession hm.. yes, maybe. But this is old code. Interesting, the directory is taken relative to the file swagger :-). Yes, it might be worth adding a separate variable in which you can set the directory for displaying UI resources.
```
![изображение](https://user-images.githubusercontent.com/48474279/205093499-627f0b52-67d5-40da-b87c-b75cea745ccb.png)
```

**Comment by altro3** [comment]
@ThraaxSession fixed

**Comment by ThraaxSession** [comment]
@altro3 so there will be now a another property for the title?

**Comment by altro3** [comment]
No, now we have 2 different values:
`micronaut.openapi.target.file` - path to target generated swagger file (with filename)
`micronaut.openapi.views.dest.dir` - path to target generated openapi UI files

If you change one of these paths, the other path will remain the same.

Now these 2 paths are independent of each other.

**Comment by altro3** [comment]
@ThraaxSession This fix already released. Check it. If all ok, close issue, please :-)

**Comment by altro3** [comment]
@ThraaxSession Just add version to your dependency:
```groovy
    annotationProcessor "io.micronaut.openapi:micronaut-openapi:4.8.0"
```
