### ISSUE TITLE
Generating OpenAPI Documentation is logged with level=ERROR

### ISSUE THREAD

**Issue by roar-skinderviken** [micronaut-projects/micronaut-openapi#869]
### Expected Behavior

When running 
`mvn clean verify`
with a clean project generated by 
[launch.](https://micronaut.io/launch)
I expect no errors in build log.

![image](https://user-images.githubusercontent.com/7499642/205026562-a6584f91-804d-4893-9820-803709c4abb1.png)

### Actual Behaviour

When running
`mvn clean verify`
this appears in the build log:
```
[ERROR] Note: Generating OpenAPI Documentation
[ERROR] Note: Writing OpenAPI file to destination: /home/roars/temp/demo/target/classes/META-INF/swagger/demo-0.0.yml
[ERROR] Note: Creating bean classes for 1 type elements
```

### Steps To Reproduce

Go to 
https://micronaut.io/launch

Select 
- Java Version = 17
- Language = Kotlin
- Build Tool = Maven
- Test Framework = Kotest

Add feature "openapi"

Select "Generate Project", download source and build project.

### Environment Information

- Ubuntu 22.04
- JDK 17 Oracle

### Version

3.7.4

**Comment by altro3** [comment]
@roar-skinderviken Hi! I tried to create by your instruction. So, haven't ani problems with openapi.

These line aren't errors. Jsut informational logs. Why maven print it with `[ERROR]` mark - I don't know. The micronaut openapi itself does not write anything to the console or logs, it sends information to the processor annotation context. And how then it gets into the console - I do not know. But, for example, if you use gradle, then you will see the same lines without a prefix `[ERROR]` in the console.

**Comment by roar-skinderviken** [comment]
Thanks for quick response on this one!

It's not up to me to replace Maven with Gradle at customer site, but I'll bring the information further.

Best regards, Roar Skinderviken

**Comment by nbrugger-tgm** [comment]
As far as I remember even in gradle the text is printed red. It isn't prefixed with [Error] but still red. I will post a reproduction example asap? :)

**Comment by altro3** [comment]
@nbrugger-tgm yes, I know. But anyway, that's not a problem of micronaut-openapi. You need to create issue in [micronaut-core](https://github.com/micronaut-projects/micronaut-core)

**Comment by altro3** [comment]
@roar-skinderviken @nbrugger-tgm Unfortunately, this is specific to the annotation processor in the JDK. I tried to fix the problem through the public api, but unfortunately it can't be done without access to the internal api. You can see detailed information here:: https://github.com/micronaut-projects/micronaut-core/issues/9121

**Comment by roar-skinderviken** [comment]
@altro3 Thanks for looking into this.
