### ISSUE TITLE
Swagger UI resources cannot be loaded behind a reverse proxy (with path prefix strip)

### ISSUE THREAD

**Issue by srettenmeier** [micronaut-projects/micronaut-openapi#878]
### Expected Behavior

When running an app behind a reverse proxy, that is also stripping path prefixes, 
the Swagger UI resources (JS, CSS) should be loaded taking the stripped prefix into account.

### Actual Behaviour

With version 4.7.1, the generated Swagger UI's `index.html` references resources absolutely (e.g. `<script src='/swagger-ui/res/swagger-ui-bundle.js'>`). With these references in place the browser cannot load the resources, as the stripped path prefix is not taken into account.

Prior, we used version 4.5.2. There the references where relative (e.g. `<script src="res/swagger-ui-bundle.js">`). This way the resources could also be loaded behind a reverse proxy

### Steps To Reproduce

1. Start an arbitrary Micronaut app with a Swagger UI (generated by Gradle kapt processor)
2. Set up a reverse proxy (e.g. nginx)
3. Configure the reverse proxy to strip a certain prefix (e.g. `/sample-app`) and forward requests to the Micronaut app
4. Open the Swagger UI in your browser by using the reverse proxy's URL including the path prefix (e.g. `http://<reverse proxy address>/sample-app`)

### Version

4.7.1

**Comment by altro3** [comment]
Hi! This is not an error, but you can change the path to the resources as you need using the property `swagger-ui.js.url`. 
```groovy
options.forkOptions.jvmArgs += "-Dmicronaut.openapi.views.spec=swagger-ui.enabled=true,swagger-ui.js.url=res/"
```

**Comment by altro3** [comment]
But I found a different bug with *.js.url properties. Fix is here #879

**Comment by srettenmeier** [comment]
Hi @altro3,

first of all, thanks for the super fast feedback! 


> Hi! This is not an error, but you can change the path to the resources as you need using the property `swagger-ui.js.url`.
> 
> ```groovy
> options.forkOptions.jvmArgs += "-Dmicronaut.openapi.views.spec=swagger-ui.enabled=true,swagger-ui.js.url=res/"
> ```

That's what I tried, but it didn't have the desired effect. The resources were still referenced absolutely (e.g. <script src='/swagger-ui/res/swagger-ui-bundle.js'>).

> But I found a different bug with *.js.url properties. Fix is here #879

I'm glad you found out that this is a bug and already fixed it.

Thank you so much!

**Comment by altro3** [comment]
This fix already released. Check it. If all ok, close issue, please :-)

**Comment by srettenmeier** [comment]
> This fix already released. Check it. If all ok, close issue, please :-)

Now the resources are referenced relatively in the `index.html` as expected. 
But all of a sudden - when running the annotation processor - the JS files are no longer being generated, thus the Swagger UI cannot work.

![image](https://user-images.githubusercontent.com/1714086/206568662-1ca11d1d-6111-4436-acda-dd5f7b16a755.png)

**Comment by altro3** [comment]
@srettenmeier fixed it here https://github.com/micronaut-projects/micronaut-openapi/pull/881

**Comment by altro3** [comment]
@srettenmeier Hi! Try to use version 4.8.1 - now it should work

**Comment by srettenmeier** [comment]
@altro3 works like a charm! Thank you!
