### ISSUE TITLE
Error finalizing type visitor - ConcurrentModificationException 

### ISSUE THREAD

**Issue by kevind-wgu** [micronaut-projects/micronaut-openapi#894]
### Expected Behavior

I recently upgraded to using Micronaut 3.8.0 and immediately started getting compile time errors. I trace the issue to 
 micronaut-openapi 4.8.1. I expect the OpenApi code to generate without errors. 

### Actual Behaviour

It is difficult to tell what exactly in my code is triggering the problem code. What I see on the outside is this error during the maven build.
`
[ERROR] Error finalizing type visitor [io.micronaut.openapi.visitor.OpenApiApplicationVisitor@6520625f]: null
`

Debugging into the OpenApiApplicationVisitor I found this stacktrace

```
java.util.ConcurrentModificationException
        at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486)
        at java.base/java.util.TreeMap$KeyIterator.next(TreeMap.java:1540)
        at io.micronaut.openapi.visitor.OpenApiApplicationVisitor.finish(OpenApiApplicationVisitor.java:945)
```

Looking at that code it is doing this 
```
                Map<String, Schema> schemas = openAPI.getComponents().getSchemas();
                if (CollectionUtils.isNotEmpty(schemas)) {
                    String openApiJson = ConvertUtils.getJsonMapper().writeValueAsString(openAPI);
                    for (String schemaName : schemas.keySet()) {
                        if (!openApiJson.contains(COMPONENTS_SCHEMAS_REF + schemaName)) {
                            schemas.remove(schemaName);
                        }
                    }
                }
```

Modifying a Map (schemas.remove) while in a foreach for that map will always cause a ConcurrentModificationException.

### Steps To Reproduce

If needed I can publish a repository that will cause the error. But looking at the code the coding error is obvious.

### Version

micronaut - 3.8.0
micronaut-openapi - 4.8.1

**Comment by rnielsen** [comment]
I am seeing this issue too.  A workaround until the fix is released is to use micronaut-openapi 4.7.1
