### ISSUE TITLE
kotlinKapt crash in some cases when use ArrayList<T> or ArrayDeque<T> as return type in controller

### ISSUE THREAD

**Issue by marendil** [micronaut-projects/micronaut-openapi#903]
### Expected Behavior

Project should build successfully.

### Actual Behaviour

After calling `gradlew clean build` I've got following error:
```
> Task :kaptKotlin
Note: Generating OpenAPI Documentation
error: Error finalizing type visitor [io.micronaut.openapi.visitor.OpenApiApplicationVisitor@107268a5]: null
Note: Creating bean classes for 2 type elements
error: Error finalizing type visitor [io.micronaut.openapi.visitor.OpenApiApplicationVisitor@107268a5]: null

> Task :kaptKotlin FAILED

FAILURE: Build failed with an exception.
```

### Steps To Reproduce

I've created new project in Micronaut Launcher https://micronaut.io/launch/ with following options:

Application Type: Micronaut Application
Java version: 17
Micronaut Version: 3.8.0
Language: Kotlin
Build Tool: Gradle Kotlin
Test Framework: Kotest
In features: swagger-ui and openapi

Next I've created new simple data class:

`data class AC(val someField: String)`

and changed index method so it returns empty `ArrayList<AB>`

`fun index() = ArrayList<AB>()`

Then I call  `gradlew clean build` and it fails.

What is funny following class names works:

```
A
Ab
SomeClass
Xbcd
```

but following class names are not:
```
Abc
AB
ABc
AwesomeClass
```

what is more consusing is that it always works for List or MutableList but doesn't work for ArrayList and ArrayDeque

It starts to crash from version 4.8.0 of micronaut-openapi, after downgrading to 4.7.1 it works like a charm.

Full gradle stacktrace in attachment.
[fullstacktrace.txt](https://github.com/micronaut-projects/micronaut-openapi/files/10401018/fullstacktrace.txt)

### Environment Information

- JDK 17
- Gradle wrapper 7.5.1

### Example Application

https://github.com/marendil/demo

### Version

3.8.0

**Comment by altro3** [comment]
Fixed here: https://github.com/micronaut-projects/micronaut-openapi/pull/905

**Comment by Colonel-Rogue** [comment]
This also occurs when returning a [kotlin Flow](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/) from a controller function.
Workaround is to return a https://www.reactive-streams.org/reactive-streams-1.0.0-javadoc/org/reactivestreams/Publisher.html (which is trivial when using `org.jetbrains.kotlinx:kotlinx-coroutines-reactor`)
