### ISSUE TITLE
Micronaut Project with both Java and Groovy, Swagger Generation

### ISSUE THREAD

**Issue by wmunyan** [micronaut-projects/micronaut-openapi#904]
### Issue description

I have a project with both Java and Groovy classes, with some controllers in each.  I have configured my `build.gradle` as such to enable compilation of both:
```
sourceSets {
    main {
        java {
            srcDirs = []
        }
        groovy {
            srcDirs = ['src/main/java', 'src/main/groovy']
        }
    }
}
```
However, when assembling my project, the swagger YAML file is only generating for controllers in Groovy classes.  Swagger annotations in Java classes and controllers defined in Java classes are not being picked up.  A workaround could be to just define all my controllers in Groovy, but if there's a way to generate everything as-is, that would probably be better.

**Comment by altro3** [comment]
@wmunyan Hi! Could you create a sample project for this case? I'll try to do something to make it work

**Comment by wmunyan** [comment]
Ill see what I can throw together, will be a good exercise to ensure I can recreate the issue :)

**Comment by wmunyan** [comment]
Try this guy - https://github.com/wmunyan/openapi-java-groovy - has 1 java controller, 1 groovy controller.

Pull Repo
`gradlew clean assemble`
Run the app
http://localhost:7777/wkm/api/swagger-ui shows only the Groovy controller, but `/wkm/api/groovy` and `/wkm/api/java` both exist.

Hope it works :)

**Comment by altro3** [comment]
In general, the point is not micronaut-openapi, but micronaut-inject. The problem is that java files are simply ignored in this case.

@graemerocher Could you tell me if it's worth making a bug for Micronaut-inject or is there a way to make such a project work correctly?

**Comment by altro3** [comment]
@graemerocher Could you help?

**Comment by djKianoosh** [comment]
The only way I was able to get this to somewhat work was to have this in `build.gradle`

```
  annotationProcessor "io.micronaut.openapi:micronaut-openapi:4.8.4"
  implementation "io.micronaut.openapi:micronaut-openapi:4.8.4"
```

and then in addition to using `@OpenAPIDefinition`, I have an extra `@OpenAPIInclude(classes ={ ...list of groovy classes...}`. My only issue is that VSCode doesn't compile groovy properly so there's no code completion (I believe IntelliJ works better but not sure) but this compiles and generates the swagger docs correctly. As a side effect, it does automatically generate a second swagger.yml as well with only the groovy classes, but at least the main one has all my endpoints.

**Comment by djKianoosh** [comment]
> The only way I was able to get this to somewhat work was to have this in `build.gradle`
> 
> ```
>   annotationProcessor "io.micronaut.openapi:micronaut-openapi:4.8.4"
>   implementation "io.micronaut.openapi:micronaut-openapi:4.8.4"
> ```
> 
> and then in addition to using `@OpenAPIDefinition`, I have an extra `@OpenAPIInclude(classes ={ ...list of groovy classes...}`. My only issue is that VSCode doesn't compile groovy properly so there's no code completion (I believe IntelliJ works better but not sure) but this compiles and generates the swagger docs correctly. As a side effect, it does automatically generate a second swagger.yml as well with only the groovy classes, but at least the main one has all my endpoints.

Note this is the same thing happening in this other closed issue: https://github.com/micronaut-projects/micronaut-openapi/issues/602#issuecomment-1103225478

My understanding is the groovy annotationProcessor doesn't behave the same as the java one, so if you declare your deps such as:

```
  annotationProcessor "io.micronaut.openapi:micronaut-openapi:4.8.4"
  implementation "io.swagger.core.v3:swagger-annotations:2.2.8"
```
 this will generate swagger docs for java controllers, but you can't use `OpenAPIInclude`. And if you use 
```
  annotationProcessor "io.micronaut.openapi:micronaut-openapi:4.8.4"
  implementation "io.micronaut.openapi:micronaut-openapi:4.8.4"
```
then you get two sets of swagger docs generated, but can use `OpenAPIInclude` to have all java+groovy controllers included in at least one of the two sets of generated swagger docs.

**Comment by graemerocher** [comment]
The way Micronaut works today I don't believe it is feasible to allow mixed language generation of Swagger documentation unfortunately.
