### ISSUE TITLE
kotlinKapt crashes when a component or value is injected into the controller

### ISSUE THREAD

**Issue by darylrobbins** [micronaut-projects/micronaut-openapi#911]
### Expected Behavior

Project should build successfully

### Actual Behaviour

After calling `gradlew clean build` I receive the following error:

```
> Task :kaptKotlin FAILED
5 actionable tasks: 5 executed
Note: Generating OpenAPI Documentation
error: Error finalizing type visitor [io.micronaut.openapi.visitor.OpenApiApplicationVisitor@7787e4cf]: null
Note: Creating bean classes for 3 type elements
error: Error finalizing type visitor [io.micronaut.openapi.visitor.OpenApiApplicationVisitor@7787e4cf]: null

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

### Steps To Reproduce

I started from the test case for #903 and modified to isolate this issue.

Application Type: Micronaut Application
Java version: 17
Micronaut Version: 3.8.0
Language: Kotlin
Build Tool: Gradle Kotlin
Test Framework: Kotest
In features: swagger-ui and openapi

I define a controller with either an injected component or value.

```
@Controller("/demo")
class DemoController(
    // Fails with either of these two present:
    @Inject val demoService: DemoService, // (1)
    @Value("\${baseurl:}") val baseUrl: String, // (2)
) { ... }
```

It will fail with either (1) or (2) commented out.

Full gradle stacktrace in attachment.
[stacktrace.txt](https://github.com/micronaut-projects/micronaut-openapi/files/10417999/stacktrace.txt)

### Environment Information

- Operating System: Mac OS
- Java: Amazon Corretto 17 (but happens on OpenJDK as well)

### Example Application

https://github.com/darylrobbins/micronaut-openapi-test

### Version

3.8.0

**Comment by altro3** [comment]
@darylrobbins Hi! Already fixed. Checked with version 4.8.2-SNAPSHOT. This is the same problem as here https://github.com/micronaut-projects/micronaut-openapi/issues/903 - you return ArrayList, not List
