### ISSUE TITLE
Incorrect warning during openapi generation: 'name' property can't set for securityScheme with type http.

### ISSUE THREAD

**Issue by StefanSrf** [micronaut-projects/micronaut-openapi#912]
### Expected Behavior

no warning is logged during the build

### Actual Behaviour

the following warning is logged when generating the openAPI documentation:
warning: 'name' property can't set for securityScheme with type http. Skip it

Note: the generated openapi yml file is correct, the security scheme with the given name is added to the yml. If the 'name' value is removed from the securityScheme the warning disappears, but then the security scheme is no longer added to the yml.

### Steps To Reproduce

Add the following to the Application

@SecurityScheme(
    name = "basicAuth",
    scheme = "Basic",
    type = SecuritySchemeType.HTTP,
)

build the project

### Environment Information

Ubuntu 22.04
JDK 17

### Version

3.8.0

**Comment by altro3** [comment]
@StefanSrf already fixed here: https://github.com/micronaut-projects/micronaut-openapi/pull/892

Wait release 4.8.2
