### ISSUE TITLE
Jakarta's annotations are ignored

### ISSUE THREAD

**Issue by nbrugger-tgm** [micronaut-projects/micronaut-openapi#921]
### Expected Behavior

When using annotations from the `jakarta.validation.*` and `jakarta.annotations.*` package they should behave the same as from `javax.*` and produce oas that includes the annotations.

### Actual Behaviour

The annotations are ignored.

### Steps To Reproduce

1. Create a project with an API endpoint that takes an Pojo as parameter
2. use `@Valid` on that parameter
3. create field in the   `@jakarta.annotations.Nullable @jakarta.validation.Size(min=1,max=2) public String a;`
4. inspect the generated yml file  

### Environment Information

Any environment.

Maybe this should be done in sync with: https://github.com/micronaut-projects/micronaut-core/issues/4770 but it might also be a good idea to support it before micronaut core does it. At least for `@Nullable` since Nullable doesn't create any behavior but just adds intellisense.

I would argue that every annotation `*.Nullable` should be considered since there are 100 and one (Non)Nullability annotation providers like `jetbrains`, `findbugs`, `spotbugs` and so on

### Version

`3.*.*`

**Comment by altro3** [comment]
@nbrugger-tgm Could you create sampl project to reproduce your problem?Because I added support for jakarta validation . Should work. Also, specify which version of mcironaut-openapi you are using

**Comment by nbrugger-tgm** [comment]
Hi, thanks for the quick reply!
I created a reproduction here: https://github.com/nbrugger-tgm/micronaut-reproductions/tree/main/921

for `micronaut.Nullable` it generates the `nullable` property for `jakarta.annotation.Nullable` not. The `jakarta.validation` annotations seem to work so sorry for that.

**Comment by altro3** [comment]
@nbrugger-tgm fixed here: #923

**Comment by nbrugger-tgm** [comment]
Thank you for the quick fix. If there is any easy issue to create PRs for, for 4.0 micronaut release let me know if help is needed :)
