### ISSUE TITLE
Rapidoc: POST routes returning 'Request Aborted' error

### ISSUE THREAD

**Issue by rodrigotm** [micronaut-projects/micronaut-openapi#933]
### Expected Behavior

After upgrading to the latest version of Micronaut (3.8.4, from 2.x), I noticed that POST routes in Rapidoc were returning a "Response Status: Request Aborted" error and not even reaching the API. All other methods (GET, PUT, DELETE, etc.) were working fine. I spent hours trying to figure out if I had made a mistake or if something had been changed for security reasons, but I couldn't find any information on this issue either in my code or online. It seems that there is a bug in the 'before-try' listener in the Rapidoc index.html file, which aborts POST requests.

https://github.com/micronaut-projects/micronaut-openapi/blob/master/openapi/src/main/resources/templates/rapidoc/index.html

My question is whether this is a bug or a security feature that was intentionally implemented. I also noticed that Swagger-UI continues to support POST requests.

If this is a security feature, I suggest creating a configuration option that can be enabled on a per-environment basis, giving us the freedom to enable it for local and sandbox environments.

### Version

3.8.4

**Comment by altro3** [comment]
@rodrigotm Which micronaut-openapi version do you use? Try to use latest version 4.8.4 and tell me problem solved or not

**Comment by altro3** [comment]
@rodrigotm Hm... I think it was just mistake. Removed this block here: #937
