### ISSUE TITLE
Duplicate path parameters when using RequestBean in a controller that inherits from base class

### ISSUE THREAD

**Issue by patimen** [micronaut-projects/micronaut-openapi#948]
### Expected Behavior

If:

1. A path parameter is caught using a RequestBean
2. The RequestBean variable is not named the same as the parameter
3. The containing Controller inherits from ANY class
4. Using Kotlin (unsure about Java)

We expect the path parameter to be output only once in the openapi spec:
```openapi
/{path}/simple:
    get:
      operationId: getPath_1
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getPath_1 200 response
          content:
            application/json:
              schema:
                type: string
```

### Actual Behaviour

The parameter is output twice:
```openapi
/{path}/simple:
    get:
      operationId: getPath_1
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
      - name: path
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getPath_1 200 response
          content:
            application/json:
              schema:
                type: string
```

### Steps To Reproduce

1. Catch a  path parameter using a RequestBean
2. RequestBean variable is not named the same as the parameter
3. The containing Controller inherits from ANY class
4. Using Kotlin

### Environment Information

MacOS
Java 11

(For all details, see the project)

### Example Application

https://github.com/patimen/duplicatepathparams

### Version

3.7.3

**Comment by altro3** [comment]
@patimen Hi! Hmm... interesting, this bug really couldn't be reproduced in java, but I see that your example does reproduce this bug. In general, in any case, I added additional protection against duplicate parameters. Checked on your example - everything works correctly. Wait for the next release
