### ISSUE TITLE
micronaut.openapi.additional.files does not merge .yaml files

### ISSUE THREAD

**Issue by vserrago** [micronaut-projects/micronaut-openapi#957]
### Expected Behavior

When using the feature to [combine openapi schemas](https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#mergingSchemas), I expect it to merge a `.yaml` file that I place into the folder.

### Actual Behaviour

The processor processes files that end in `.yml`, but not `.yaml`. It seems that [when processing files](https://github.com/micronaut-projects/micronaut-openapi/blob/master/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java#L594), only `.yml` files are picked up.

### Steps To Reproduce

 1. Have a gradle project folder with the following contents:

```
├── build.gradle.kts
├── openapi
│   └── openapi-additional.yaml
├── openapi.properties
└── src
    ├── main
    └── test
```

2. with `openapi.properties` specifying the following:

```
micronaut.openapi.target.file=build/azure-functions/openapi.yml
micronaut.openapi.additional.files=openapi
```

3. Build the project,
4. Observe that `build/azure-functions/openapi.yml` does not contain any of the contents of `openapi-additional.yaml`

### Version

4.8.4

**Comment by altro3** [comment]
@vserrago Fixed here https://github.com/micronaut-projects/micronaut-openapi/pull/960 . Wait next release micronaut-openapi
