### ISSUE TITLE
Add support for the new requiredMode to replace required

### ISSUE THREAD

**Issue by swaechter** [micronaut-projects/micronaut-openapi#962]
## Problem

Swagger Core deprecated the `required` field in `Schema` with `requiredMode`. For more information see https://github.com/swagger-api/swagger-core/pull/4286 . Upgrading to the latest Micronaut OpenAPI + Swagger OpenAPI core version marks this field as deprecated:

![Bug11_1](https://user-images.githubusercontent.com/5626755/227043910-4b5ffbad-6394-4d40-a200-6bb807c7380c.png)

Switching to the new annotation value makes the compiler happy (No warning):

![Bug11_2](https://user-images.githubusercontent.com/5626755/227043988-f781f1c3-c7dc-49a3-9d8d-4255a1d5d6c6.png)

But this new annotation value isn't picked up by Micronaut OpenAPI, so the `required` field in the generated OpenAPI file is dropped, which leads to a compiler error in our TypeScript frontend (The value is now undefined):

![Bug11_3](https://user-images.githubusercontent.com/5626755/227044173-7c3a0356-93dc-4413-b9ea-059791474d49.png)

## Solution

Is it possible to add support for `requiredMode` which takes precedence over `required`? There was another annotation value that was deprecated but I can't remember.

## Example

You can reproduce the problem with bug 11 in https://github.com/swaechter/openapiproblems

# Version

* Platform: Linux Debian
* Java: OpenJDK 64-Bit Server VM (build 17.0.4+8-Debian-1deb11u1, mixed mode, sharing)
* Micronaut Application Gradle Plugin: 3.7.2
* Micronaut Version: 3.8.7

**Comment by swaechter** [comment]
Ah found it: `readOnly` and `writeOnly` were also deprecated and replaced with `accessMode` in OpenAPI Core version 2.0.0 (2018): https://github.com/swagger-api/swagger-core/releases/tag/v2.0.0 . I am not sure if this feature was ever supported, because it interferes with JSON serialization/deserialization. So nothing to worry about, but still a cool feature in OpenAPI :)

**Comment by altro3** [comment]
@swaechter Hi! Added support `requiredMode` here #968. `accessMode` already supported.

Also turn on alphabetical sort tags by default for swagger-ui and redoc (rapidoc already sort it) here #968. Found this problem on your repo :-).

I found some more bug descriptions in your repo. Could you actualize them with latest micronaut-openapi version? If there's anything else, I'll fix it.

**Comment by altro3** [comment]
@swaechter Hi! No, I think, need to release all these fixes before micronaut 4.0. Will be in release micronaut-openapi 4.8.6. I'll ask @graemerocher  to merge everything and make a release - there are already enough fixes for the new release.

**Comment by altro3** [comment]
@swaechter you can check fixes in current release 4.8.6. And just for you know: you don't need to use `@Schema` annotation for your case. You can add javadoc and `@NotNull` annotation. Swagger file will be identical. For example, this code
```java
@Schema(description = "My description", requiredMode = Schema.RequiredMode.REQUIRED)
private MyClass myFiled;
```
and this
```java
/**
 * My description
 */
@NotNull
private MyClass myFiled;
```
generate the same swagger file.

**Comment by swaechter** [comment]
@altro3 Thanks a lot for the fix. I justed tested it successfully. I always thought that the required means the key has to exists in the JSON object, but can be null :)

**Comment by altro3** [comment]
@swaechter understand. But description may be in javadoc ;-)
