### ISSUE TITLE
Add option to disable(/enable) OpenAPI generation

### ISSUE THREAD

**Issue by aentwist** [micronaut-projects/micronaut-openapi#977]
## User Story

When running the Micronaut development server via `./gradlew clean run -t`, OpenAPI and views are generated, which takes extra time. I want to minimize the time taken for the server to start so that Gradle's restart on change provides the best DX / productivity.

## Proposed Solution

This should be possible in some way by providing settings depending on the Gradle task. That is, for the `run` task, provide settings to disable OpenAPI and views.

Settings for enabling/disabling views seem to exist. e.g. the system properties equivalent of `redoc.enabled=true`.
See https://micronaut-projects.github.io/micronaut-openapi/latest/guide/#viewsGenerationWithSystemProperties

A setting for controlling OpenAPI generation does not seem to exist. I propose adding it. Mirror views settings by making it an `enabled` setting. Set the default to true so that it is not a breaking change.

## Alternative Considerations

Make it a '`disableOpenApi`' setting. Default to false. Allow users to set to true.

## After the fact alternative consideration

Move OpenAPI to its own Gradle task (would involve adding a Gradle plugin?)

**Comment by altro3** [comment]
@aentwist Added new system proeprty `micronaut.openapi.enabled`. If you want to diable it - just set false. But this property will be available in next release

**Comment by aentwist** [comment]
Thanks for picking this up so fast!

**Comment by aentwist** [comment]
Does the setting also disable views, or will they need to be explicitly disabled?
