### ISSUE TITLE
Groovy Project, `micronaut.openapi.expand` properties not compiling

### ISSUE THREAD

**Issue by wmunyan** [micronaut-projects/micronaut-openapi#980]
### Expected Behavior

I have a Micronaut project that used Gradle for builds, and have a mix of Groovy and Java, so my compilation task looks like this:
```
tasks.withType(GroovyCompile) {
    groovyOptions.fork = true
    groovyOptions.forkOptions.jvmArgs.add('-Dgroovy.parameters=true')
    groovyOptions.forkOptions.jvmArgs.add('-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop')
}
```
This worked to generate swagger yml and enable the swagger-ui in my application.  However, the generated yml did not have a `version` value within the `@Info` element, so it wouldn't import into Postman.  I am using a semantic versioning plugin in my `build.gradle`, so I wanted to enable a `micronaut.openapi.expand.apiversion` property in the above compilation task, like this:

```
tasks.withType(GroovyCompile) {
    groovyOptions.fork = true
    groovyOptions.forkOptions.jvmArgs.add('-Dgroovy.parameters=true')
    groovyOptions.forkOptions.jvmArgs.add('-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop')

    // Adding here.  getVersion() is a task to retrieve the current 
    def v = "-Dmicronaut.openapi.expand.apiversion=${version}".toString()
    groovyOptions.forkOptions.jvmArgs.add(v)
}
```

In my `Application.groovy` I have the following annotation:
```
@OpenAPIDefinition(
    info = @Info(
        title = "My Microservice",
        version = "${apiversion}",
        ...)
)
```
I would expect that, at compile-time, the `micronaut.openapi.expand.apiversion` property would resolve and the `version` would be correctly populated in my swagger yml output.

### Actual Behaviour

I receive a compilation error:

```
Note: Generating OpenAPI Documentation
startup failed:
C:\path\to\the\Application.groovy: 25: [Static type checking] - The variable [apiversion] is undeclared.
 @ line 25, column 22.
           version = "${apiversion}",
                        ^
```

### Steps To Reproduce

This GitHub repo: https://github.com/wmunyan/openapi-java-groovy shows the basic setup I have.  Executing a `gradlew clean assemble` will provide the compilation error.

### Environment Information

Windows 10, Java 17, Micronaut 3.8.8, Groovy 3.0.13

### Example Application

https://github.com/wmunyan/openapi-java-groovy

### Version

3.8.8

**Comment by altro3** [comment]
@wmunyan That is not problem of mcrionaut-openapi. That is yoour mistake: you use groovy, and groovy has his own instrument to replace placeholders. Compilation failed, because you try to set `apiversion` variable from code, not from system properties. If you want to set parameters from system properties you need to escape `$` symbol (like this `version = "\${apiversion}"`) or use single quotes - `version = '${apiversion}'`.

About `micronaut.openapi.expand` properties: well, it is old solution and it works, but with some limitations: you can set exanded properties only in `openapi.properties` file.

For you I recomend use system properties withou expand prefix like this:
```
groovyOptions.forkOptions.jvmArgs.add('-Dapiversion=' + version)
```

**Comment by wmunyan** [comment]
@altro3 this is great - thank you for this!  I was able to get this working using the tips you suggested!  I'll close the issue
