### ISSUE TITLE
Generated index.html not using configured mapping url.

### ISSUE THREAD

**Issue by steven-ww** [micronaut-projects/micronaut-openapi#981]
### Expected Behavior

When changing the mapping property of the swagger-ui property in application.yml, the generated index.html file should use this new mapping in order to locate the swagger ui resources.

Changing the mapping for the swagger-ui should generate an index.html file with the new path to the resources.

`static-resources:
            swagger:
                enabled: ${SWAGGER_ENABLED:true}
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger/ui/**`

`<head>
    <meta charset='UTF-8' />
    <title>basket-bff-1.0.0</title>
    <link rel='icon' type='image/png' href='/swagger/ui/res/favicon-32x32.png' sizes='32x32' />
    <link rel='icon' type='image/png' href='/swagger/ui/res/favicon-16x16.png' sizes='16x16' />
    <script src='/swagger/ui/res/swagger-ui-bundle.js'></script>
    <script src='/swagger/ui/res/swagger-ui-standalone-preset.js'></script>
    <link rel='stylesheet' type='text/css' href='/swagger/ui/res/swagger-ui.css' />
    <link rel='stylesheet' type='text/css' href='/swagger/ui/res/flattop.css' />
    
</head>`

The path then to the index.html is ../swagger/ui/index.html (works)
And the index.html file should be able to load the required UI resources from that same url.

### Actual Behaviour

However, if you change the mapping, the generated index.html file does not reflect the new url and the swagger ui breaks. (The index.html file itself is found at the new url, however, it does not load any of the resources)

`        
static-resources:
            swagger:
                enabled: ${SWAGGER_ENABLED:true}
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger/ui/**
`        
                
That is, I'd expect the index.html file to contain the new mapping, however, it still contains the default mapping. 

`<head>
    <meta charset='UTF-8' />
    <title>basket-bff-1.0.0</title>
    <link rel='icon' type='image/png' href='/swagger-ui/res/favicon-32x32.png' sizes='32x32' />
    <link rel='icon' type='image/png' href='/swagger-ui/res/favicon-16x16.png' sizes='16x16' />
    <script src='/swagger-ui/res/swagger-ui-bundle.js'></script>
    <script src='/swagger-ui/res/swagger-ui-standalone-preset.js'></script>
    <link rel='stylesheet' type='text/css' href='/swagger-ui/res/swagger-ui.css' />
    <link rel='stylesheet' type='text/css' href='/swagger-ui/res/flattop.css' />
    
</head>
`

While the index.html page loads, it's blank.
              

### Steps To Reproduce

Create a micronaut project with some rest endpoints. 
Add the OpenApi annotation to your Application File.
Enable swagger generation with the default properties set.
Build and start micronaut application.
Load the swagger ui at http://localhost:8080/swagger-ui/index.html

Now change the application.yml properties to have a different mapping for the swagger ui E.g. 

`        static-resources:
            swagger:
                enabled: ${SWAGGER_ENABLED:true}
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger/ui/**`
                
Hit the new URL http://localhost:8080/swagger/ui/index.html.
The index.html page loads, but the page is blank

### Environment Information

MacOs/Linux
JDK 17

### Version
4.8.6

**Comment by altro3** [comment]
@steven-ww Hi! This is not a bug. You forgot to set to set parameter `swagger-ui.js.url=/swagger/ui/` to property `micronaut.openapi.views.spec`. Final value must be like this:
```
-Dmicronaut.openapi.views.spec=swagger-ui.enabled=true,swagger-ui.js.url=/swagger/ui/
```

**Comment by steven-ww** [comment]
Thank you! That works.
